Repository vuetifyjs/vuetify, pull requests merged in 2018-02, with the labels that each got.

#3295 fix(VFooter): update application after mount when using auto height
  src/components/VFooter/VFooter.js
  src/mixins/applicationable.js
Labels: bug

#3247 refactor: improve install function
  build/config.js
  build/webpack.base.config.js
  build/webpack.dev.config.js
  build/webpack.prod.config.js
  src/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
  src/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
  src/components/VSelect/__snapshots__/VSelect.spec.js.snap
  src/components/VSelect/__snapshots__/VSelect2.spec.js.snap
  src/components/Vuetify/index.js
  src/index.js
Labels: enhancement

#3314 fix(ssr): allow theme to be applied with vue-meta
  src/components/VApp/mixins/app-theme.js
Labels: bug

#3350 Fix/#3270 tabs router link
  src/components/VTabs/VTab.js
Labels: bug

#3351 fix(build): use babel-transform-define instead of webpack.DefinePlugin
  .babelrc
  build/babel-transform-define.js
  build/webpack.base.config.js
  package.json
  src/components/Vuetify/index.js
  yarn.lock
Labels: bug, critical

#3320 feat: Set header font via `$header-font-family`
  src/stylus/elements/_typography.styl
  src/stylus/settings/_variables.styl
Labels: enhancement, pending merge

#3191 fix: reset page to 1 when sorting changes
  src/mixins/data-iterable.js
Labels: bug

#3353 Remove outline on data table headers, add focus effect
  src/stylus/components/_data-table.styl
Labels: enhancement

#3324 enh/expansion-panel
  src/components/VExpansionPanel/VExpansionPanel.js
  src/components/VExpansionPanel/VExpansionPanel.spec.js
  src/components/VExpansionPanel/VExpansionPanelContent.js
  src/components/VExpansionPanel/__snapshots__/VExpansionPanel.spec.js.snap
  src/stylus/settings/_theme.styl
Labels: enhancement

#3365 fix(applicationable): updated process
  src/components/Vuetify/mixins/application.js
  src/mixins/applicationable.js
Labels: bug
