Repository vuetifyjs/vuetify, pull requests merged in 2018-12, with the labels that each got.

#5672 fix(VDatePicker): display proper year when model is null
  packages/vuetify/src/components/VDatePicker/VDatePicker.js
  packages/vuetify/test/unit/components/VDatePicker/VDatePicker.date.spec.js
Labels: T: bug

#5685 feat(VTimePicker, VDatePicker): disabled prop
  packages/vuetify/src/components/VDatePicker/VDatePicker.js
  packages/vuetify/src/components/VDatePicker/VDatePickerHeader.js
  packages/vuetify/src/components/VDatePicker/VDatePickerTitle.js
  packages/vuetify/src/components/VDatePicker/VDatePickerYears.js
  packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.js
  packages/vuetify/src/components/VTimePicker/VTimePicker.js
  packages/vuetify/src/components/VTimePicker/VTimePickerClock.js
  packages/vuetify/src/components/VTimePicker/VTimePickerTitle.js
  packages/vuetify/src/stylus/components/_date-picker-header.styl
  packages/vuetify/src/stylus/components/_date-picker-table.styl
  packages/vuetify/src/stylus/components/_date-picker-title.styl
  packages/vuetify/test/unit/components/VDatePicker/VDatePicker.date.spec.js
  packages/vuetify/test/unit/components/VDatePicker/VDatePickerDateTable.spec.js
  packages/vuetify/test/unit/components/VDatePicker/VDatePickerHeader.spec.js
  packages/vuetify/test/unit/components/VDatePicker/VDatePickerTitle.spec.js
  packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePicker.date.spec.js.snap
  packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePickerDateTable.spec.js.snap
  packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePickerHeader.spec.js.snap
  packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePickerTitle.spec.js.snap
  packages/vuetify/test/unit/components/VTimePicker/VTimePicker.spec.js
  packages/vuetify/test/unit/components/VTimePicker/VTimePickerClock.spec.js
  packages/vuetify/test/unit/components/VTimePicker/VTimePickerTitle.spec.js
  packages/vuetify/test/unit/components/VTimePicker/__snapshots__/VTimePicker.spec.js.snap
  packages/vuetify/test/unit/components/VTimePicker/__snapshots__/VTimePickerClock.spec.js.snap
  packages/vuetify/test/unit/components/VTimePicker/__snapshots__/VTimePickerTitle.spec.js.snap
Labels: T: feature

#5678 feat(VDatePicker): show week number
  packages/vuetify/src/components/VDatePicker/VDatePicker.js
  packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.js
  packages/vuetify/src/stylus/components/_date-picker-table.styl
  packages/vuetify/test/unit/components/VDatePicker/VDatePickerDateTable.spec.js
  packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePickerDateTable.spec.js.snap
Labels: T: feature

#4208 feat(VAutocomplete): add autoSelectFirst prop
  packages/vuetify/src/components/VAutocomplete/VAutocomplete.js
  packages/vuetify/test/unit/components/VAutocomplete/VAutocomplete.spec.js
Labels: T: feature

#5817 docs: correct affix position description
  packages/vuetifyjs.com/src/lang/en/mixins/DataIterable.json
Labels: T: documentation

#5816 fix(VDatePicker): change clickable area of month/year in header
  packages/vuetify/src/components/VDatePicker/VDatePickerHeader.js
  packages/vuetify/src/stylus/components/_date-picker-header.styl
  packages/vuetify/test/unit/components/VDatePicker/VDatePicker.date.spec.js
  packages/vuetify/test/unit/components/VDatePicker/VDatePicker.month.spec.js
  packages/vuetify/test/unit/components/VDatePicker/VDatePickerHeader.spec.js
  packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePicker.date.spec.js.snap
  packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePicker.month.spec.js.snap
  packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePickerHeader.spec.js.snap
Labels: T: enhancement

#5799 docs: load fonts asynchronously
  packages/vuetifyjs.com/package.json
  packages/vuetifyjs.com/src/App.vue
  packages/vuetifyjs.com/src/entry-client.js
  packages/vuetifyjs.com/src/index.template.html
  yarn.lock
Labels: T: documentation, pending review

#5747 feat: add display breakpoints for printing
  packages/vuetify/src/stylus/settings/_variables.styl
  packages/vuetifyjs.com/src/data/pages/layout/Display.json
  packages/vuetifyjs.com/src/lang/en/layout/Display.json
Labels: T: feature

#5802 fix(VChip): rtl mode
  packages/vuetify/src/stylus/components/_chips.styl
  packages/vuetify/src/stylus/settings/_variables.styl
Labels: T: bug

#5801 fix(VBadge): rtl mode
  packages/vuetify/src/stylus/components/_badges.styl
Labels: T: bug

#5642 fix: add rtl support for toolbar title
  packages/vuetify/src/stylus/components/_toolbar.styl
Labels: T: bug

#5822 fix(VBottomNav): correct inactive colors
  packages/vuetify/src/components/VBottomNav/VBottomNav.ts
  packages/vuetify/src/stylus/components/_bottom-navs.styl
  packages/vuetifyjs.com/src/examples/bottom-navigation/colorAndShift.vue
Labels: T: bug, T: enhancement, pending team review

#5595 fix(VTextField): css rules were applied to checkboxes in v-select menu
  packages/vuetify/src/stylus/components/_inputs.styl
  packages/vuetify/src/stylus/components/_text-fields.styl
Labels: T: bug

#5780 fix(VSelect): fix VSelect behavior when switching to another tab
  packages/vuetify/src/components/VSelect/VSelect.js
Labels: T: bug

#5789 chore: update vue to 2.5.21
  package.json
  packages/api-generator/package.json
  packages/vuetify/package.json
  packages/vuetify/src/components/VAlert/VAlert.ts
  packages/vuetify/src/components/VBadge/VBadge.ts
  packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.ts
  packages/vuetify/src/components/VBtn/VBtn.ts
  packages/vuetify/src/components/VCard/index.ts
  packages/vuetify/src/components/VChip/VChip.ts
  packages/vuetify/src/components/VExpansionPanel/VExpansionPanelContent.ts
  packages/vuetify/src/components/VHover/VHover.ts
  packages/vuetify/src/components/VPagination/VPagination.ts
  packages/vuetify/src/components/VProgressCircular/VProgressCircular.ts
  packages/vuetify/src/components/VRating/VRating.ts
  packages/vuetify/src/components/VSnackbar/VSnackbar.ts
  packages/vuetify/src/components/VTimeline/VTimelineItem.ts
  packages/vuetify/src/components/VTreeview/VTreeview.ts
  packages/vuetify/src/components/VWindow/VWindow.ts
  packages/vuetify/src/components/VWindow/VWindowItem.ts
  packages/vuetify/src/directives/resize.ts
  packages/vuetify/src/directives/touch.ts
  packages/vuetify/src/mixins/bootable.ts
  packages/vuetify/src/mixins/dependent.ts
  packages/vuetify/src/mixins/routable.ts
  packages/vuetify/src/util/ThemeProvider.ts
  packages/vuetify/src/util/helpers.ts
  packages/vuetify/test/unit/components/VMessages/VMessages.spec.js
  packages/vuetify/test/unit/components/VMessages/__snapshots__/VMessages.spec.js.snap
  packages/vuetifyjs.com/build/webpack.server.config.js
  packages/vuetifyjs.com/package.json
  packages/vuetifyjs.com/src/components/core/TableOfContents.vue
  packages/vuetifyjs.com/src/components/helpers/Parameters.vue
  packages/vuetifyjs.com/src/examples/scrolling/usage.vue
  packages/vuetifyjs.com/src/pages/ThemeGeneratorPage.vue
  packages/vuetifyjs.com/src/pages/framework/InternationalizationPage.vue
  packages/vuetifyjs.com/src/pages/motion/TransitionsPage.vue
  packages/vuetifyjs.com/src/pages/style/ColorsPage.vue
  packages/vuetifyjs.com/src/pages/style/ThemePage.vue
  tsconfig.json
  yarn.lock
Labels: task

#5861 refactor(VTimePicker*): convert to typescript
  packages/vuetify/src/components/VTimePicker/VTimePicker.ts
  packages/vuetify/src/components/VTimePicker/VTimePickerClock.ts
  packages/vuetify/src/components/VTimePicker/VTimePickerTitle.ts
  packages/vuetify/src/components/VTimePicker/index.ts
  packages/vuetify/src/mixins/picker-button.ts
  packages/vuetify/src/mixins/picker.ts
Labels: T: enhancement

#5832 feat(VDatePicker): mouse events - click/dblclick
  packages/vuetify/src/components/VDatePicker/VDatePicker.js
  packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.js
  packages/vuetify/src/components/VDatePicker/VDatePickerMonthTable.js
  packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.js
  packages/vuetify/test/unit/components/VDatePicker/VDatePicker.date.spec.js
  packages/vuetify/test/unit/components/VDatePicker/VDatePicker.month.spec.js
Labels: T: feature

#5511 fix(VDialog/VMenu): enable pointer-events for disabled activator
  packages/vuetify/src/components/VDialog/VDialog.js
  packages/vuetify/src/components/VMenu/VMenu.js
  packages/vuetify/src/components/VMenu/mixins/menu-activator.js
  packages/vuetify/src/components/VMenu/mixins/menu-generators.js
  packages/vuetify/src/stylus/components/_dialogs.styl
  packages/vuetify/src/stylus/components/_menus.styl
  packages/vuetify/test/unit/components/VDialog/VDialog.spec.js
  packages/vuetify/test/unit/components/VMenu/VMenu.spec.js
Labels: T: bug

#4910 feat(VIcon): add svg support
  packages/vuetify/src/components/VIcon/VIcon.ts
  packages/vuetify/src/components/Vuetify/mixins/icons.ts
  packages/vuetify/src/stylus/components/_icons.styl
  packages/vuetify/src/util/helpers.ts
  packages/vuetify/test/unit/components/VIcon/VIcon.spec.js
  packages/vuetify/test/unit/components/VIcon/__snapshots__/VIcon.spec.js.snap
  packages/vuetify/types/index.d.ts
  packages/vuetifyjs.com/src/data/pages/framework/Icons.json
  packages/vuetifyjs.com/src/lang/en/framework/Icons.json
  packages/vuetifyjs.com/src/snippets/bash_yarn_install_fa_svg.txt
  packages/vuetifyjs.com/src/snippets/js_component_icons_install.txt
  packages/vuetifyjs.com/src/snippets/js_import_fa_svg.txt
  packages/vuetifyjs.com/src/snippets/stylus_component_icon_styles.txt
Labels: T: feature

#5885 refactor(VExpansionPanel): add `aria-expanded` attribute
  packages/vuetify/src/components/VExpansionPanel/VExpansionPanelContent.ts
  packages/vuetify/test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanel.spec.js.snap
  packages/vuetify/test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanelContent.spec.js.snap
Labels: T: enhancement

#5912 docs: translate framework/PreDefined page to Japanese
  packages/vuetifyjs.com/src/lang/ja/framework/PreDefined.json
Labels: T: documentation

#5643 feat(VParallax): add alt tag by default
  packages/vuetify/src/components/VParallax/VParallax.ts
  packages/vuetify/test/unit/components/VParallax/VParallax.spec.js
  packages/vuetify/test/unit/components/VParallax/__snapshots__/VParallax.spec.js.snap
Labels: T: feature

#5318 feat(detachable): add activator scoped slot
  packages/vuetify/src/components/VDialog/VDialog.js
  packages/vuetify/src/components/VMenu/mixins/menu-activator.js
  packages/vuetify/src/components/VMenu/mixins/menu-generators.js
  packages/vuetify/src/components/VTooltip/VTooltip.js
  packages/vuetify/src/mixins/detachable.js
  packages/vuetify/src/mixins/menuable.js
  packages/vuetify/src/stylus/components/_inputs.styl
  packages/vuetify/src/stylus/components/_menus.styl
  packages/vuetify/src/stylus/components/_tooltips.styl
  packages/vuetify/test/unit/components/VDialog/VDialog.spec.js
  packages/vuetify/test/unit/components/VTooltip/__snapshots__/VTooltip.spec.js.snap
Labels: T: feature

#5666 feat: override breakpoint thresholds
  packages/vuetify/src/components/Vuetify/index.ts
  packages/vuetify/src/components/Vuetify/mixins/breakpoint.ts
  packages/vuetify/test/unit/components/Vuetify/Vuetify.breakpoint.spec.js
  packages/vuetify/types/index.d.ts
  packages/vuetify/types/test/global.ts
  packages/vuetifyjs.com/src/data/pages/framework/Breakpoints.json
  packages/vuetifyjs.com/src/lang/en/framework/Breakpoints.json
  packages/vuetifyjs.com/src/snippets/js_breakpoint_example3.txt
  packages/vuetifyjs.com/src/snippets/ts_breakpoint_example1.txt
Labels: T: feature

#5138 feat(VMenu): disable-keys prop
  packages/vuetify/src/components/VMenu/VMenu.js
  packages/vuetify/src/components/VMenu/mixins/menu-keyable.js
  packages/vuetify/test/unit/components/VMenu/VMenu.spec.js
  packages/vuetifyjs.com/src/lang/en/components/Menus.json
Labels: T: bug, T: feature, needs docs update

#5907 docs(examples) Examples restructuring
  packages/vuetifyjs.com/src/components/ad/Script.vue
  packages/vuetifyjs.com/src/components/doc/Codepen.vue
  packages/vuetifyjs.com/src/components/doc/Example.vue
  packages/vuetifyjs.com/src/components/doc/Examples.vue
  packages/vuetifyjs.com/src/components/doc/Markup.vue
Labels: T: documentation
