Repository vuetifyjs/vuetify, pull requests merged in 2018-06, with the labels that each got.

#4165 fix(VStepper): Use name instead of tag name
  src/components/VStepper/VStepper.js
Labels: T: enhancement

#4261 fix(VAutocomplete): update input value when items change
  src/components/VAutocomplete/VAutocomplete.js
  test/unit/components/VAutocomplete/VAutocomplete.spec.js
Labels: T: bug

#4257 fix(VTextArea): prevent layout flickering with auto-grow
  src/components/VTextField/VTextField.js
  src/components/VTextarea/VTextarea.js
  src/stylus/components/_textarea.styl
  test/unit/components/VTextField/VTextField.spec.js
  test/unit/components/VTextarea/VTextarea.spec.js
  test/unit/components/VTextarea/__snapshots__/VTextarea.spec.js.snap
Labels: P: low, T: enhancement

#4254 feat(inputs): emit events instead of using callback props on icons
  src/components/VInput/VInput.js
  src/components/VSelect/index.js
  src/components/VTextField/VTextField.js
  src/components/VTextField/index.js
  src/util/console.ts
  test/unit/components/VRangeSlider/VRangeSlider.spec.js
  test/unit/components/VSlider/VSlider.spec.js
  test/unit/mixins/detachable.spec.js
  test/unit/util/console.spec.js
Labels: T: enhancement

#3227 fix (v-edit-dialog): restores save/open/close/cancel events
  src/components/VDataTable/VEditDialog.js
Labels: S: on hold, pending team review

#4281 fix(VInput): emitting click:append-outer event
  src/components/VInput/VInput.js
Labels: T: bug

#4286 refactor(inputs): allow long messages, inner icons when enclosed
  src/components/VInput/VInput.js
  src/components/VTextField/VTextField.js
  src/stylus/components/_inputs.styl
  src/stylus/components/_messages.styl
  src/stylus/components/_select.styl
  src/stylus/components/_text-fields.styl
  src/stylus/components/_textarea.styl
  src/stylus/generic/_transitions.styl
  test/unit/components/VSelect/VSelect3.spec.js
Labels: T: enhancement, needs docs update, pending team review

#4315 feat(v-toolbar): fix tab align and distance between button icons
  src/stylus/components/_tabs.styl
  src/stylus/components/_toolbar.styl
Labels: pending team review

#4311 chore(build): update to ts 2.9, enable tslint and happypack
  .eslintrc.js
  .travis.yml
  .tslint.js
  build/webpack.base.config.js
  build/webpack.dev.config.js
  build/webpack.prod.config.js
  package.json
  src/mixins/routable.ts
  src/util/console.ts
  yarn.lock
Labels: T: task, pending team review

#4305 feat(v-toolbar): normalize gutter functionality
  src/stylus/components/_tabs.styl
  src/stylus/components/_toolbar.styl
Labels: pending team review

#4303 fix(VAutocomplete): combobox - show no-data slot if provided
  src/components/VAutocomplete/VAutocomplete.js
  test/unit/components/VAutocomplete/VAutocomplete.spec.js
Labels: pending team review

#4300 refactor: use convertToUnit helper
  src/components/VCard/VCard.js
  src/components/VCard/VCardMedia.js
  src/components/VDialog/VDialog.js
  src/components/VMenu/VMenu.js
  src/components/VNavigationDrawer/VNavigationDrawer.js
  src/components/VProgressLinear/VProgressLinear.js
  src/components/VStepper/VStepperContent.js
  src/components/VTooltip/VTooltip.js
  test/unit/components/VDialog/VDialog.spec.js
  test/unit/components/VDialog/__snapshots__/VDialog.spec.js.snap
Labels: P: low, T: enhancement, pending team review

#4297 fix(VSelectList): use noDataText if item slot is provided
  src/components/VSelect/VSelectList.js
  test/unit/components/VSelect/VSelectList.spec.js
  test/unit/components/VSelect/__snapshots__/VSelectList.spec.js.snap
Labels: T: bug, pending team review

#4293 fix(VTextarea): resize handler position
  src/stylus/components/_textarea.styl
Labels: pending team review

#4292 fix(VInput): prefix width
  src/stylus/components/_text-fields.styl
Labels: pending team review

#4270 fix(VTextField): invalid label position with placeholder
  src/components/VTextField/VTextField.js
Labels: P: low, T: bug, pending team review

#4304 fix(VTimePickerClock): dont switch to minutes if clicked disabled hour
  src/components/VTimePicker/VTimePickerClock.js
  test/unit/components/VTimePicker/VTimePickerClock.spec.js
Labels: T: bug, pending team review

#4003 Too loose selector for fill-height
  src/stylus/components/_grid.styl
Labels: T: bug, pending team review

#4282 feat(detachable): pass through scoped style attribute from parent
  src/components/VDialog/VDialog.js
  src/components/VMenu/mixins/menu-generators.js
  src/components/VTooltip/VTooltip.js
  src/mixins/detachable.js
  test/unit/components/VDialog/__snapshots__/VDialog.spec.js.snap
Labels: T: feature

#4301 fix(translatable): removed normalizedHeight
  src/components/VParallax/VParallax.js
  src/mixins/translatable.js
Labels: P: low, pending team review

#4309 feat: VCombobox
  src/components/VAutocomplete/VAutocomplete.js
  src/components/VCombobox/VCombobox.js
  src/components/VCombobox/index.js
  src/components/VSelect/VSelect.js
  src/components/VSelect/index.js
  src/components/index.js
  test/unit/components/VAutocomplete/VAutocomplete.spec.js
  test/unit/components/VCombobox/VCombobox-multiple.spec.js
  test/unit/components/VCombobox/VCombobox.spec.js
Labels: S: in progress

#4098 fix(VSelect): show input placeholder
  src/components/VSelect/VSelect.js
  src/components/VSlider/VSlider.js
  src/stylus/components/_inputs.styl
  src/stylus/components/_select.styl
  src/stylus/components/_sliders.styl
  test/unit/components/VSlider/__snapshots__/VSlider.spec.js.snap
Labels: T: regression

#4319 feat: Specify custom translation function
  src/components/VDataTable/VDataTable.js
  src/components/Vuetify/mixins/lang.ts
  src/mixins/data-iterable.js
  src/mixins/filterable.js
  test/unit/components/Vuetify/Vuetify.lang.spec.js
  types/index.d.ts
Labels: T: feature, needs docs update

#4328 fix(RTL): next/prev icons and transitions in picker, pagination, carousel, iterable
  src/components/VCarousel/VCarousel.js
  src/components/VCarousel/VCarouselItem.js
  src/components/VDatePicker/VDatePickerHeader.js
  src/components/VDatePicker/mixins/date-picker-table.js
  src/components/VPagination/VPagination.js
  src/mixins/data-iterable.js
  src/stylus/components/_carousel.styl
  src/stylus/components/_date-picker-header.styl
  src/stylus/components/_date-picker-title.styl
  test/unit/components/VCarousel/VCarousel.spec.js
  test/unit/components/VCarousel/__snapshots__/VCarousel.spec.js.snap
  test/unit/components/VDataIterator/VDataIterator.spec.js
  test/unit/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
  test/unit/components/VDatePicker/VDatePickerHeader.spec.js
  test/unit/components/VDatePicker/__snapshots__/VDatePickerHeader.spec.js.snap
  test/unit/components/VPagination/VPagination.spec.js
  test/unit/components/VPagination/__snapshots__/VPagination.spec.js.snap
Labels: T: bug

#4337 fix(VTextField): don't show v-counter if counter is null/undefined
  src/components/VTextField/VTextField.js
  test/unit/components/VTextField/VTextField.spec.js
  test/unit/components/VTextField/__snapshots__/VTextField.spec.js.snap
Labels: T: regression

#4406 fix(v-tabs): update active comparison
  src/components/VTabs/VTabItem.js
  src/components/VTabs/VTabsItems.js
Labels: T: bug

#3777 Don't offset last tab when scrolling
  src/components/VTabs/VTabs.js
Labels: pending team review
