Repository vuetifyjs/vuetify, pull requests merged in 2018-11, with the labels that each got.

#5489 Fix IE11 issue with nested flexbox on scrollable dialog
  packages/vuetify/src/stylus/components/_dialogs.styl
Labels: T: bug

#5497 Added Pagination Props as example
  packages/api-generator/src/map.js
Labels: T: documentation

#5535 fix(VTreeview): arrow direction in rtl
  packages/vuetify/src/stylus/components/_treeview.styl
Labels: T: bug

#5527 Fix: v-menu position problem with horizontal scrolling
  packages/vuetify/src/mixins/menuable.js
Labels: T: bug

#5579 fix(VSelect): stop keydown.esc propagation
  packages/vuetify/src/components/VSelect/VSelect.js
Labels: T: bug

#5502 feat(VDatePicker): month events
  packages/vuetify/src/components/VDatePicker/VDatePicker.js
  packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.js
  packages/vuetify/src/components/VDatePicker/VDatePickerMonthTable.js
  packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.js
  packages/vuetify/src/stylus/components/_date-picker-table.styl
  packages/vuetify/test/unit/components/VDatePicker/VDatePickerMonthTable.spec.js
  packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePickerDateTable.spec.js.snap
  packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePickerMonthTable.spec.js.snap
  packages/vuetifyjs.com/src/data/components.json
  packages/vuetifyjs.com/src/examples/date-pickers/monthEvents.vue
  packages/vuetifyjs.com/src/lang/en/components/DatePickers.json
Labels: T: feature

#5512 feat(VDatePicker): multiple event indicators
  packages/vuetify/src/components/VDatePicker/VDatePicker.js
  packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.js
  packages/vuetify/src/stylus/components/_date-picker-table.styl
  packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePickerDateTable.spec.js.snap
  packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePickerMonthTable.spec.js.snap
  packages/vuetifyjs.com/src/examples/date-pickers/dateEvents.vue
  packages/vuetifyjs.com/src/examples/date-pickers/monthEvents.vue
  packages/vuetifyjs.com/src/lang/en/components/DatePickers.json
Labels: T: feature

#5590 fix(WindowItem): calculate height on leave
  packages/vuetify/src/components/VWindow/VWindowItem.ts
  packages/vuetify/test/unit/components/VWindow/VWindowItem.spec.js
Labels: T: bug, pending team review

#5647 refactor(Paper): rename to Sheet
  packages/vuetify/src/components/VCard/VCard.ts
  packages/vuetify/src/components/VPaper/index.ts
  packages/vuetify/src/components/VSheet/VSheet.ts
  packages/vuetify/src/components/VSheet/index.ts
  packages/vuetify/src/components/index.ts
  packages/vuetify/src/stylus/components/_sheet.styl
  packages/vuetify/src/stylus/settings/_variables.styl
  packages/vuetify/test/integration/__snapshots__/importA-la-carte.spec.js.snap
  packages/vuetify/test/integration/__snapshots__/importFull.spec.js.snap
  packages/vuetify/test/integration/__snapshots__/importLib.spec.js.snap
  packages/vuetify/test/integration/importA-la-carte.spec.js
  packages/vuetify/test/integration/importLib.spec.js
  packages/vuetify/test/unit/components/VCard/__snapshots__/VCard.spec.js.snap
  packages/vuetify/test/unit/components/VMenu/__snapshots__/VMenu.spec.js.snap
  packages/vuetify/test/unit/components/VPaper/__snapshots__/VPaper.spec.js.snap
  packages/vuetify/test/unit/components/VSheet/VSheet.spec.js
  packages/vuetify/test/unit/components/VSheet/__snapshots__/VSheet.spec.js.snap
Labels: T: enhancement

#5545 Updated wrong link in the documentation's Colors page
  packages/vuetifyjs.com/src/lang/en/components/Menus.json
  packages/vuetifyjs.com/src/lang/en/components/Selects.json
  packages/vuetifyjs.com/src/lang/en/style/Colors.json
  packages/vuetifyjs.com/src/lang/en/style/Theme.json
  packages/vuetifyjs.com/src/lang/es-MX/components/Menus.json
  packages/vuetifyjs.com/src/lang/es-MX/style/Colors.json
  packages/vuetifyjs.com/src/lang/es-MX/style/Theme.json
  packages/vuetifyjs.com/src/lang/ko/components/Menus.json
  packages/vuetifyjs.com/src/lang/ko/style/Colors.json
  packages/vuetifyjs.com/src/lang/ko/style/Theme.json
  packages/vuetifyjs.com/src/lang/ru/components/Menus.json
  packages/vuetifyjs.com/src/lang/ru/style/Colors.json
  packages/vuetifyjs.com/src/lang/ru/style/Theme.json
  packages/vuetifyjs.com/src/lang/zhHans/components/Menus.json
  packages/vuetifyjs.com/src/lang/zhHans/style/Colors.json
  packages/vuetifyjs.com/src/lang/zhHans/style/Theme.json
  packages/vuetifyjs.com/src/releases/0.15/pages/MenusView.vue
  packages/vuetifyjs.com/src/releases/0.16/pages/MenusView.vue
  packages/vuetifyjs.com/src/releases/0.17/pages/MenusView.vue
Labels: T: documentation

#5612 Improve responsive behaviour
  packages/vuetifyjs.com/src/examples/cards/horizontal.vue
Labels: T: documentation

#5710 fix(selection-controls): use ripple even when disabled
  packages/vuetify/src/components/VCheckbox/VCheckbox.js
  packages/vuetify/src/components/VRadioGroup/VRadio.js
  packages/vuetify/src/components/VSwitch/VSwitch.js
  packages/vuetify/test/unit/components/VCheckbox/VCheckbox.spec.js
Labels: T: bug

#5448 fix(VMenu): auto positioning with dense prop
  packages/vuetify/src/components/VMenu/VMenu.js
  packages/vuetify/src/components/VMenu/mixins/menu-position.js
  packages/vuetify/src/mixins/menuable.js
  packages/vuetify/src/stylus/components/_menus.styl
Labels: T: bug

#5674 Added seconds support to the VTimePicker
  packages/vuetify/src/components/VTimePicker/VTimePicker.js
  packages/vuetify/src/components/VTimePicker/VTimePickerTitle.js
  packages/vuetify/test/unit/components/VTimePicker/VTimePicker.spec.js
  packages/vuetify/test/unit/components/VTimePicker/VTimePickerTitle.spec.js
  packages/vuetify/test/unit/components/VTimePicker/__snapshots__/VTimePicker.spec.js.snap
  packages/vuetify/test/unit/components/VTimePicker/__snapshots__/VTimePickerTitle.spec.js.snap
Labels: T: feature

#5671 feat: aria roles for VList and VListTile
  packages/vuetify/src/components/VList/VList.js
  packages/vuetify/src/components/VList/VListTile.js
  packages/vuetify/test/unit/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
  packages/vuetify/test/unit/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
  packages/vuetify/test/unit/components/VList/__snapshots__/VList.spec.js.snap
  packages/vuetify/test/unit/components/VList/__snapshots__/VListGroup.spec.js.snap
  packages/vuetify/test/unit/components/VList/__snapshots__/VListTile.spec.js.snap
  packages/vuetify/test/unit/components/VSelect/__snapshots__/VSelect.spec.js.snap
  packages/vuetify/test/unit/components/VSelect/__snapshots__/VSelectList.spec.js.snap
Labels: T: feature

#4923 feat: add sparkline component
  packages/api-generator/src/map.js
  packages/vuetify/src/components/VSparkline/Bar.ts
  packages/vuetify/src/components/VSparkline/Trend.ts
  packages/vuetify/src/components/VSparkline/VSparkline.ts
  packages/vuetify/src/components/VSparkline/components/gradient.ts
  packages/vuetify/src/components/VSparkline/components/path.ts
  packages/vuetify/src/components/VSparkline/components/rect.ts
  packages/vuetify/src/components/VSparkline/components/text.ts
  packages/vuetify/src/components/VSparkline/helpers/core.ts
  packages/vuetify/src/components/VSparkline/helpers/math.ts
  packages/vuetify/src/components/VSparkline/helpers/path.ts
  packages/vuetify/src/components/VSparkline/index.ts
  packages/vuetify/src/components/VSparkline/mixins/props.ts
  packages/vuetify/src/components/index.ts
  packages/vuetify/test/integration/__snapshots__/importA-la-carte.spec.js.snap
  packages/vuetify/test/integration/__snapshots__/importFull.spec.js.snap
  packages/vuetify/test/integration/__snapshots__/importLib.spec.js.snap
  packages/vuetify/test/integration/importA-la-carte.spec.js
  packages/vuetify/test/integration/importLib.spec.js
  packages/vuetifyjs.com/src/data/drawerItems.json
  packages/vuetifyjs.com/src/data/pages/components/Sparklines.json
  packages/vuetifyjs.com/src/examples/sparklines/playground.vue
  packages/vuetifyjs.com/src/lang/en/components/Sparklines.json
  packages/vuetifyjs.com/src/lang/en/meta.json
  packages/vuetifyjs.com/src/lang/en/vuetify/AppDrawer.json
Labels: T: feature
