Repository vuetifyjs/vuetify, pull requests merged in 2018-04, with the labels that each got.

#3660 fix (v-tabs): disabled tab is not disabled
  src/stylus/components/_tabs.styl
Labels: in progress

#3379 feat: allow theme to be disabled entirely
  index.d.ts
  src/components/VApp/mixins/app-theme.js
  src/components/Vuetify/mixins/theme.js
Labels: enhancement, pending merge

#3724 refactor (VAlert): Add v- prefix to alert classes
  src/components/VAlert/VAlert.js
  src/stylus/components/_alerts.styl
  test/unit/components/VAlert/VAlert.spec.js
  test/unit/components/VAlert/__snapshots__/VAlert.spec.js.snap
Labels: enhancement

#3728 fix(v-tabs): recalculate overflow on tabs change
  src/components/VTabs/VTabs.js
  test/unit/components/VTabs/VTabs.spec.js
Labels: bug

#3843 fix(v-pagination): fixed responsive pagination
  src/components/VNavigationDrawer/VNavigationDrawer.js
  src/components/VPagination/VPagination.js
  src/stylus/components/_grid.styl
  test/unit/components/VPagination/VPagination.spec.js
Labels: bug

#3848 fix: zero-width activator when edit-dialog input is empty
  src/stylus/components/_small-dialog.styl
Labels: bug

#3854 fix(VBreadcrumbs): only create dividers for v-breadcrumbs-item
  src/components/VBreadcrumbs/VBreadcrumbs.js
  test/unit/components/VBreadcrumbs/VBreadcrumbs.spec.js
  test/unit/components/VBreadcrumbs/__snapshots__/VBreadcrumbs.spec.js.snap
Labels: bug

#3781 fix(v-tabs): reset scrollOffset if not overflowing
  src/components/VTabs/VTabs.js
  test/unit/components/VTabs/VTabs.spec.js
Labels: bug

#3785 feat(types): add icons and Vuetify plugin to type definition
  index.d.ts
Labels: enhancement

#3819 Fix #3727
  src/stylus/components/_snackbars.styl
Labels: in progress
