Repository vuetifyjs/vuetify, pull requests merged in 2018-07, with the labels that each got.

#4430 fix: prevent selection controls' labels from growing
  src/stylus/components/_selection-controls.styl
Labels: T: bug

#4368 refactor(breakpoint): update to ts, remove from v-app
  src/components/VApp/VApp.js
  src/components/Vuetify/index.ts
  src/components/Vuetify/mixins/breakpoint.ts
  test/unit/components/VToolbar/VToolbar.spec.js
  test/unit/components/VToolbar/__snapshots__/VToolbar.spec.js.snap
  test/unit/components/Vuetify/Vuetify.breakpoint.spec.js
Labels: T: enhancement, pending review

#4532 refactor(theme): remove from v-app, convert to TS
  src/components/VApp/VApp.js
  src/components/Vuetify/index.ts
  src/components/Vuetify/mixins/theme.ts
  src/components/Vuetify/services/ThemeService.ts
  src/globals.d.ts
  src/util/theme.ts
  test/unit/components/VApp/VApp.spec.js
  test/unit/components/VApp/__snapshots__/VApp.spec.js.snap
  test/unit/components/Vuetify/Vuetify.theme.spec.js
  test/unit/components/Vuetify/__snapshots__/Vuetify.theme.spec.js.snap
  types/index.d.ts
Labels: T: enhancement

#4339 fix(VProgressCircular): added vertical alignment
  src/stylus/components/_progress-circular.styl
Labels: S: pending merge

#4441 fix(VSelect): override v-text-field's blur method
  src/components/VSelect/VSelect.js
Labels: T: bug

#4531 fix(VChip): styles for disabled chips
  src/components/VChip/VChip.js
  src/stylus/components/_chips.styl
  test/unit/components/VChip/VChip.spec.js
Labels: T: enhancement, T: regression

#4515 fix: v-tabs should now update v-model if swiping on v-tab
  src/components/VTabs/VTabs.js
  src/components/VTabs/mixins/tabs-computed.js
  test/unit/components/VTabs/VTabs.spec.js
Labels: T: bug

#4435 feat: add ukrainian locale
  src/locale/uk.js
Labels: S: pending merge

#4437 feat(locale): polish
  src/locale/pl.js
Labels: S: pending merge

#4425 feat: add russian locale
  src/locale/ru.js
Labels: S: pending merge, semver: minor

#4538 refactor: convert v-avatar to typescript
  src/components/VAvatar/VAvatar.ts
  src/components/VAvatar/index.ts
Labels: T: task

#4551 chore(typescript): application.js, applicationable.js converted to typescript
  src/components/Vuetify/mixins/application.js
  src/components/Vuetify/mixins/application.ts
  src/mixins/applicationable.ts
  types/index.d.ts
Labels: T: task

#4457 fix(VInput): themeable label, icon, counter, messages
  src/components/VCheckbox/VCheckbox.js
  src/components/VCounter/VCounter.js
  src/components/VInput/VInput.js
  src/components/VLabel/VLabel.js
  src/components/VMessages/VMessages.js
  src/components/VRadioGroup/VRadio.js
  src/components/VSwitch/VSwitch.js
  src/components/VTextField/VTextField.js
  test/unit/components/VCheckbox/VCheckbox.spec.js
  test/unit/components/VCheckbox/__snapshots__/VCheckbox.spec.js.snap
  test/unit/components/VInput/VInput.spec.js
  test/unit/components/VInput/__snapshots__/VInput.spec.js.snap
  test/unit/components/VRadioGroup/VRadio.spec.js
  test/unit/components/VRadioGroup/__snapshots__/VRadio.spec.js.snap
  test/unit/components/VTextField/VTextField.spec.js
  test/unit/components/VTextField/__snapshots__/VTextField.spec.js.snap
Labels: T: bug, T: regression

#4560 refactor(v-bottom-nav): convert to typescript
  src/components/VBottomNav/VBottomNav.ts
  src/components/VBottomNav/index.ts
  src/mixins/applicationable.ts
Labels: T: task

#4545 4265 update tests to use new icon events
  src/components/VInput/VInput.js
  src/util/console.ts
  test/unit/components/VInput/VInput.spec.js
  test/unit/components/VSelect/VSelect2.spec.js
  test/unit/components/VTextField/VTextField.spec.js
Labels: S: in progress, T: enhancement

#4565 refactor(VCard): convert to typescript
  src/components/VCard/VCard.ts
  src/components/VCard/VCardMedia.ts
  src/components/VCard/VCardTitle.ts
  src/components/VCard/index.js
  src/components/VCard/index.ts
Labels: T: task

#4598 fix(types): prevent type leak in Toggleable, add $el to VBtn
  src/components/VBadge/VBadge.ts
  src/components/VBtn/VBtn.ts
  src/components/VBtnToggle/VBtnToggle.ts
  src/mixins/bootable.ts
  src/mixins/button-group.ts
  src/mixins/registrable.ts
  src/mixins/toggleable.ts
  src/util/mixins.ts
Labels: T: task

#4593 fix(v-form): restore ability to work with inputs through $refs
  src/components/VForm/VForm.js
  test/unit/components/VForm/VForm.spec.js
Labels: T: regression

#4664 Add removed style to shift text on expansion toolbar
  src/stylus/components/_toolbar.styl
Labels: T: bug

#4638 Fix deepEqual helper - Enable Date values for v-radio
  src/util/helpers.ts
  test/unit/util/helpers.spec.js
Labels: T: bug

#4472 feat: create v-img and v-responsive components
  build/webpack.dev.config.js
  dev/angryman.png
  package.json
  src/components/VCard/VCardMedia.ts
  src/components/VCarousel/VCarouselItem.js
  src/components/VImg/VImg.ts
  src/components/VImg/index.ts
  src/components/VJumbotron/VJumbotron.js
  src/components/VResponsive/VResponsive.ts
  src/components/VResponsive/index.ts
  src/components/index.js
  src/globals.d.ts
  src/stylus/components/_cards.styl
  src/stylus/components/_carousel.styl
  src/stylus/components/_images.styl
  src/stylus/components/_responsive.styl
  test/unit/components/VCard/VCardMedia.spec.js
  test/unit/components/VCard/__snapshots__/VCardMedia.spec.js.snap
  test/unit/components/VCarousel/__snapshots__/VCarousel.spec.js.snap
  test/unit/components/VCarousel/__snapshots__/VCarouselItem.spec.js.snap
  test/unit/components/VImg/VImg.spec.js
  test/unit/components/VImg/__snapshots__/VImg.spec.js.snap
  test/unit/components/VResponsive/VResponsive.spec.js
  test/unit/components/VResponsive/__snapshots__/VResponsive.spec.js.snap
  yarn.lock
Labels: semver: minor

#3863 feature: v-rating component
  src/components/VIcon/VIcon.ts
  src/components/VRating/VRating.ts
  src/components/VRating/index.ts
  src/components/Vuetify/mixins/icons.js
  src/components/index.js
  src/mixins/rippleable.ts
  src/mixins/sizeable.ts
  src/stylus/components/_rating.styl
  src/stylus/settings/_variables.styl
  src/util/helpers.ts
  test/unit/components/VRating/VRating.spec.js
  test/unit/components/VRating/__snapshots__/VRating.spec.js.snap
  types/index.d.ts
Labels: S: in progress

#2965 feature (v-date-picker) add multiple date selection
  src/components/VDatePicker/VDatePicker.js
  src/components/VDatePicker/mixins/date-picker-table.js
  test/unit/components/VDatePicker/VDatePicker.date.spec.js
  test/unit/components/VDatePicker/VDatePickerDateTable.spec.js
  test/unit/components/VDatePicker/VDatePickerMonthTable.spec.js
  test/unit/components/VDatePicker/__snapshots__/VDatePickerDateTable.spec.js.snap
  test/unit/components/VDatePicker/__snapshots__/VDatePickerMonthTable.spec.js.snap
Labels: needs docs update, semver: minor

#4179 feat(v-select): additional slots before/after options list
  src/components/VSelect/VSelect.js
  src/components/VSelect/VSelectList.js
  test/unit/components/VSelect/VSelect.spec.js
  test/unit/components/VSelect/__snapshots__/VSelect.spec.js.snap
Labels: T: feature, needs docs update, semver: minor

#4747 feat(locale): chinese
  src/locale/zh-Hans.js
  src/locale/zh-Hant.js
Labels: T: feature
