Repository vuetifyjs/vuetify, pull requests merged in 2018-08, with the labels that each got.

#4841 feat(v-hover): create new component
  src/components/VHover/VHover.ts
  src/components/VHover/index.ts
  src/components/index.js
  src/globals.d.ts
  src/stylus/components/_cards.styl
  src/stylus/generic/_transitions.styl
  src/util/helpers.ts
  test/integration/__snapshots__/importA-la-carte.spec.js.snap
  test/integration/__snapshots__/importFull.spec.js.snap
  test/integration/importA-la-carte.spec.js
  test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanel.spec.js.snap
  test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanelContent.spec.js.snap
  test/unit/components/VHover/VHover.spec.js
  types/index.d.ts
Labels: T: enhancement

#4342 feat(colorable): hex colors
  src/components/VAlert/VAlert.ts
  src/components/VAvatar/VAvatar.ts
  src/components/VBadge/VBadge.ts
  src/components/VBottomNav/VBottomNav.ts
  src/components/VBreadcrumbs/VBreadcrumbsItem.js
  src/components/VBtn/VBtn.ts
  src/components/VCard/VCard.ts
  src/components/VCheckbox/VCheckbox.js
  src/components/VChip/VChip.ts
  src/components/VDatePicker/VDatePicker.js
  src/components/VDatePicker/VDatePickerDateTable.js
  src/components/VDatePicker/VDatePickerHeader.js
  src/components/VDatePicker/VDatePickerYears.js
  src/components/VDatePicker/mixins/date-picker-table.js
  src/components/VFooter/VFooter.js
  src/components/VIcon/VIcon.ts
  src/components/VInput/VInput.js
  src/components/VJumbotron/VJumbotron.js
  src/components/VLabel/VLabel.js
  src/components/VList/VListTile.js
  src/components/VMessages/VMessages.js
  src/components/VPagination/VPagination.js
  src/components/VPicker/VPicker.js
  src/components/VProgressCircular/VProgressCircular.ts
  src/components/VProgressLinear/VProgressLinear.ts
  src/components/VRadioGroup/VRadio.js
  src/components/VRating/VRating.ts
  src/components/VSelect/VSelect.js
  src/components/VSelect/VSelectList.js
  src/components/VSlider/VSlider.js
  src/components/VSnackbar/VSnackbar.ts
  src/components/VSwitch/VSwitch.js
  src/components/VSystemBar/VSystemBar.js
  src/components/VTabs/VTab.js
  src/components/VTabs/VTabsSlider.js
  src/components/VTabs/mixins/tabs-generators.js
  src/components/VTimePicker/VTimePickerClock.js
  src/components/VToolbar/VToolbar.js
  src/components/VTooltip/VTooltip.js
  src/mixins/colorable.ts
  src/mixins/routable.ts
  src/mixins/selectable.js
  test/unit/components/VAlert/VAlert.spec.js
  test/unit/components/VIcon/VIcon.spec.js
  test/unit/components/VInput/__snapshots__/VInput.spec.js.snap
  test/unit/components/VRadioGroup/VRadio.spec.js
  test/unit/components/VRadioGroup/__snapshots__/VRadioGroup.spec.js.snap
  test/unit/components/VTextarea/__snapshots__/VTextarea.spec.js.snap
  test/unit/mixins/colorable.spec.js
Labels: T: feature, needs docs update, semver: minor

#4795 feat(VSelect): add menu-props prop, deprecate everything else
  src/components/VAutocomplete/VAutocomplete.js
  src/components/VMenu/VMenu.js
  src/components/VOverflowBtn/VOverflowBtn.js
  src/components/VSelect/VSelect.js
  src/mixins/data-iterable.js
  src/mixins/menuable.js
  src/util/helpers.ts
  test/unit/components/VAutocomplete/VAutocomplete.spec.js
  test/unit/components/VCombobox/VCombobox.spec.js
  test/unit/components/VSelect/VSelect.spec.js
  test/unit/components/VSelect/VSelect3.spec.js
Labels: T: enhancement, T: feature

#4774 feat(theme): css vars
  src/components/VApp/mixins/app-theme.js
  src/components/Vuetify/mixins/options.js
  src/stylus/generic/_colors.styl
  src/util/theme.ts
  test/unit/components/VApp/VApp.spec.js
  test/unit/components/VApp/__snapshots__/VApp.spec.js.snap
  types/index.d.ts
Labels: T: feature

#4821 feat(VRating) null rating if current value is selected
  src/components/VRating/VRating.ts
  test/unit/components/VRating/VRating.spec.js
Labels: T: feature

#4890 feat(VTimePicker): readonly prop
  src/components/VDatePicker/VDatePickerTitle.js
  src/components/VTimePicker/VTimePicker.js
  src/components/VTimePicker/VTimePickerClock.js
  src/components/VTimePicker/VTimePickerTitle.js
  src/mixins/picker-button.js
  src/stylus/components/_pickers.styl
  test/unit/components/VDatePicker/__snapshots__/VDatePicker.date.spec.js.snap
  test/unit/components/VDatePicker/__snapshots__/VDatePicker.month.spec.js.snap
  test/unit/components/VDatePicker/__snapshots__/VDatePickerTitle.spec.js.snap
  test/unit/components/VTimePicker/VTimePickerClock.spec.js
  test/unit/components/VTimePicker/VTimePickerTitle.spec.js
  test/unit/components/VTimePicker/__snapshots__/VTimePicker.spec.js.snap
  test/unit/components/VTimePicker/__snapshots__/VTimePickerTitle.spec.js.snap
Labels: T: feature

#4876 refactor(locale): changed to typescript
  src/locale/de.ts
  src/locale/en.ts
  src/locale/fr.ts
  src/locale/gr.ts
  src/locale/pl.ts
  src/locale/pt.ts
  src/locale/ru.ts
  src/locale/uk.ts
  src/locale/zh-Hans.ts
  src/locale/zh-Hant.ts
Labels: T: task

#4874 refactor(VPagination): typescript
  src/components/VPagination/VPagination.ts
  src/components/VPagination/index.ts
  src/directives/resize.ts
  test/unit/components/VPagination/VPagination.spec.js
Labels: T: task

#4907 fix: icon button's height in toolbar items
  src/stylus/components/_toolbar.styl
Labels: T: bug

#4903 feat(locale): farsi
  src/locale/fa.ts
Labels: T: feature

#4902 fix(v-text-field/v-select): remove explicit height
  src/stylus/components/_select.styl
  src/stylus/components/_text-fields.styl
Labels: T: bug

#4928 refactor(VSelect): remove menu activator slot
  src/components/VMenu/VMenu.js
  src/components/VMenu/mixins/menu-keyable.js
  src/components/VSelect/VSelect.js
  src/stylus/components/_autocompletes.styl
  src/stylus/components/_overflow-buttons.styl
  src/stylus/components/_select.styl
  test/unit/components/VCombobox/VCombobox-multiple.spec.js
  test/unit/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
  test/unit/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
  test/unit/components/VOverflowBtn/__snapshots__/VOverflowBtn.spec.js.snap
  test/unit/components/VSelect/VSelect2.spec.js
  test/unit/components/VSelect/__snapshots__/VSelect.spec.js.snap
  test/unit/components/VSelect/__snapshots__/VSelect2.spec.js.snap
Labels: T: bug, T: enhancement

#4933 md2/v-expansion-panel updates
  src/components/VExpansionPanel/VExpansionPanel.ts
  src/components/VExpansionPanel/VExpansionPanelContent.ts
  src/components/transitions/expand-transition.js
  src/stylus/components/_expansion-panel.styl
  src/stylus/components/_lists.styl
  test/unit/components/VExpansionPanel/VExpansionPanel.spec.js
  test/unit/components/VExpansionPanel/VExpansionPanelContent.spec.js
  test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanel.spec.js.snap
  test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanelContent.spec.js.snap
Labels: T: enhancement
