Repository vuetifyjs/vuetify, pull requests merged in 2018-05, with the labels that each got.

#3965 Fix: Prevent stylus variable vs. animation name collision ("query")
  src/stylus/components/_grid.styl
  src/stylus/generic/_bootstrap.styl
  src/stylus/trumps/_display.styl
  src/stylus/trumps/_spacing.styl
  src/stylus/trumps/_text.styl
Labels: pending merge

#3992 feat: create v-overflow-btn
  src/components/VOverflowBtn/VOverflowBtn.js
  src/components/VOverflowBtn/index.js
  src/components/VSelect/VSelect.js
  src/components/VSelect/index.js
  src/components/index.js
  src/stylus/components/_overflow-buttons.styl
  src/stylus/settings/_theme.styl
  test/unit/components/VAutocomplete/VAutocomplete-segmented.old.js
  test/unit/components/VOverflowBtn/VOverflowBtn.spec.js
  test/unit/components/VOverflowBtn/__snapshots__/VOverflowBtn.spec.js.snap
Labels: in progress

#3920 fix(v-data-table): incorrect colspan when not using headers prop
  src/components/VDataTable/VDataTable.js
  test/unit/components/VDataTable/VDataTable.spec.js
Labels: needs docs update

#3969 feat(VExpansionPanel): add disabled and readonly props
  src/components/VExpansionPanel/VExpansionPanel.js
  src/components/VExpansionPanel/VExpansionPanelContent.js
  src/stylus/components/_expansion-panel.styl
  test/unit/components/VExpansionPanel/VExpansionPanel.spec.js
  test/unit/components/VExpansionPanel/VExpansionPanelContent.spec.js
Labels: T: enhancement, needs docs update

#3922 feat(v-data-iterator): add header slot
  src/components/VDataIterator/VDataIterator.js
  test/unit/components/VDataIterator/VDataIterator.spec.js
Labels: needs docs update

#4005 perf(VSelect): cache list VNode
  src/components/VAutocomplete/VAutocomplete.js
  src/components/VSelect/VSelect.js
Labels: T: enhancement

#4025 fix(v-select): add back fake virtualization
  src/components/VAutocomplete/VAutocomplete.js
  src/components/VSelect/VSelect.js
  test/unit/components/VSelect/VSelect3.spec.js
Labels: P: critical, T: enhancement

#4026 Fixed one more case of hard-coded icon (clear, if clearable)
  src/components/VTextField/VTextField.js
Labels: T: bug

#4029 fix(VInput): allow input to fill width when in a flex container
  src/stylus/components/_inputs.styl
Labels: T: regression

#4030 fix(VTextField): add back focus and blur methods
  src/components/VTextField/VTextField.js
  test/unit/components/VTextField/VTextField.spec.js
Labels: T: regression

#4010 fix(VTextField): fix error state with external validation
  src/components/VForm/VForm.js
  src/components/VInput/VInput.js
  src/mixins/validatable.js
  src/stylus/components/_inputs.styl
  src/stylus/components/_text-fields.styl
  test/unit/components/VCheckbox/__snapshots__/VCheckbox.spec.js.snap
  test/unit/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
  test/unit/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
  test/unit/components/VForm/VForm.spec.js
  test/unit/components/VInput/VInput.spec.js
  test/unit/components/VInput/__snapshots__/VInput.spec.js.snap
  test/unit/components/VOverflowBtn/__snapshots__/VOverflowBtn.spec.js.snap
  test/unit/components/VRadioGroup/VRadioGroup.spec.js
  test/unit/components/VRadioGroup/__snapshots__/VRadioGroup.spec.js.snap
  test/unit/components/VSelect/__snapshots__/VSelect.spec.js.snap
  test/unit/components/VSelect/__snapshots__/VSelect2.spec.js.snap
  test/unit/components/VSlider/__snapshots__/VSlider.spec.js.snap
  test/unit/components/VTextField/VTextField.spec.js
  test/unit/components/VTextField/__snapshots__/VTextField.spec.js.snap
Labels: T: regression

#4051 feature(lang): added lang option to vuetify
  .eslintrc.js
  src/components/VDataTable/VDataTable.js
  src/components/VSelect/VSelect.js
  src/components/Vuetify/index.js
  src/components/Vuetify/mixins/lang.ts
  src/locale/en.js
  src/mixins/data-iterable.js
  src/mixins/filterable.js
  src/util/helpers.d.ts
  src/util/helpers.js
  test/unit/components/Vuetify/Vuetify.lang.spec.js
  types/index.d.ts
  types/lang.d.ts
Labels: T: feature

#4124 fix(VSlider): allow step to be set to 0
  src/components/VSlider/VSlider.js
  test/unit/components/VSlider/VSlider.spec.js
Labels: T: regression

#4170 fix(v-dialog/selection-controls): style updates
  src/stylus/components/_cards.styl
  src/stylus/components/_dialogs.styl
  src/stylus/components/_radio-group.styl
  src/stylus/components/_radios.styl
  src/stylus/components/_selection-controls.styl
Labels: T: bug
