Repository vuetifyjs/vuetify, pull requests merged in 2019-03, with the labels that each got.

#6653 feat(typography): update typography font weight to md2
  packages/vuetify/src/styles/base/_variables.scss
Labels: md2

#6659 refactor(trumps): convert to SASS
  packages/vuetify/src/styles/styles.sass
  packages/vuetify/src/styles/trumps/_display.sass
  packages/vuetify/src/styles/trumps/_helpers.sass
  packages/vuetify/src/styles/trumps/_index.sass
  packages/vuetify/src/styles/trumps/_spacing.sass
  packages/vuetify/src/styles/trumps/_text.sass
  packages/vuetify/src/styles/trumps/_transition.sass
  packages/vuetify/src/stylus/app.styl
  packages/vuetify/src/stylus/trumps/_spacing.styl
  packages/vuetify/src/stylus/trumps/_transition.styl
Labels: T: enhancement

#6658 docs: add md spec version and links
  packages/docs/src/components/core/Page.vue
  packages/docs/src/components/core/SpecBtn.vue
  packages/docs/src/data/pages/components/Autocompletes.json
  packages/docs/src/data/pages/components/Banners.json
  packages/docs/src/data/pages/components/BottomNavigation.json
  packages/docs/src/data/pages/components/BottomSheets.json
  packages/docs/src/data/pages/components/ButtonGroups.json
  packages/docs/src/data/pages/components/Buttons.json
  packages/docs/src/data/pages/components/Cards.json
  packages/docs/src/data/pages/components/ChipGroups.json
  packages/docs/src/data/pages/components/Chips.json
  packages/docs/src/data/pages/components/DataTables.json
  packages/docs/src/data/pages/components/DatePickers.json
  packages/docs/src/data/pages/components/Dialogs.json
  packages/docs/src/data/pages/components/Dividers.json
  packages/docs/src/data/pages/components/ExpansionPanels.json
  packages/docs/src/data/pages/components/FloatingActionButtons.json
  packages/docs/src/data/pages/components/Icons.json
  packages/docs/src/data/pages/components/Images.json
  packages/docs/src/data/pages/components/Lists.json
  packages/docs/src/data/pages/components/Menus.json
  packages/docs/src/data/pages/components/NavigationDrawers.json
  packages/docs/src/data/pages/components/OverflowBtns.json
  packages/docs/src/data/pages/components/Progress.json
  packages/docs/src/data/pages/components/SelectionControls.json
  packages/docs/src/data/pages/components/Sliders.json
  packages/docs/src/data/pages/components/Snackbars.json
  packages/docs/src/data/pages/components/Steppers.json
  packages/docs/src/data/pages/components/Subheaders.json
  packages/docs/src/data/pages/components/Tabs.json
  packages/docs/src/data/pages/components/TextFields.json
  packages/docs/src/data/pages/components/Textarea.json
  packages/docs/src/data/pages/components/TimePickers.json
  packages/docs/src/data/pages/components/Toolbars.json
  packages/docs/src/data/pages/components/Tooltips.json
  packages/docs/src/data/pages/framework/AspectRatios.json
  packages/docs/src/data/pages/framework/Breakpoints.json
  packages/docs/src/data/pages/framework/Colors.json
  packages/docs/src/data/pages/framework/Elevation.json
  packages/docs/src/data/pages/framework/Grid.json
  packages/docs/src/data/pages/framework/GridLists.json
  packages/docs/src/data/pages/framework/Icons.json
  packages/docs/src/data/pages/framework/Internationalization.json
  packages/docs/src/data/pages/framework/Spacing.json
  packages/docs/src/data/pages/framework/Transitions.json
  packages/docs/src/data/pages/framework/Typography.json
Labels: T: documentation

#6660 Test/directives update tests
  packages/vuetify/src/directives/__tests__/click-outside.spec.ts
  packages/vuetify/src/directives/__tests__/resize.spec.ts
  packages/vuetify/src/directives/__tests__/ripple.spec.ts
  packages/vuetify/src/directives/__tests__/scroll.spec.ts
  packages/vuetify/src/directives/__tests__/touch.spec.js
  packages/vuetify/test/unit/directives/resize.spec.js
  packages/vuetify/test/unit/directives/scroll.spec.js
Labels: T: enhancement, testing

#6424 feat(VSlider): updated to TS and added vertical sliders
  packages/api-generator/src/map.js
  packages/docs/src/components/doc/Parameters.vue
  packages/docs/src/data/new.json
  packages/docs/src/data/pages/components/Sliders.json
  packages/docs/src/examples/sliders/customThumb.vue
  packages/docs/src/examples/sliders/editableNumericValue.vue
  packages/docs/src/examples/sliders/metronome.vue
  packages/docs/src/examples/sliders/minMax.vue
  packages/docs/src/examples/sliders/range.vue
  packages/docs/src/examples/sliders/thumb.vue
  packages/docs/src/examples/sliders/ticks.vue
  packages/docs/src/examples/sliders/usage.vue
  packages/docs/src/examples/sliders/vertical.vue
  packages/docs/src/lang/en/components/Sliders.json
  packages/kitchen/src/pan/Sliders.vue
  packages/vuetify/src/components/VRangeSlider/VRangeSlider.js
  packages/vuetify/src/components/VRangeSlider/VRangeSlider.ts
  packages/vuetify/src/components/VRangeSlider/index.ts
  packages/vuetify/src/components/VSlider/VSlider.js
  packages/vuetify/src/components/VSlider/VSlider.sass
  packages/vuetify/src/components/VSlider/VSlider.ts
  packages/vuetify/src/components/VSlider/_mixins.sass
  packages/vuetify/src/components/VSlider/_variables.sass
  packages/vuetify/src/components/VSlider/index.ts
  packages/vuetify/src/stylus/components/_sliders.styl
  packages/vuetify/test/unit/components/VRangeSlider/VRangeSlider.spec.js
  packages/vuetify/test/unit/components/VRangeSlider/__snapshots__/VRangeSlider.spec.js.snap
  packages/vuetify/test/unit/components/VSlider/VSlider.spec.js
  packages/vuetify/test/unit/components/VSlider/__snapshots__/VSlider.spec.js.snap
Labels: T: feature

#6670 refactor(VCheckbox): convert to TypeScript
  packages/vuetify/src/components/VCheckbox/VCheckbox.ts
  packages/vuetify/src/components/VCheckbox/index.ts
Labels: T: enhancement

#6674 refactor(VForm): convert to TypeScript
  packages/vuetify/src/components/VForm/VForm.ts
  packages/vuetify/src/components/VForm/index.ts
  packages/vuetify/test/unit/components/VForm/VForm.spec.js
Labels: T: enhancement

#6680 docs(toolbar): fix slot extension example
  packages/docs/src/examples/toolbars/appBarExtension.vue
Labels: T: documentation

#6683 test(services): improve coverage
  packages/vuetify/src/services/lang/index.ts
  packages/vuetify/src/services/theme/__tests__/__snapshots__/theme.spec.ts.snap
  packages/vuetify/src/services/theme/__tests__/theme.spec.ts
  packages/vuetify/src/services/theme/index.ts
Labels: testing

#6679 test(util): convert to TypeScript and move
  packages/vuetify/src/util/__tests__/colorUtils.spec.ts
  packages/vuetify/src/util/__tests__/console.spec.ts
  packages/vuetify/src/util/__tests__/helpers.spec.ts
  packages/vuetify/src/util/__tests__/mask.spec.ts
Labels: testing

#6709 Korean translate
  packages/docs/src/lang/ko-KR/components/Avatars.json
  packages/docs/src/lang/ko-KR/components/BottomSheets.json
  packages/docs/src/lang/ko-KR/components/Breadcrumbs.json
  packages/docs/src/lang/ko-KR/components/Sliders.json
  packages/docs/src/lang/ko-KR/generic/Props.json
Labels: T: documentation

#6661 Feat/md2 window
  packages/vuetify/src/components/VWindow/VWindow.sass
  packages/vuetify/src/components/VWindow/VWindow.ts
  packages/vuetify/src/components/VWindow/__tests__/VWindow.spec.ts
  packages/vuetify/src/components/VWindow/__tests__/VWindowItem.spec.ts
  packages/vuetify/src/components/VWindow/_variables.sass
  packages/vuetify/src/mixins/proxyable.ts
  packages/vuetify/test/index.js
Labels: S: has merge conflicts, T: feature, md2

#6713 refactor(VSubheader): update to v2
  packages/vuetify/src/components/VSubheader/VSubheader.sass
  packages/vuetify/src/components/VSubheader/VSubheader.ts
  packages/vuetify/src/components/VSubheader/__tests__/VSubheader.spec.ts
  packages/vuetify/src/components/VSubheader/__tests__/__snapshots__/VSubheader.spec.ts.snap
  packages/vuetify/src/components/VSubheader/_mixins.sass
  packages/vuetify/src/components/VSubheader/_variables.scss
  packages/vuetify/src/stylus/components/_subheaders.styl
Labels: T: enhancement

#6735 feat(bootable): update for v2
  packages/docs/src/lang/en/mixins/Bootable.json
  packages/vuetify/src/components/VDataTable/VEditDialog.js
  packages/vuetify/src/components/VList/VListGroup.ts
  packages/vuetify/src/components/VList/__tests__/VListGroup.spec.ts
  packages/vuetify/src/components/VList/__tests__/__snapshots__/VListGroup.spec.ts.snap
  packages/vuetify/src/components/VSelect/VSelect.js
  packages/vuetify/src/components/VTooltip/__tests__/VTooltip.spec.js
  packages/vuetify/src/components/VTooltip/__tests__/__snapshots__/VTooltip.spec.js.snap
  packages/vuetify/src/mixins/bootable/__tests__/bootable.spec.ts
  packages/vuetify/src/mixins/bootable/index.ts
  packages/vuetify/src/mixins/detachable.ts
  packages/vuetify/test/unit/components/VCarousel/__snapshots__/VCarousel.spec.js.snap
  packages/vuetify/test/unit/components/VCarousel/__snapshots__/VCarouselItem.spec.js.snap
  packages/vuetify/test/unit/components/VDialog/VDialog.spec.js
  packages/vuetify/test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanel.spec.js.snap
  packages/vuetify/test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanelContent.spec.js.snap
  packages/vuetify/test/unit/components/VMenu/VMenu.spec.js
  packages/vuetify/test/unit/mixins/detachable.spec.js
Labels: T: enhancement

#6673 refactor(VSelect): convert to TypeScript
  packages/vuetify/src/components/VSelect/VSelect.ts
  packages/vuetify/src/components/VSelect/VSelectList.ts
  packages/vuetify/src/components/VSelect/index.ts
Labels: T: enhancement

#6741 refactor(VBottomNav): update to md2
  packages/api-generator/src/map.js
  packages/docs/src/components/ad/BottomNav.vue
  packages/docs/src/components/ad/Carbon.vue
  packages/docs/src/components/ad/CodeFund.vue
  packages/docs/src/data/deprecated.json
  packages/docs/src/data/pages/components/BottomNavigation.json
  packages/docs/src/examples/bottom-navigation/colorAndShift.vue
  packages/docs/src/examples/bottom-navigation/toggle.vue
  packages/docs/src/examples/bottom-navigation/usage.vue
  packages/docs/src/lang/en/components/AppBars.json
  packages/docs/src/lang/en/components/BottomNavigation.json
  packages/docs/src/lang/en/components/BottomSheets.json
  packages/docs/src/lang/en/meta.json
  packages/docs/src/lang/en/mixins/Scrollable.json
  packages/docs/src/lang/es-MX/components/BottomNavigation.json
  packages/docs/src/lang/es-MX/components/BottomSheets.json
  packages/docs/src/lang/es-MX/meta.json
  packages/docs/src/lang/ja-JP/components/BottomNavigation.json
  packages/docs/src/lang/ja-JP/components/BottomSheets.json
  packages/docs/src/lang/ja-JP/meta.json
  packages/docs/src/lang/ko-KR/components/BottomNavigation.json
  packages/docs/src/lang/ko-KR/components/BottomSheets.json
  packages/docs/src/lang/ko-KR/meta.json
  packages/docs/src/lang/pt-BR/components/BottomNavigation.json
  packages/docs/src/lang/pt-BR/components/BottomSheets.json
  packages/docs/src/lang/ru-RU/components/BottomNavigation.json
  packages/docs/src/lang/ru-RU/components/BottomSheets.json
  packages/docs/src/lang/ru-RU/meta.json
  packages/docs/src/lang/zh-CN/components/BottomNavigation.json
  packages/docs/src/lang/zh-CN/components/BottomSheets.json
  packages/vuetify/src/components/VAppBar/VAppBar.ts
  packages/vuetify/src/components/VAppBar/__tests__/VAppBar.spec.ts
  packages/vuetify/src/components/VBottomNav/VBottomNav.ts
  packages/vuetify/src/components/VBottomNav/index.ts
  packages/vuetify/src/components/VBottomNavigation/VBottomNavigation.sass
  packages/vuetify/src/components/VBottomNavigation/VBottomNavigation.ts
  packages/vuetify/src/components/VBottomNavigation/__tests__/VBottomNavigation.spec.ts
  packages/vuetify/src/components/VBottomNavigation/__tests__/__snapshots__/VBottomNavigation.spec.ts.snap
  packages/vuetify/src/components/VBottomNavigation/_mixins.sass
  packages/vuetify/src/components/VBottomNavigation/_variables.scss
  packages/vuetify/src/components/VBottomNavigation/index.ts
  packages/vuetify/src/components/index.ts
  packages/vuetify/src/mixins/scrollable/__tests__/scrollable.spec.ts
  packages/vuetify/src/mixins/scrollable/index.ts
  packages/vuetify/src/stylus/components/_bottom-navs.styl
  packages/vuetify/test/index.js
  packages/vuetify/test/unit/components/VBottomNav/VBottomNav.spec.js
  packages/vuetify/test/unit/components/VBottomNav/__snapshots__/VBottomNav.spec.js.snap
  packages/vuetify/types/lib.d.ts
Labels: T: enhancement

#6720 feat(VExpansionPanel): update to v2
  packages/api-generator/src/map.js
  packages/docs/src/components/doc/Example.vue
  packages/docs/src/data/deprecated.json
  packages/docs/src/data/pages/components/ExpansionPanels.json
  packages/docs/src/examples/avatars/advanced.vue
  packages/docs/src/examples/expansion-panels/advanced.vue
  packages/docs/src/examples/expansion-panels/customIcons.vue
  packages/docs/src/examples/expansion-panels/disabledAndReadonly.vue
  packages/docs/src/examples/expansion-panels/expand.vue
  packages/docs/src/examples/expansion-panels/external.vue
  packages/docs/src/examples/expansion-panels/focusable.vue
  packages/docs/src/examples/expansion-panels/iconSlot.vue
  packages/docs/src/examples/expansion-panels/popout.vue
  packages/docs/src/examples/expansion-panels/usage.vue
  packages/docs/src/lang/en/components/ExpansionPanels.json
  packages/docs/src/lang/en/framework/ALaCarte.json
  packages/docs/src/lang/eo-UY/components/ExpansionPanels.json
  packages/docs/src/lang/es-MX/components/ExpansionPanels.json
  packages/docs/src/lang/es-MX/framework/ALaCarte.json
  packages/docs/src/lang/ko-KR/components/ExpansionPanels.json
  packages/docs/src/lang/ko-KR/framework/ALaCarte.json
  packages/docs/src/lang/pt-BR/framework/ALaCarte.json
  packages/docs/src/lang/ru-RU/components/ExpansionPanels.json
  packages/docs/src/lang/zh-CN/components/ExpansionPanels.json
  packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.sass
  packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.ts
  packages/vuetify/src/components/VExpansionPanel/VExpansionPanelContent.ts
  packages/vuetify/src/components/VExpansionPanel/VExpansionPanelHeader.ts
  packages/vuetify/src/components/VExpansionPanel/VExpansionPanels.ts
  packages/vuetify/src/components/VExpansionPanel/__tests__/VExpansionPanel.spec.ts
  packages/vuetify/src/components/VExpansionPanel/__tests__/VExpansionPanelHeader.spec.ts
  packages/vuetify/src/components/VExpansionPanel/__tests__/VExpansionPanels.spec.ts
  packages/vuetify/src/components/VExpansionPanel/__tests__/__snapshots__/VExpansionPanel.spec.ts.snap
  packages/vuetify/src/components/VExpansionPanel/_mixins.sass
  packages/vuetify/src/components/VExpansionPanel/_variables.scss
  packages/vuetify/src/components/VExpansionPanel/index.ts
  packages/vuetify/src/mixins/groupable/index.ts
  packages/vuetify/src/mixins/registrable/index.ts
  packages/vuetify/src/stylus/components/_expansion-panel.styl
  packages/vuetify/src/util/helpers.ts
  packages/vuetify/test/unit/components/VExpansionPanel/VExpansionPanel.spec.js
  packages/vuetify/test/unit/components/VExpansionPanel/VExpansionPanelContent.spec.js
  packages/vuetify/test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanel.spec.js.snap
  packages/vuetify/test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanelContent.spec.js.snap
Labels: T: enhancement

#6772 docs(component): add complement to "item-key" of DataTable
  packages/docs/src/lang/en/components/DataTables.json
  packages/docs/src/lang/zh-CN/components/DataTables.json
Labels: T: documentation

#6460 fix(VMenu, VTooltip): detect when activator has position:fixed
  packages/docs/src/components/core/Ecosystems.vue
  packages/docs/src/components/core/Locales.vue
  packages/docs/src/components/core/Versions.vue
  packages/vuetify/src/components/VMenu/mixins/menu-generators.js
  packages/vuetify/src/components/VTooltip/VTooltip.js
  packages/vuetify/src/mixins/menuable.js
  packages/vuetify/src/stylus/components/_menus.styl
  packages/vuetify/src/stylus/components/_tooltips.styl
Labels: T: enhancement

#6742 [WIP] test(vselect): convert tests to vue-test-utils
  packages/vuetify/src/components/VSelect/VSelect.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect2.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect3.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect4.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelectList.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect.spec.ts.snap
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect2.spec.ts.snap
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect3.spec.ts.snap
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelectList.spec.ts.snap
  packages/vuetify/test/unit/components/VAutocomplete/VAutocomplete.spec.js
  packages/vuetify/test/unit/components/VSelect/VSelect2.spec.js
  packages/vuetify/test/unit/components/VSelect/VSelect3.spec.js
Labels: S: work in progress

#6778 refactor(VBreadcrumbs): update for v2
  packages/docs/src/data/deprecated.json
  packages/docs/src/examples/breadcrumbs/itemSlot.vue
  packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.sass
  packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.ts
  packages/vuetify/src/components/VBreadcrumbs/__tests__/VBreadcrumbs.spec.ts
  packages/vuetify/src/components/VBreadcrumbs/__tests__/VBreadcrumbsItem.spec.ts
  packages/vuetify/src/components/VBreadcrumbs/__tests__/__snapshots__/VBreadcrumbs.spec.ts.snap
  packages/vuetify/src/components/VBreadcrumbs/__tests__/__snapshots__/VBreadcrumbsItem.spec.ts.snap
  packages/vuetify/src/components/VBreadcrumbs/_mixins.sass
  packages/vuetify/src/components/VBreadcrumbs/_variables.scss
  packages/vuetify/src/stylus/components/_breadcrumbs.styl
  packages/vuetify/src/stylus/settings/_variables.styl
  packages/vuetify/test/unit/components/VBreadcrumbs/VBreadcrumbs.spec.js
  packages/vuetify/test/unit/components/VBreadcrumbs/VBreadcrumbsItem.spec.js
Labels: T: enhancement

#6786 refactor(VBottomSheet): update for v2
  packages/docs/src/examples/bottom-sheets/inset.vue
  packages/docs/src/examples/bottom-sheets/usage.vue
  packages/vuetify/src/components/VBottomSheet/VBottomSheet.js
  packages/vuetify/src/components/VBottomSheet/VBottomSheet.sass
  packages/vuetify/src/components/VBottomSheet/VBottomSheet.ts
  packages/vuetify/src/components/VBottomSheet/index.ts
  packages/vuetify/src/components/transitions/index.ts
  packages/vuetify/src/stylus/components/_bottom-sheets.styl
  packages/vuetify/src/stylus/generic/_transitions.styl
Labels: T: enhancement

#6826 refactor(VTooltip): convert to TS
  packages/vuetify/src/components/VTooltip/VTooltip.ts
  packages/vuetify/src/components/VTooltip/__tests__/VTooltip.spec.ts
  packages/vuetify/src/components/VTooltip/__tests__/__snapshots__/VTooltip.spec.ts.snap
  packages/vuetify/src/components/VTooltip/index.ts
Labels: T: enhancement

#6831 refactor(icons-service): improve typings
  packages/vuetify/src/components/VIcon/VIcon.ts
  packages/vuetify/src/services/icons/presets/index.ts
  packages/vuetify/src/util/helpers.ts
  packages/vuetify/types/index.d.ts
  packages/vuetify/types/presets/index.d.ts
  packages/vuetify/types/services/icons.d.ts
  packages/vuetify/types/test/plugin.ts
Labels: T: enhancement

#6853 refactor(selection-controls): convert to SASS
  packages/vuetify/src/components/VCheckbox/VCheckbox.ts
  packages/vuetify/src/components/VRadioGroup/VRadioGroup.js
  packages/vuetify/src/components/VSwitch/VSwitch.js
  packages/vuetify/src/styles/components/_index.sass
  packages/vuetify/src/styles/components/_mixins.sass
  packages/vuetify/src/styles/components/_selection-controls.sass
  packages/vuetify/src/styles/settings/_variables.scss
Labels: T: enhancement

#6858 test(VCheckbox): convert to TS and @vue/test-utils
  packages/vuetify/src/components/VCheckbox/__tests__/VCheckbox.spec.ts
  packages/vuetify/src/components/VCheckbox/__tests__/__snapshots__/VCheckbox.spec.ts.snap
Labels: T: enhancement, testing

#6788 feat(VCard): update to md2
  packages/docs/src/data/pages/components/Cards.json
  packages/docs/src/examples/cards/advanced.vue
  packages/docs/src/examples/cards/customActions.vue
  packages/docs/src/examples/cards/desert.vue
  packages/docs/src/examples/cards/grids.vue
  packages/docs/src/examples/cards/horizontal.vue
  packages/docs/src/examples/cards/infoCard.vue
  packages/docs/src/examples/cards/intermediate.vue
  packages/docs/src/examples/cards/loading.vue
  packages/docs/src/examples/cards/mediaWithText.vue
  packages/docs/src/examples/cards/outlined.vue
  packages/docs/src/examples/cards/usage.vue
  packages/docs/src/examples/cards/weather.vue
  packages/docs/src/lang/en/components/Cards.json
  packages/docs/src/lang/en/mixins/Loadable.json
  packages/vuetify/src/components/VCard/VCard.sass
  packages/vuetify/src/components/VCard/VCard.ts
  packages/vuetify/src/components/VCard/VCardMedia.ts
  packages/vuetify/src/components/VCard/VCardText.ts
  packages/vuetify/src/components/VCard/VCardTitle.ts
  packages/vuetify/src/components/VCard/__tests__/VCard.spec.ts
  packages/vuetify/src/components/VCard/__tests__/VCardText.spec.ts
  packages/vuetify/src/components/VCard/__tests__/__snapshots__/VCard.spec.ts.snap
  packages/vuetify/src/components/VCard/__tests__/__snapshots__/VCardText.spec.ts.snap
  packages/vuetify/src/components/VCard/_mixins.sass
  packages/vuetify/src/components/VCard/index.ts
  packages/vuetify/src/components/VPicker/VPicker.ts
  packages/vuetify/src/components/VSelect/VSelectList.ts
  packages/vuetify/src/mixins/loadable/index.ts
  packages/vuetify/test/unit/components/VCard/VCard.spec.js
  packages/vuetify/test/unit/components/VCard/VCardTitle.spec.js
  packages/vuetify/test/unit/components/VCard/__snapshots__/VCard.spec.js.snap
  packages/vuetify/test/unit/components/VCard/__snapshots__/VCardTitle.spec.js.snap
Labels: T: bug, T: enhancement

#6830 [WIP] test(VGrid): convert tests to vue-test-utils
  packages/vuetify/src/components/VGrid/__tests__/VGrid.spec.ts
  packages/vuetify/test/unit/components/VGrid/VGrid.spec.js
Labels: S: work in progress, help wanted

#6867 refactor(VPicker): convert to SASS
  packages/vuetify/src/components/VPicker/VPicker.sass
  packages/vuetify/src/components/VPicker/VPicker.ts
  packages/vuetify/src/components/VPicker/_mixins.sass
  packages/vuetify/src/components/VPicker/_variables.scss
Labels: T: enhancement

#6849 refactor(VTreeview): update to v2
  packages/vuetify/src/components/VTreeview/VTreeview.sass
  packages/vuetify/src/components/VTreeview/VTreeview.ts
  packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
  packages/vuetify/src/components/VTreeview/__tests__/VTreeview.spec.ts
  packages/vuetify/src/components/VTreeview/__tests__/VTreeviewNode.spec.ts
  packages/vuetify/src/components/VTreeview/__tests__/__snapshots__/VTreeview.spec.ts.snap
  packages/vuetify/src/components/VTreeview/__tests__/__snapshots__/VTreeviewNode.spec.ts.snap
  packages/vuetify/src/components/VTreeview/_mixins.sass
  packages/vuetify/src/components/VTreeview/_variables.scss
Labels: T: enhancement, T: feature, a11y

#6869 Feat/md2 time picker
  packages/docs/src/examples/time-pickers/usage.vue
  packages/docs/src/lang/en/components/TimePickers.json
  packages/kitchen/src/pan/Time pickers.vue
  packages/vuetify/src/components/VTimePicker/VTimePicker.ts
  packages/vuetify/src/components/VTimePicker/VTimePickerClock.sass
  packages/vuetify/src/components/VTimePicker/VTimePickerClock.ts
  packages/vuetify/src/components/VTimePicker/VTimePickerTitle.sass
  packages/vuetify/src/components/VTimePicker/VTimePickerTitle.ts
  packages/vuetify/src/components/VTimePicker/__tests__/VTimePicker.spec.ts
  packages/vuetify/src/components/VTimePicker/__tests__/VTimePickerClock.spec.ts
  packages/vuetify/src/components/VTimePicker/__tests__/VTimePickerTitle.spec.ts
  packages/vuetify/src/components/VTimePicker/__tests__/__snapshots__/VTimePicker.spec.ts.snap
  packages/vuetify/src/components/VTimePicker/__tests__/__snapshots__/VTimePickerClock.spec.ts.snap
  packages/vuetify/src/components/VTimePicker/__tests__/__snapshots__/VTimePickerTitle.spec.ts.snap
  packages/vuetify/src/components/VTimePicker/_mixins.sass
  packages/vuetify/src/components/VTimePicker/_variables.scss
Labels: T: enhancement, T: feature, a11y, md2, needs docs update

#6851 feat(VSwitch): update to md2
  packages/docs/src/data/pages/components/SelectionControls.json
  packages/docs/src/examples/selection-controls/switchesFlat.vue
  packages/docs/src/examples/selection-controls/switchesStates.vue
  packages/docs/src/lang/en/components/SelectionControls.json
  packages/kitchen/src/pan/Switches.vue
  packages/vuetify/src/components/VSwitch/VSwitch.sass
  packages/vuetify/src/components/VSwitch/VSwitch.ts
  packages/vuetify/src/components/VSwitch/__tests__/VSwitch.spec.ts
  packages/vuetify/src/components/VSwitch/__tests__/__snapshots__/VSwitch.spec.ts.snap
  packages/vuetify/src/components/VSwitch/_mixins.sass
  packages/vuetify/src/components/VSwitch/_variables.sass
  packages/vuetify/src/components/VSwitch/index.ts
  packages/vuetify/src/styles/settings/_light.scss
  packages/vuetify/src/stylus/components/_switch.styl
Labels: T: enhancement, T: feature, a11y, kitchen, md2

#6879 chore(framework): remove deprecated stylus
  packages/docs/build/webpack.client.config.js
  packages/docs/build/webpack.server.config.js
  packages/docs/package.json
  packages/docs/src/components/core/Drawer.vue
  packages/docs/src/components/doc/Example.vue
  packages/docs/src/lang/en/framework/ALaCarte.json
  packages/docs/src/lang/pt-BR/framework/ALaCarte.json
  packages/docs/src/lang/ru-RU/framework/ALaCarte.json
  packages/kitchen/package.json
  packages/vuetify/.babelrc
  packages/vuetify/.eslintignore
  packages/vuetify/build/babel-transform-stylus-paths.js
  packages/vuetify/build/webpack.base.config.js
  packages/vuetify/package.json
  packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.sass
  packages/vuetify/src/components/VCard/VCard.sass
  packages/vuetify/src/components/VDialog/VDialog.sass
  packages/vuetify/src/components/VOverflowBtn/VOverflowBtn.sass
  packages/vuetify/src/components/VSlider/VSlider.sass
  packages/vuetify/src/components/VSlider/_variables.sass
  packages/vuetify/src/components/VSlider/_variables.scss
  packages/vuetify/src/components/VSnackbar/VSnackbar.sass
  packages/vuetify/src/framework.ts
  packages/vuetify/src/stylus/app.styl
  packages/vuetify/src/stylus/bootstrap.styl
  packages/vuetify/src/stylus/browsers.styl
  packages/vuetify/src/stylus/main.styl
  packages/vuetify/src/stylus/settings/_colors.styl
  packages/vuetify/src/stylus/settings/_elevations.styl
  packages/vuetify/src/stylus/settings/_rtl.styl
  packages/vuetify/src/stylus/settings/_theme.styl
  packages/vuetify/src/stylus/settings/_variables.styl
  packages/vuetify/src/stylus/theme.styl
  yarn.lock
Labels: T: enhancement, semver: major

#6882 feat(theme): add reactivity
  packages/vuetify/src/services/theme/__tests__/theme.spec.ts
  packages/vuetify/src/services/theme/index.ts
  packages/vuetify/test/unit/components/VRadioGroup/__snapshots__/VRadioGroup.spec.js.snap
Labels: T: enhancement

#6880 docs(VBanner): translate to Russian
  packages/docs/src/lang/ru-RU/components/Banners.json
Labels: T: documentation
