Repository vuetifyjs/vuetify, pull requests merged in 2019-01, with the labels that each got.

#6028 docs(VCard): add Russian translation for Twitter Card example
  packages/vuetifyjs.com/src/lang/ru/components/Cards.json
Labels: P: low, T: documentation

#6041 docs(Icons): add link to SVG guide
  packages/vuetifyjs.com/src/lang/en/components/Icons.json
Labels: T: documentation, T: enhancement

#6030 Added Romanian translation
  packages/vuetify/src/locale/index.ts
  packages/vuetify/src/locale/ro.ts
Labels: T: enhancement

#6063 docs(VNavigationDrawer): fix typos in Chinese
  packages/vuetifyjs.com/src/lang/zh-Hans/components/NavigationDrawers.json
Labels: T: documentation

#5948 fix(VCarousel): prevent container recreation
  packages/vuetify/src/components/VCarousel/VCarousel.ts
  packages/vuetify/test/unit/components/VCarousel/__snapshots__/VCarousel.spec.js.snap
Labels: T: enhancement, T: feature

#5956 fix(VChip): Removes transparent border
  packages/vuetify/src/stylus/components/_chips.styl
Labels: T: enhancement

#5905 fix(VRadio): fix `focus` event
  packages/vuetify/src/components/VRadioGroup/VRadio.js
Labels: T: bug

#6054 fix(VSelect): don't emit change event when clicked on the selected item
  packages/vuetify/src/components/VSelect/VSelect.js
  packages/vuetify/test/unit/components/VSelect/VSelect.spec.js
  packages/vuetify/test/unit/components/VSelect/VSelect3.spec.js
Labels: T: bug

#5716 fix(VMenu): don't close on tab if child element has focus
  packages/vuetify/src/components/VMenu/mixins/menu-keyable.js
  packages/vuetify/test/unit/components/VMenu/VMenu.spec.js
Labels: T: bug

#6037 feat(VBtn): support Material Design 2
  jest.config.js
  packages/kitchen/package.json
  packages/kitchen/src/App.vue
  packages/kitchen/src/pan/Buttons.vue
  packages/vuetify/package.json
  packages/vuetify/src/components/VBtn/VBtn.sass
  packages/vuetify/src/components/VBtn/VBtn.ts
  packages/vuetify/src/components/VBtn/__tests__/VBtn.spec.ts
  packages/vuetify/src/components/VBtn/__tests__/__snapshots__/VBtn.spec.ts.snap
  packages/vuetify/src/components/VBtn/_mixins.sass
  packages/vuetify/src/components/VBtn/_variables.sass
  packages/vuetify/src/components/VBtnToggle/VBtnToggle.sass
  packages/vuetify/src/components/VBtnToggle/VBtnToggle.ts
  packages/vuetify/src/components/VDataTable/VEditDialog.js
  packages/vuetify/src/components/VIcon/VIcon.ts
  packages/vuetify/src/components/VOverflowBtn/VOverflowBtn.js
  packages/vuetify/src/components/VToolbar/VToolbarSideIcon.js
  packages/vuetify/src/mixins/data-iterable.js
  packages/vuetify/src/mixins/routable.ts
  packages/vuetify/src/mixins/sizeable.ts
  packages/vuetify/src/styles/helpers/_elevation.sass
  packages/vuetify/src/styles/helpers/_rtl.sass
  packages/vuetify/src/styles/themes/_dark.scss
  packages/vuetify/src/styles/themes/_light.scss
  packages/vuetify/src/stylus/components/_button-toggle.styl
  packages/vuetify/src/stylus/components/_buttons.styl
  packages/vuetify/src/stylus/components/_icons.styl
  packages/vuetify/src/stylus/components/_sheet.styl
  packages/vuetify/test/unit/components/VBottomNav/VBottomNav.spec.js
  packages/vuetify/test/unit/components/VBottomNav/__snapshots__/VBottomNav.spec.js.snap
  packages/vuetify/test/unit/components/VBtn/VBtn.spec.js
  packages/vuetify/test/unit/components/VBtn/__snapshots__/VBtn.spec.js.snap
  packages/vuetify/test/unit/components/VCarousel/__snapshots__/VCarousel.spec.js.snap
  packages/vuetify/test/unit/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
  packages/vuetify/test/unit/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
  packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePicker.date.spec.js.snap
  packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePicker.month.spec.js.snap
  packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePickerHeader.spec.js.snap
  packages/vuetify/test/unit/components/VIcon/VIcon.spec.js
  packages/vuetify/test/unit/components/VIcon/__snapshots__/VIcon.spec.js.snap
  packages/vuetify/test/unit/components/VMenu/__snapshots__/VMenu.spec.js.snap
  packages/vuetify/test/unit/components/VOverflowBtn/__snapshots__/VOverflowBtn.spec.js.snap
  packages/vuetify/test/unit/components/VToolbar/__snapshots__/VToolbarSideIcon.spec.js.snap
  packages/vuetifyjs.com/src/data/pages/components/ButtonGroups.json
  packages/vuetifyjs.com/src/examples/button-groups/qwerty.vue
  packages/vuetifyjs.com/src/examples/button-groups/togglePictures.vue
  packages/vuetifyjs.com/src/examples/buttons/usage.vue
  packages/vuetifyjs.com/src/lang/en/components/ButtonGroups.json
  yarn.lock
Labels: PR: don't squash, T: enhancement, T: feature, md2, need unit tests, needs docs update, semver: major

#6126 feat(VProgressLinear): support for content inside progress bar
  packages/vuetify/src/components/VProgressLinear/VProgressLinear.ts
  packages/vuetify/src/stylus/components/_progress-linear.styl
  packages/vuetify/test/unit/components/VProgressLinear/VProgressLinear.spec.js
  packages/vuetify/test/unit/components/VProgressLinear/__snapshots__/VProgressLinear.spec.js.snap
Labels: S: work in progress, needs docs update

#6080 feat(VSparkline): add bar type
  packages/docs/src/lang/en/components/Sparklines.json
  packages/vuetify/src/components/VSparkline/VSparkline.ts
Labels: T: feature

#6091 fix(VAutocomplete): may not show menu with hide-selected
  packages/vuetify/src/components/VAutocomplete/VAutocomplete.js
  packages/vuetify/src/components/VCombobox/VCombobox.js
  packages/vuetify/test/unit/components/VAutocomplete/VAutocomplete.spec.js
Labels: T: bug, T: enhancement

#6130 docs(kitchen): add more examples to VAlert pan
  packages/kitchen/src/pan/Alerts.vue
Labels: T: enhancement, T: feature

#6107 feat(VAlert): update styles
  packages/docs/src/data/deprecated.json
  packages/docs/src/examples/alerts/closable.vue
  packages/docs/src/examples/alerts/icon.vue
  packages/docs/src/examples/alerts/outline.vue
  packages/docs/src/examples/alerts/transition.vue
  packages/docs/src/examples/alerts/usage.vue
  packages/docs/src/lang/en/components/Alerts.json
  packages/docs/src/lang/en/components/Sparklines.json
  packages/docs/src/lang/en/components/Treeview.json
  packages/docs/src/lang/en/generic/Props.json
  packages/kitchen/src/pan/Alerts.vue
  packages/vuetify/src/components/VAlert/VAlert.sass
  packages/vuetify/src/components/VAlert/VAlert.ts
  packages/vuetify/src/components/VAlert/__tests__/VAlert.spec.js
  packages/vuetify/src/components/VAlert/__tests__/VAlert.spec.ts
  packages/vuetify/src/components/VAlert/__tests__/__snapshots__/VAlert.spec.ts.snap
  packages/vuetify/src/components/VAlert/_mixins.sass
  packages/vuetify/src/components/VAlert/_variables.scss
  packages/vuetify/src/components/VProgressLinear/VProgressLinear.ts
  packages/vuetify/src/components/VSparkline/VSparkline.ts
  packages/vuetify/src/components/VTreeview/VTreeview.ts
  packages/vuetify/src/locale/en.ts
  packages/vuetify/src/locale/hr.ts
  packages/vuetify/src/locale/index.ts
  packages/vuetify/src/locale/th.ts
  packages/vuetify/src/stylus/components/_alerts.styl
  packages/vuetify/src/stylus/components/_progress-linear.styl
  packages/vuetify/src/stylus/settings/_variables.styl
  packages/vuetify/src/util/console.ts
  packages/vuetify/test/unit/components/VAlert/__snapshots__/VAlert.spec.js.snap
  packages/vuetify/test/unit/components/VProgressLinear/VProgressLinear.spec.js
  packages/vuetify/test/unit/components/VProgressLinear/__snapshots__/VProgressLinear.spec.js.snap
  packages/vuetify/test/unit/components/VTreeview/VTreeview.spec.js
  packages/vuetify/test/unit/components/VTreeview/__snapshots__/VTreeview.spec.js.snap
Labels: T: enhancement, T: feature, md2, semver: major

#6131 docs: improve some Russian docs
  packages/docs/src/lang/ru/components/Avatars.json
  packages/docs/src/lang/ru/components/BottomSheets.json
  packages/docs/src/lang/ru/components/Buttons.json
Labels: T: documentation

#6142 docs(kitchen): add VRating pan
  packages/kitchen/src/pan/Ratings.vue
Labels: T: documentation

#6137 refactor(VDatePicker): convert to Typescript
  packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts
  packages/vuetify/src/components/VDatePicker/VDatePickerHeader.ts
  packages/vuetify/src/components/VDatePicker/VDatePickerMonthTable.ts
  packages/vuetify/src/components/VDatePicker/VDatePickerTitle.ts
  packages/vuetify/src/components/VDatePicker/VDatePickerYears.ts
  packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.js
  packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts
  packages/vuetify/src/components/VDatePicker/util/createNativeLocaleFormatter.js
  packages/vuetify/src/components/VDatePicker/util/createNativeLocaleFormatter.ts
  packages/vuetify/src/components/VDatePicker/util/index.ts
  packages/vuetify/src/components/VDatePicker/util/isDateAllowed.js
  packages/vuetify/src/components/VDatePicker/util/isDateAllowed.ts
  packages/vuetify/src/components/VDatePicker/util/monthChange.ts
  packages/vuetify/src/components/VDatePicker/util/pad.ts
  packages/vuetify/src/components/VTimePicker/VTimePicker.ts
  packages/vuetify/src/directives/touch.ts
  packages/vuetify/src/mixins/picker-button.ts
  packages/vuetify/test/unit/components/VDatePicker/VDatePickerDateTable.spec.js
  packages/vuetify/test/unit/components/VDatePicker/VDatePickerMonthTable.spec.js
  packages/vuetify/test/unit/components/VDatePicker/util/createNativeLocaleFormatter.spec.js
Labels: task

#6079 fix(VTimePicker): emit change event after clicking minutes/seconds
  packages/vuetify/src/components/VTimePicker/VTimePicker.ts
Labels: T: bug

#6144 docs(kitchen): add VTimePicker pan
  packages/kitchen/src/pan/Time pickers.vue
Labels: T: documentation, T: enhancement, T: feature

#6092 feat(VCalendar): add new component
  packages/api-generator/src/map.js
  packages/docs/src/data/drawerItems.json
  packages/docs/src/data/pages/components/Calendars.json
  packages/docs/src/examples/calendars/daily.vue
  packages/docs/src/examples/calendars/events.vue
  packages/docs/src/examples/calendars/features.vue
  packages/docs/src/examples/calendars/slots.vue
  packages/docs/src/examples/calendars/usage.vue
  packages/docs/src/examples/calendars/weekly.vue
  packages/docs/src/lang/en/components/Calendars.json
  packages/docs/src/lang/en/meta.json
  packages/docs/src/lang/en/vuetify/AppDrawer.json
  packages/vuetify/src/components/VCalendar/VCalendar.ts
  packages/vuetify/src/components/VCalendar/VCalendarDaily.ts
  packages/vuetify/src/components/VCalendar/VCalendarMonthly.ts
  packages/vuetify/src/components/VCalendar/VCalendarWeekly.ts
  packages/vuetify/src/components/VCalendar/index.ts
  packages/vuetify/src/components/VCalendar/mixins/calendar-base.ts
  packages/vuetify/src/components/VCalendar/mixins/calendar-with-intervals.ts
  packages/vuetify/src/components/VCalendar/mixins/mouse.ts
  packages/vuetify/src/components/VCalendar/mixins/times.ts
  packages/vuetify/src/components/VCalendar/util/props.ts
  packages/vuetify/src/components/VCalendar/util/timestamp.ts
  packages/vuetify/src/components/index.ts
  packages/vuetify/src/stylus/components/_calendar-daily.styl
  packages/vuetify/src/stylus/components/_calendar-weekly.styl
  packages/vuetify/src/stylus/settings/_theme.styl
  packages/vuetify/src/stylus/settings/_variables.styl
  packages/vuetify/test/integration/__snapshots__/importA-la-carte.spec.js.snap
  packages/vuetify/test/integration/__snapshots__/importFull.spec.js.snap
  packages/vuetify/test/integration/__snapshots__/importLib.spec.js.snap
  packages/vuetify/test/integration/importA-la-carte.spec.js
  packages/vuetify/test/integration/importLib.spec.js
Labels: T: feature, need unit tests, needs docs update

#5967 fix(VTooltip): Update tooltip position dynamically
  packages/vuetify/src/components/VTooltip/VTooltip.js
  packages/vuetify/src/stylus/components/_tooltips.styl
Labels: T: enhancement, T: feature

#6086 feat(VSelect): replicate html select hotkeys
  packages/vuetify/src/components/VItemGroup/VItemGroup.ts
  packages/vuetify/src/components/VSelect/VSelect.js
  packages/vuetify/test/unit/components/VSelect/VSelect3.spec.js
Labels: T: enhancement, T: feature

#6111 feat: update tooltip design
  jest.config.js
  packages/vuetify/src/components/VAlert/__tests__/VAlert.spec.js
  packages/vuetify/src/components/VTooltip/VTooltip.js
  packages/vuetify/src/components/VTooltip/VTooltip.sass
  packages/vuetify/src/components/VTooltip/__tests__/VTooltip.spec.js
  packages/vuetify/src/components/VTooltip/__tests__/__snapshots__/VTooltip.spec.js.snap
  packages/vuetify/src/components/VTooltip/_variables.sass
  packages/vuetify/src/styles/base/_variables.scss
  packages/vuetify/src/stylus/components/_tooltips.styl
  packages/vuetify/src/stylus/generic/_transitions.styl
  packages/vuetify/src/stylus/settings/_variables.styl
  packages/vuetify/test/unit/components/VTooltip/__snapshots__/VTooltip.spec.js.snap
Labels: T: enhancement, T: feature, md2

#6185 docs(VDataTable): improve expand documentation
  packages/docs/src/examples/data-tables/expand.vue
  packages/docs/src/lang/en/components/DataTables.json
  packages/docs/src/lang/es-MX/components/DataTables.json
Labels: T: documentation

#6193 Fix/menu position
  packages/vuetify/src/components/VMenu/VMenu.js
  packages/vuetify/src/mixins/menuable.js
  packages/vuetify/test/unit/mixins/menuable.spec.js
Labels: T: bug

#6132 feat(VSparkline): add fill property
  packages/docs/src/data/pages/components/Sparklines.json
  packages/docs/src/examples/sparklines/fill.vue
  packages/docs/src/lang/en-US/components/Sparklines.json
  packages/vuetify/src/components/VSparkline/VSparkline.ts
  packages/vuetify/src/components/VSparkline/helpers/path.ts
Labels: T: feature

#6217 fix(VAlert): fix border with dense prop
  packages/vuetify/src/components/VAlert/VAlert.sass
  packages/vuetify/src/components/VAlert/_variables.scss
  packages/vuetify/src/styles/base/_variables.scss
Labels: T: bug, md2

#6215 docs(kitchen): add more examples for VAlert
  packages/kitchen/src/pan/Alerts.vue
Labels: T: documentation, T: enhancement, kitchen

#6187 docs(kitchen): add VTimeline pan
  packages/kitchen/src/pan/Timelines.vue
Labels: T: documentation, kitchen

#5833 refactor(goTo): full rewrite, target container selection, typescript
  packages/vuetify/src/components/Vuetify/goTo/easing-patterns.ts
  packages/vuetify/src/components/Vuetify/goTo/index.ts
  packages/vuetify/src/components/Vuetify/goTo/util.ts
  packages/vuetify/src/components/Vuetify/index.ts
  packages/vuetify/src/components/Vuetify/util/goTo.js
  packages/vuetify/test/unit/components/Vuetify/goTo/goTo.spec.js
  packages/vuetify/test/unit/components/Vuetify/util/goTo.spec.js
Labels: T: feature

#6210 docs(kitchen): rebuild, add CoreTitle and CoreSection components
  packages/kitchen/src/components/CoreSection.vue
  packages/kitchen/src/components/CoreTitle.vue
  packages/kitchen/src/main.js
  packages/kitchen/src/pan/Alerts.vue
  packages/kitchen/src/pan/Avatars.vue
  packages/kitchen/src/pan/Badges.vue
  packages/kitchen/src/pan/Buttons.vue
  packages/kitchen/src/pan/Chips.vue
  packages/kitchen/src/pan/Date pickers.vue
  packages/kitchen/src/pan/Dividers.vue
  packages/kitchen/src/pan/Hover.vue
  packages/kitchen/src/pan/Icons.vue
  packages/kitchen/src/pan/Images.vue
  packages/kitchen/src/pan/Month pickers.vue
  packages/kitchen/src/pan/Parallaxes.vue
  packages/kitchen/src/pan/Ratings.vue
  packages/kitchen/src/pan/Sheets.vue
  packages/kitchen/src/pan/Sparklines.vue
  packages/kitchen/src/pan/Text fields.vue
  packages/kitchen/src/pan/Time pickers.vue
  packages/kitchen/src/pan/Toolbars.vue
  packages/kitchen/src/pan/Tooltips.vue
  packages/kitchen/src/pan/Treeviews.vue
  packages/kitchen/src/pan/_Template.vue
  packages/kitchen/src/views/Home.vue
Labels: T: enhancement

#6232 docs(kitchen): add VCard pan
  packages/kitchen/src/pan/Cards.vue
Labels: T: enhancement, kitchen

#6236 docs(kitchen): use CoreSection and CoreTitle in Timelines pan
  packages/kitchen/src/pan/Timelines.vue
Labels: T: bug, T: enhancement, kitchen

#6238 docs(kitchen): add VList pan
  packages/kitchen/src/pan/Lists.vue
Labels: kitchen

#6239 docs(kitchen): add VTabs pan
  packages/kitchen/src/pan/Tabs.vue
Labels: kitchen

#6252 docs(kitchen): add VItemGroup pan
  packages/kitchen/src/pan/Item Groups.vue
Labels: kitchen

#6248 docs(kitchen): add VWindow pan
  packages/kitchen/src/pan/Windows.vue
Labels: kitchen

#6250 docs(kitchen): use VAutocomplete on the Home page
  packages/kitchen/src/views/Home.vue
Labels: kitchen

#6240 feat(VSlideGroup): create new component
  packages/docs/src/data/drawerItems.json
  packages/docs/src/data/pages/components/SlideGroups.json
  packages/docs/src/examples/slide-groups/carousel.vue
  packages/docs/src/examples/slide-groups/usage.vue
  packages/docs/src/lang/en-US/components/SlideGroups.json
  packages/docs/src/lang/en-US/vuetify/AppDrawer.json
  packages/vuetify/src/components/VItemGroup/VItem.ts
  packages/vuetify/src/components/VSlideGroup/VSlideGroup.sass
  packages/vuetify/src/components/VSlideGroup/VSlideGroup.ts
  packages/vuetify/src/components/VSlideGroup/VSlideItem.ts
  packages/vuetify/src/components/VSlideGroup/__tests__/VSlideGroup.spec.ts
  packages/vuetify/src/components/VSlideGroup/index.ts
  packages/vuetify/src/components/index.ts
  packages/vuetify/test/integration/__snapshots__/importA-la-carte.spec.js.snap
  packages/vuetify/test/integration/__snapshots__/importFull.spec.js.snap
  packages/vuetify/test/integration/__snapshots__/importLib.spec.js.snap
  packages/vuetify/test/integration/importA-la-carte.spec.js
  packages/vuetify/test/integration/importLib.spec.js
Labels: T: feature

#6267 docs(kitchen): add Slide Groups pan
  packages/kitchen/src/pan/Slide groups.vue
Labels: kitchen

#6279 test(VChipGroup): add tests
  packages/vuetify/src/components/VChipGroup/__tests__/VChipGroup.spec.ts
  packages/vuetify/src/components/VChipGroup/__tests__/__snapshots__/VChipGroup.spec.ts.snap
Labels: md2, testing

#6286 docs(kitchen): add VChipGroup pan
  packages/kitchen/src/pan/Chip Groups.vue
Labels: kitchen

#6297 fix(VChip): add margin after pill filter
  packages/vuetify/src/components/VChip/VChip.sass
Labels: T: bug

#6302 test(VChip): add more tests
  packages/vuetify/src/components/VChip/__tests__/VChip.spec.ts
Labels: testing

#6313 docs(kitchen): add theming page
  packages/kitchen/src/App.vue
  packages/kitchen/src/router.js
  packages/kitchen/src/views/Theme.vue
Labels: kitchen
