Repository vuetifyjs/vuetify, pull requests merged in 2019-06, with the labels that each got.

#7363 fix(VTextarea): recalculate height on model update
  packages/vuetify/src/components/VTextField/VTextField.ts
  packages/vuetify/src/components/VTextField/__tests__/VTextField.spec.ts
  packages/vuetify/src/components/VTextarea/VTextarea.ts
Labels: T: bug

#7346 docs(VSubheader): update examples for 2.0
  packages/docs/src/data/pages/components/Subheaders.json
  packages/docs/src/examples/subheaders/intermediate/social.vue
  packages/docs/src/examples/subheaders/playground.vue
  packages/docs/src/examples/subheaders/simple/grid.vue
  packages/docs/src/examples/subheaders/simple/inset.vue
  packages/docs/src/examples/subheaders/simple/menu.vue
  packages/docs/src/examples/subheaders/usage.vue
  packages/docs/src/lang/en/components/Subheaders.json
Labels: T: documentation

#7380 docs(VItemGroup): update examples
  packages/docs/src/data/pages/components/ItemGroups.json
  packages/docs/src/examples/item-groups/complex/post.vue
  packages/docs/src/examples/item-groups/intermediate/togglePictures.vue
  packages/docs/src/examples/item-groups/playground.vue
  packages/docs/src/examples/item-groups/simple/activeClass.vue
  packages/docs/src/examples/item-groups/simple/mandatory.vue
  packages/docs/src/examples/item-groups/simple/multiple.vue
  packages/docs/src/lang/en/components/ItemGroups.json
Labels: T: documentation

#7366 Add Korean locale.
  packages/vuetify/src/locale/index.ts
  packages/vuetify/src/locale/ko.ts
Labels: T: feature

#7370 docs(VExpansionPanel): update examples
  packages/docs/src/data/pages/components/ExpansionPanels.json
  packages/docs/src/examples/expansion-panels/complex/advanced.vue
  packages/docs/src/examples/expansion-panels/intermediate/customIcons.vue
  packages/docs/src/examples/expansion-panels/intermediate/external.vue
  packages/docs/src/examples/expansion-panels/playground.vue
  packages/docs/src/examples/expansion-panels/popout.vue
  packages/docs/src/examples/expansion-panels/simple/accordion.vue
  packages/docs/src/examples/expansion-panels/simple/disabled.vue
  packages/docs/src/examples/expansion-panels/simple/focusable.vue
  packages/docs/src/examples/expansion-panels/simple/inset.vue
  packages/docs/src/examples/expansion-panels/simple/popout.vue
  packages/docs/src/examples/expansion-panels/simple/readonly.vue
  packages/docs/src/lang/en/components/ExpansionPanels.json
Labels: T: documentation

#7397 docs(VWindow): update examples
  packages/docs/src/data/pages/components/Windows.json
  packages/docs/src/examples/windows/complex/account.vue
  packages/docs/src/examples/windows/playground.vue
  packages/docs/src/examples/windows/simple/onboarding.vue
  packages/docs/src/examples/windows/simple/reverse.vue
  packages/docs/src/examples/windows/simple/vertical.vue
  packages/docs/src/lang/en/components/Windows.json
Labels: T: documentation

#7359 docs(VCombobox): update examples
  packages/docs/src/data/pages/components/Combobox.json
  packages/docs/src/examples/combobox/intermediate/advanced.vue
  packages/docs/src/examples/combobox/intermediate/noData.vue
  packages/docs/src/examples/combobox/playground.vue
  packages/docs/src/examples/combobox/simple/comboboxMultiple.vue
Labels: T: documentation

#7389 docs(examples): load md+mdi by default
  packages/docs/src/components/doc/Codepen.vue
  packages/docs/src/examples/autocompletes/advanced.vue
  packages/docs/src/examples/autocompletes/api.vue
  packages/docs/src/examples/autocompletes/customFilter.vue
  packages/docs/src/examples/autocompletes/scopedSlots.vue
  packages/docs/src/examples/autocompletes/usage.vue
  packages/docs/src/examples/badges/simple/icon.vue
  packages/docs/src/examples/cards/complex/twitterCard.vue
  packages/docs/src/examples/carousels/simple/customIcons.vue
  packages/docs/src/examples/date-pickers/dateIcons.vue
  packages/docs/src/examples/date-pickers/monthIcons.vue
  packages/docs/src/examples/expansion-panels/intermediate/customIcons.vue
  packages/docs/src/examples/hover/transition.vue
  packages/docs/src/examples/hover/usage.vue
  packages/docs/src/examples/icons/intermediate/clickable.vue
  packages/docs/src/examples/icons/playground.vue
  packages/docs/src/examples/icons/usage.vue
  packages/docs/src/examples/paginations/icons.vue
  packages/docs/src/examples/ratings/advanced.vue
  packages/docs/src/examples/ratings/length.vue
  packages/docs/src/examples/ratings/slots.vue
  packages/docs/src/examples/selects/slots.vue
  packages/docs/src/examples/sliders/metronome.vue
  packages/docs/src/examples/tabs/icons.vue
  packages/docs/src/examples/text-fields/intermediate/iconEvents.vue
  packages/docs/src/examples/text-fields/intermediate/iconSlots.vue
  packages/docs/src/examples/textarea/signupBox.vue
  packages/docs/src/examples/timelines/alert.vue
  packages/docs/src/examples/timelines/color.vue
  packages/docs/src/examples/timelines/icons.vue
  packages/docs/src/examples/timelines/small.vue
  packages/docs/src/examples/treeview/directory.vue
  packages/docs/src/examples/treeview/fileExplorer.vue
  packages/docs/src/examples/treeview/hotspots.vue
  packages/docs/src/examples/windows/simple/onboarding.vue
  packages/docs/src/examples/windows/usage.vue
Labels: T: documentation

#7371 Docs(VFooter): update examples for 2.0
  packages/docs/src/data/pages/components/Footer.json
  packages/docs/src/examples/footer/intermediate/companyFooter.vue
  packages/docs/src/examples/footer/intermediate/indigoFooter.vue
  packages/docs/src/examples/footer/intermediate/tealFooter.vue
  packages/docs/src/examples/footer/playground.vue
  packages/docs/src/examples/footer/simple/absolute.vue
  packages/docs/src/examples/footer/simple/padless.vue
  packages/docs/src/lang/en/components/Footer.json
Labels: T: documentation

#7402 docs(VMenu): update examples
  packages/docs/src/data/pages/components/Menus.json
  packages/docs/src/examples/menus/intermediate/absoluteWithoutActivator.vue
  packages/docs/src/examples/menus/intermediate/menus.vue
  packages/docs/src/examples/menus/intermediate/popover.vue
  packages/docs/src/examples/menus/playground.vue
  packages/docs/src/examples/menus/simple/absolute.vue
  packages/docs/src/examples/menus/simple/closeOnClick.vue
  packages/docs/src/examples/menus/simple/closeOnContentClick.vue
  packages/docs/src/examples/menus/simple/customTransition.vue
  packages/docs/src/examples/menus/simple/disabled.vue
  packages/docs/src/examples/menus/simple/hover.vue
  packages/docs/src/examples/menus/simple/menuActivatorTooltip.vue
  packages/docs/src/examples/menus/simple/offsetX.vue
  packages/docs/src/examples/menus/simple/offsetY.vue
  packages/docs/src/lang/en/components/Menus.json
Labels: T: documentation

#7423 docs(VList): update examples
  packages/docs/src/data/pages/components/Lists.json
  packages/docs/src/examples/lists/intermediate/actionTitleAndSubtitle.vue
  packages/docs/src/examples/lists/intermediate/actionWithTitleAndSubtitle.vue
  packages/docs/src/examples/lists/intermediate/avatarSubheaderTitleAndAction.vue
  packages/docs/src/examples/lists/intermediate/avatarThreeLines.vue
  packages/docs/src/examples/lists/intermediate/avatarTitleAndAction.vue
  packages/docs/src/examples/lists/intermediate/cardList.vue
  packages/docs/src/examples/lists/intermediate/expansionLists.vue
  packages/docs/src/examples/lists/intermediate/iconTwoLinesAndAction.vue
  packages/docs/src/examples/lists/intermediate/nav.vue
  packages/docs/src/examples/lists/intermediate/subheadingsAndDividers.vue
  packages/docs/src/examples/lists/intermediate/titleSubtitleActionsAndActionText.vue
  packages/docs/src/examples/lists/playground.vue
  packages/docs/src/examples/lists/shaped.vue
  packages/docs/src/examples/lists/simple/dense.vue
  packages/docs/src/examples/lists/simple/disabled.vue
  packages/docs/src/examples/lists/simple/flat.vue
  packages/docs/src/examples/lists/simple/rounded.vue
  packages/docs/src/examples/lists/simple/shaped.vue
  packages/docs/src/examples/lists/usage.vue
  packages/docs/src/lang/en/components/Lists.json
Labels: T: documentation

#7357 fix(VTabs): normal tabs inside vertical tabs are vertical
  packages/vuetify/src/components/VTabs/VTabs.sass
Labels: T: bug

#7361 feat(VDatePicker): selected items count translation
  packages/vuetify/dev/index.js
  packages/vuetify/src/components/VDatePicker/VDatePicker.ts
  packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.date.spec.ts
  packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.month.spec.ts
  packages/vuetify/src/locale/af.ts
  packages/vuetify/src/locale/ar.ts
  packages/vuetify/src/locale/ca.ts
  packages/vuetify/src/locale/de.ts
  packages/vuetify/src/locale/el.ts
  packages/vuetify/src/locale/en.ts
  packages/vuetify/src/locale/es.ts
  packages/vuetify/src/locale/et.ts
  packages/vuetify/src/locale/fa.ts
  packages/vuetify/src/locale/fr.ts
  packages/vuetify/src/locale/he.ts
  packages/vuetify/src/locale/hr.ts
  packages/vuetify/src/locale/hu.ts
  packages/vuetify/src/locale/id.ts
  packages/vuetify/src/locale/it.ts
  packages/vuetify/src/locale/ja.ts
  packages/vuetify/src/locale/ko.ts
  packages/vuetify/src/locale/lv.ts
  packages/vuetify/src/locale/nl.ts
  packages/vuetify/src/locale/pl.ts
  packages/vuetify/src/locale/pt.ts
  packages/vuetify/src/locale/ro.ts
  packages/vuetify/src/locale/ru.ts
  packages/vuetify/src/locale/sl.ts
  packages/vuetify/src/locale/sr-Cyrl.ts
  packages/vuetify/src/locale/th.ts
  packages/vuetify/src/locale/tr.ts
  packages/vuetify/src/locale/uk.ts
  packages/vuetify/src/locale/zh-Hans.ts
  packages/vuetify/src/locale/zh-Hant.ts
Labels: T: bug, T: feature

#7461 docs(VInput): update examples
  packages/docs/src/data/pages/components/Inputs.json
  packages/docs/src/examples/inputs/intermediate/rules.vue
  packages/docs/src/examples/inputs/intermediate/slotEvents.vue
  packages/docs/src/examples/inputs/intermediate/slots.vue
  packages/docs/src/examples/inputs/playground.vue
  packages/docs/src/examples/inputs/simple/error.vue
  packages/docs/src/examples/inputs/simple/hint.vue
  packages/docs/src/examples/inputs/simple/loading.vue
  packages/docs/src/examples/inputs/simple/multiError.vue
  packages/docs/src/examples/inputs/simple/success.vue
  packages/docs/src/lang/en/components/Inputs.json
Labels: C: VInput, T: documentation

#7447 docs(VForm): update examples
  packages/docs/src/data/pages/components/Forms.json
  packages/docs/src/examples/forms/intermediate/veeValidate.vue
  packages/docs/src/examples/forms/intermediate/vuelidate.vue
  packages/docs/src/examples/forms/playground.vue
  packages/docs/src/examples/forms/simple/rules.vue
  packages/docs/src/examples/forms/simple/validationWithSubmitAndClear.vue
  packages/docs/src/examples/forms/validationWithSubmitAndClear.vue
Labels: C: VForm, T: documentation

#7179 [WIP] docs(VDataIterator): update examples
  packages/docs/src/data/pages/components/DataIterators.json
  packages/docs/src/examples/data-iterators/filter.vue
  packages/docs/src/lang/en/components/DataIterator.json
  packages/docs/src/lang/en/components/DataIterators.json
Labels: S: work in progress, T: documentation

#7469 Docs(VOverlay): Example updates for 2.0
  packages/docs/src/data/pages/components/Overlays.json
  packages/docs/src/examples/overlays/complex/advanced.vue
  packages/docs/src/examples/overlays/intermediate/loader.vue
  packages/docs/src/examples/overlays/playground.vue
  packages/docs/src/examples/overlays/simple/absolute.vue
  packages/docs/src/examples/overlays/simple/opacity.vue
  packages/docs/src/examples/overlays/simple/zIndex.vue
  packages/docs/src/lang/en/components/Overlays.json
Labels: T: documentation

#7479 docs(VOverFlowBtn): update examples
  packages/docs/src/data/pages/components/OverflowBtns.json
  packages/docs/src/examples/overflow-btns/playground.vue
  packages/docs/src/examples/overflow-btns/simple/counter.vue
  packages/docs/src/examples/overflow-btns/simple/disabled.vue
  packages/docs/src/examples/overflow-btns/simple/editable.vue
  packages/docs/src/examples/overflow-btns/simple/filled.vue
  packages/docs/src/examples/overflow-btns/simple/hint.vue
  packages/docs/src/examples/overflow-btns/simple/loading.vue
  packages/docs/src/examples/overflow-btns/simple/menuProps.vue
  packages/docs/src/examples/overflow-btns/simple/readonly.vue
  packages/docs/src/examples/overflow-btns/simple/segmented.vue
  packages/docs/src/examples/overflow-btns/usage.vue
  packages/docs/src/lang/en/components/OverflowBtns.json
  packages/docs/src/lang/en/meta.json
Labels: C: VOverflowBtn, T: documentation

#7348 docs(VAutocomplete): update examples
  packages/docs/src/data/pages/components/Autocompletes.json
  packages/docs/src/examples/autocompletes/complex/stateSelector.vue
  packages/docs/src/examples/autocompletes/intermediate/advanced.vue
  packages/docs/src/examples/autocompletes/intermediate/asynchronous.vue
  packages/docs/src/examples/autocompletes/intermediate/scopedSlots.vue
  packages/docs/src/examples/autocompletes/playground.vue
  packages/docs/src/examples/autocompletes/simple/api.vue
  packages/docs/src/examples/autocompletes/simple/customFilter.vue
  packages/docs/src/examples/autocompletes/usage.vue
  packages/docs/src/lang/en/components/Autocompletes.json
Labels: T: documentation

#7497 fix(install): add property to Vue object to avoid memory leak
  packages/vuetify/src/globals.d.ts
  packages/vuetify/src/install.ts
Labels: T: enhancement

#7505 [WIP]docs(VTimeline): update examples
  packages/docs/src/data/pages/components/Timelines.json
  packages/docs/src/examples/timelines/complex/advanced.vue
  packages/docs/src/examples/timelines/complex/color.vue
  packages/docs/src/examples/timelines/intermediate/alert.vue
  packages/docs/src/examples/timelines/intermediate/avatars.vue
  packages/docs/src/examples/timelines/intermediate/slot.vue
  packages/docs/src/examples/timelines/playground.vue
  packages/docs/src/examples/timelines/simple/card.vue
  packages/docs/src/examples/timelines/simple/icons.vue
  packages/docs/src/examples/timelines/simple/reverse.vue
  packages/docs/src/examples/timelines/simple/small.vue
  packages/docs/src/examples/timelines/usage.vue
  packages/docs/src/lang/en/components/Timelines.json
Labels: C: VTimeline, S: work in progress, T: documentation

#7506 docs(VSlider): update examples
  packages/docs/src/data/pages/components/Sliders.json
  packages/docs/src/examples/sliders/intermediate/metronome.vue
  packages/docs/src/examples/sliders/intermediate/validation.vue
  packages/docs/src/examples/sliders/playground.vue
  packages/docs/src/examples/sliders/simple/customColors.vue
  packages/docs/src/examples/sliders/simple/customThumb.vue
  packages/docs/src/examples/sliders/simple/disabled.vue
  packages/docs/src/examples/sliders/simple/discrete.vue
  packages/docs/src/examples/sliders/simple/editableNumericValue.vue
  packages/docs/src/examples/sliders/simple/icons.vue
  packages/docs/src/examples/sliders/simple/inverseLabel.vue
  packages/docs/src/examples/sliders/simple/minMax.vue
  packages/docs/src/examples/sliders/simple/range.vue
  packages/docs/src/examples/sliders/simple/readonly.vue
  packages/docs/src/examples/sliders/simple/step.vue
  packages/docs/src/examples/sliders/simple/thumb.vue
  packages/docs/src/examples/sliders/simple/thumbLabel.vue
  packages/docs/src/examples/sliders/simple/ticks.vue
  packages/docs/src/examples/sliders/simple/vertical.vue
  packages/docs/src/examples/sliders/usage.vue
  packages/docs/src/lang/en/components/Sliders.json
Labels: C: VRangeSlider, C: VSlider, T: documentation

#7520 docs: unify slot usage in examples
  packages/docs/src/examples/banners/playground.vue
  packages/docs/src/examples/banners/simple/two-line.vue
  packages/docs/src/examples/banners/usage.vue
  packages/docs/src/examples/data-tables/crud.vue
  packages/docs/src/examples/hover/complex/hoverList.vue
  packages/docs/src/examples/hover/complex/transition.vue
  packages/docs/src/examples/hover/playground.vue
  packages/docs/src/examples/hover/simple/disabled.vue
  packages/docs/src/examples/hover/simple/openAndCloseDelay.vue
  packages/docs/src/examples/hover/usage.vue
  packages/docs/src/examples/item-groups/complex/post.vue
  packages/docs/src/examples/item-groups/intermediate/togglePictures.vue
  packages/docs/src/examples/item-groups/playground.vue
  packages/docs/src/examples/item-groups/simple/activeClass.vue
  packages/docs/src/examples/item-groups/simple/mandatory.vue
  packages/docs/src/examples/item-groups/simple/multiple.vue
  packages/docs/src/examples/item-groups/usage.vue
  packages/docs/src/examples/list-item-groups/selectionControls.vue
  packages/docs/src/examples/lists/intermediate/actionTitleAndSubtitle.vue
  packages/docs/src/examples/lists/intermediate/subheadingsAndDividers.vue
  packages/docs/src/examples/lists/intermediate/titleSubtitleActionsAndActionText.vue
  packages/docs/src/examples/slide-groups/carousel.vue
  packages/docs/src/examples/slide-groups/centerActive.vue
  packages/docs/src/examples/slide-groups/usage.vue
  packages/docs/src/examples/sliders/intermediate/metronome.vue
  packages/docs/src/examples/sliders/simple/customThumb.vue
  packages/docs/src/examples/sliders/simple/editableNumericValue.vue
  packages/docs/src/examples/sliders/simple/minMax.vue
  packages/docs/src/examples/sparklines/fill.vue
  packages/docs/src/examples/sparklines/playground.vue
  packages/docs/src/examples/windows/simple/onboarding.vue
  packages/docs/src/examples/windows/simple/reverse.vue
  packages/docs/src/examples/windows/simple/vertical.vue
  packages/docs/src/examples/windows/usage.vue
Labels: T: documentation

#7522 docs(VPagination): Update examples for 2.0
  packages/docs/src/data/pages/components/Paginations.json
  packages/docs/src/examples/paginations/playground.vue
  packages/docs/src/examples/paginations/simple/disabled.vue
  packages/docs/src/examples/paginations/simple/icons.vue
  packages/docs/src/examples/paginations/simple/limit.vue
  packages/docs/src/examples/paginations/simple/long.vue
  packages/docs/src/examples/paginations/simple/round.vue
  packages/docs/src/lang/en/components/Paginations.json
Labels: S: work in progress, T: documentation

#7525 docs(VSelect): update examples
  packages/docs/src/data/pages/components/Selects.json
  packages/docs/src/examples/selects/intermediate/menuProps.vue
  packages/docs/src/examples/selects/intermediate/selectionAppearance.vue
  packages/docs/src/examples/selects/intermediate/slots.vue
  packages/docs/src/examples/selects/playground.vue
  packages/docs/src/examples/selects/simple/customTextAndValue.vue
  packages/docs/src/examples/selects/simple/disabled.vue
  packages/docs/src/examples/selects/simple/icons.vue
  packages/docs/src/examples/selects/simple/light.vue
  packages/docs/src/examples/selects/simple/multiple.vue
  packages/docs/src/examples/selects/simple/readonly.vue
  packages/docs/src/lang/en/components/Selects.json
Labels: C: VSelect, T: documentation

#7526 docs(VRating): update examples
  packages/docs/src/data/pages/components/Ratings.json
  packages/docs/src/examples/ratings/complex/advanced.vue
  packages/docs/src/examples/ratings/intermediate/card.vue
  packages/docs/src/examples/ratings/intermediate/increments.vue
  packages/docs/src/examples/ratings/intermediate/slots.vue
  packages/docs/src/examples/ratings/playground.vue
  packages/docs/src/examples/ratings/simple/colors.vue
  packages/docs/src/examples/ratings/simple/length.vue
  packages/docs/src/examples/ratings/simple/sizes.vue
  packages/docs/src/lang/en/components/Ratings.json
Labels: C: VRating, T: documentation

#7527 docs(VProgressCircular): Update docs for 2.0
  packages/docs/src/data/pages/components/ProgressCircular.json
  packages/docs/src/examples/paginations/playground.vue
  packages/docs/src/examples/progress-circular/playground.vue
  packages/docs/src/examples/progress-circular/simple/circularColored.vue
  packages/docs/src/examples/progress-circular/simple/circularIndeterminate.vue
  packages/docs/src/examples/progress-circular/simple/circularRotate.vue
  packages/docs/src/examples/progress-circular/simple/circularSizeAndWidth.vue
  packages/docs/src/lang/en/components/ProgressCircular.json
Labels: T: documentation

#7538 docs(VParallax): Updates for 2.0
  packages/docs/src/data/pages/components/Parallax.json
  packages/docs/src/examples/parallax/simple/content.vue
  packages/docs/src/examples/parallax/simple/customHeight.vue
Labels: T: documentation

#7515 fix(VBtnToggle): restructure styles
  packages/vuetify/src/components/VBtnToggle/VBtnToggle.sass
  packages/vuetify/src/components/VBtnToggle/VBtnToggle.ts
  packages/vuetify/src/components/VBtnToggle/_variables.sass
Labels: T: bug

#7455 feat(theme): add anchor color support
  packages/docs/src/data/pages/framework/Theme.json
  packages/docs/src/lang/en/framework/Theme.json
  packages/docs/src/snippets/js/vuetify_anchor_color.txt
  packages/vuetify/src/services/theme/__tests__/__snapshots__/theme-utils.spec.ts.snap
  packages/vuetify/src/services/theme/__tests__/__snapshots__/theme.spec.ts.snap
  packages/vuetify/src/services/theme/__tests__/theme-utils.spec.ts
  packages/vuetify/src/services/theme/utils.ts
  packages/vuetify/types/services/theme.d.ts
Labels: T: feature

#7545 docs(VStepper): update examples
  packages/docs/src/data/pages/components/Steppers.json
  packages/docs/src/examples/steppers/intermediate/dynamic.vue
  packages/docs/src/examples/steppers/playground.vue
  packages/docs/src/examples/steppers/simple/alternate-error.vue
  packages/docs/src/examples/steppers/simple/alternate-labels.vue
  packages/docs/src/examples/steppers/simple/editable.vue
  packages/docs/src/examples/steppers/simple/error.vue
  packages/docs/src/examples/steppers/simple/horizontal.vue
  packages/docs/src/examples/steppers/simple/linear.vue
  packages/docs/src/examples/steppers/simple/non-editable.vue
  packages/docs/src/examples/steppers/simple/non-linear.vue
  packages/docs/src/examples/steppers/simple/optional.vue
  packages/docs/src/examples/steppers/simple/vertical-error.vue
  packages/docs/src/examples/steppers/simple/vertical.vue
Labels: C: VStepper, T: documentation

#7548 docs(VSparkline): update examples
  packages/docs/src/data/pages/components/Sparklines.json
  packages/docs/src/examples/sparklines/intermediate/dashboard-card.vue
  packages/docs/src/examples/sparklines/intermediate/heart-rate.vue
  packages/docs/src/examples/sparklines/intermediate/sales-card.vue
  packages/docs/src/examples/sparklines/playground.vue
  packages/docs/src/examples/sparklines/simple/fill.vue
  packages/docs/src/examples/sparklines/usage.vue
Labels: C: VSparkline, S: work in progress, T: documentation

#7385 fix(VMenu/Selects): properly configure a11y
  packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts
  packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete.spec.ts
  packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete2.spec.ts
  packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete3.spec.ts
  packages/vuetify/src/components/VBtn/VBtn.ts
  packages/vuetify/src/components/VCheckbox/VSimpleCheckbox.sass
  packages/vuetify/src/components/VCheckbox/VSimpleCheckbox.ts
  packages/vuetify/src/components/VColorPicker/__tests__/__snapshots__/VColorPickerEdit.spec.ts.snap
  packages/vuetify/src/components/VCombobox/VCombobox.ts
  packages/vuetify/src/components/VCombobox/__tests__/VCombobox-multiple.spec.ts
  packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.ts
  packages/vuetify/src/components/VDataIterator/__tests__/__snapshots__/VDataFooter.spec.ts.snap
  packages/vuetify/src/components/VDataIterator/__tests__/__snapshots__/VDataIterator.spec.ts.snap
  packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
  packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTableHeader.spec.ts.snap
  packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VEditDialog.spec.ts.snap
  packages/vuetify/src/components/VDatePicker/__tests__/__snapshots__/VDatePicker.date.spec.ts.snap
  packages/vuetify/src/components/VDatePicker/__tests__/__snapshots__/VDatePickerHeader.spec.ts.snap
  packages/vuetify/src/components/VInput/VInput.ts
  packages/vuetify/src/components/VList/VList.ts
  packages/vuetify/src/components/VList/VListItem.ts
  packages/vuetify/src/components/VList/__tests__/VListItem.spec.ts
  packages/vuetify/src/components/VList/__tests__/__snapshots__/VListGroup.spec.ts.snap
  packages/vuetify/src/components/VList/__tests__/__snapshots__/VListItem.spec.ts.snap
  packages/vuetify/src/components/VMenu/VMenu.ts
  packages/vuetify/src/components/VMenu/__tests__/VMenu.spec.ts
  packages/vuetify/src/components/VMenu/__tests__/__snapshots__/VMenu.spec.ts.snap
  packages/vuetify/src/components/VOverflowBtn/__tests__/__snapshots__/VOverflowBtn.spec.ts.snap
  packages/vuetify/src/components/VSelect/VSelect.ts
  packages/vuetify/src/components/VSelect/VSelectList.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect2.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect3.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect4.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect.spec.ts.snap
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect2.spec.ts.snap
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect3.spec.ts.snap
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelectList.spec.ts.snap
  packages/vuetify/src/mixins/activatable/__tests__/__snapshots__/activatable.spec.ts.snap
  packages/vuetify/src/mixins/activatable/index.ts
  packages/vuetify/src/mixins/routable/index.ts
  packages/vuetify/test/globals.d.ts
Labels: T: bug, T: enhancement

#7518 feat(VTreeview): **dense** prop, css tweaks
  packages/docs/src/data/pages/components/Treeview.json
  packages/docs/src/examples/treeview/dense.vue
  packages/docs/src/lang/en/components/Treeview.json
  packages/kitchen/src/pan/Treeviews.vue
  packages/vuetify/src/components/VTreeview/VTreeview.sass
  packages/vuetify/src/components/VTreeview/VTreeview.ts
  packages/vuetify/src/components/VTreeview/__tests__/VTreeview.spec.ts
  packages/vuetify/src/components/VTreeview/__tests__/__snapshots__/VTreeview.spec.ts.snap
  packages/vuetify/src/components/VTreeview/_variables.scss
Labels: T: enhancement, T: feature

#7557 fix(types): give explicit type to empty arrays
  packages/vuetify/src/util/console.ts
  packages/vuetify/src/util/helpers.ts
Labels: typescript

#7546 fix(VTreeview): don't emit events on mount
  packages/vuetify/src/components/VTreeview/VTreeview.ts
Labels: T: enhancement

#7532 fix(VMenu): skip elements with 0 or NaN z-index
  packages/vuetify/src/util/helpers.ts
Labels: T: bug

#7553 docs(VProgressLinear): Update examples for 2.0
  packages/docs/src/data/pages/components/ProgressLinear.json
  packages/docs/src/examples/progress-linear/intermediate/file-loader.vue
  packages/docs/src/examples/progress-linear/intermediate/loader.vue
  packages/docs/src/examples/progress-linear/intermediate/slot.vue
  packages/docs/src/examples/progress-linear/playground.vue
  packages/docs/src/examples/progress-linear/simple/linear-buffer.vue
  packages/docs/src/examples/progress-linear/simple/linear-custom-colors.vue
  packages/docs/src/examples/progress-linear/simple/linear-determinate.vue
  packages/docs/src/examples/progress-linear/simple/linear-indeterminate.vue
  packages/docs/src/examples/progress-linear/simple/linear-query-indeterminate-and-determinate.vue
  packages/docs/src/examples/progress-linear/simple/rounded.vue
  packages/docs/src/examples/progress-linear/simple/stream.vue
  packages/docs/src/examples/progress-linear/simple/striped.vue
  packages/docs/src/lang/en/components/ProgressLinear.json
Labels: T: documentation

#7562 docs(VSlideGroup): update examples
  packages/docs/src/data/pages/components/SlideGroups.json
  packages/docs/src/examples/slide-groups/playground.vue
  packages/docs/src/examples/slide-groups/simple/active-class.vue
  packages/docs/src/examples/slide-groups/simple/carousel.vue
  packages/docs/src/examples/slide-groups/simple/center-active.vue
  packages/docs/src/examples/slide-groups/simple/custom-icons.vue
  packages/docs/src/examples/slide-groups/simple/mandatory.vue
  packages/docs/src/examples/slide-groups/simple/multiple.vue
  packages/docs/src/examples/slide-groups/usage.vue
  packages/docs/src/lang/en/components/SlideGroups.json
Labels: C: VSlideGroup, T: documentation

#7448 feat(styles): add rtl/ltr start/end spacing and alignment
  packages/docs/src/data/pages/framework/Alignment.json
  packages/docs/src/examples/spacing/playground.vue
  packages/docs/src/lang/en/framework/Alignment.json
  packages/docs/src/lang/en/framework/Spacing.json
  packages/vuetify/src/components/VApp/VApp.ts
  packages/vuetify/src/components/VApp/__tests__/__snapshots__/VApp.spec.ts.snap
  packages/vuetify/src/components/VDataTable/VDataTable.ts
  packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts
  packages/vuetify/src/components/VDataTable/VRow.ts
  packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
  packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTableHeader.spec.ts.snap
  packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VRow.spec.ts.snap
  packages/vuetify/src/styles/tools/_rtl.sass
  packages/vuetify/src/styles/utilities/_spacing.sass
  packages/vuetify/src/styles/utilities/_text.sass
  packages/vuetify/src/util/helpers.ts
Labels: T: feature

#7463 docs(VNavigationDrawer): update examples
  packages/docs/src/data/pages/components/Lists.json
  packages/docs/src/data/pages/components/NavigationDrawers.json
  packages/docs/src/examples/lists/intermediate/nested.vue
  packages/docs/src/examples/navigation-drawers/complex/bottom-drawer.vue
  packages/docs/src/examples/navigation-drawers/dark.vue
  packages/docs/src/examples/navigation-drawers/intermediate/background.vue
  packages/docs/src/examples/navigation-drawers/intermediate/combined.vue
  packages/docs/src/examples/navigation-drawers/nested.vue
  packages/docs/src/examples/navigation-drawers/persistent.vue
  packages/docs/src/examples/navigation-drawers/playground.vue
  packages/docs/src/examples/navigation-drawers/simple/colored.vue
  packages/docs/src/examples/navigation-drawers/simple/expand-on-hover.vue
  packages/docs/src/examples/navigation-drawers/simple/mini.vue
  packages/docs/src/examples/navigation-drawers/simple/permanent-floating-card.vue
  packages/docs/src/examples/navigation-drawers/simple/permanent-floating.vue
  packages/docs/src/examples/navigation-drawers/simple/right.vue
  packages/docs/src/examples/navigation-drawers/simple/temporary.vue
  packages/docs/src/lang/en/components/Lists.json
  packages/docs/src/lang/en/components/NavigationDrawers.json
Labels: C: VNavigationDrawer, S: has merge conflicts, T: documentation

#7569 docs(VSystemBar): Doc updates for 2.0
  packages/docs/src/data/pages/components/SystemBars.json
  packages/docs/src/examples/system-bars/playground.vue
  packages/docs/src/examples/system-bars/simple/color.vue
  packages/docs/src/examples/system-bars/simple/lights-out.vue
  packages/docs/src/examples/system-bars/simple/themes.vue
  packages/docs/src/examples/system-bars/simple/window.vue
  packages/docs/src/examples/system-bars/usage.vue
  packages/docs/src/lang/en/components/SystemBars.json
Labels: S: work in progress, T: documentation

#7573 docs(VSimpleTable): Update docs for 2.0
  packages/docs/src/data/pages/components/SimpleTables.json
  packages/docs/src/examples/simple-tables/playground.vue
  packages/docs/src/examples/simple-tables/simple/dark.vue
  packages/docs/src/examples/simple-tables/simple/dense.vue
  packages/docs/src/examples/simple-tables/simple/fixed-header.vue
  packages/docs/src/examples/simple-tables/simple/height.vue
Labels: S: work in progress, T: documentation

#7581 docs(VTabs): update examples
  packages/docs/src/data/pages/components/Tabs.json
  packages/docs/src/examples/tabs/centered.vue
  packages/docs/src/examples/tabs/complex/desktop.vue
  packages/docs/src/examples/tabs/complex/dynamic-height.vue
  packages/docs/src/examples/tabs/complex/overflow-to-menu.vue
  packages/docs/src/examples/tabs/external-model.vue
  packages/docs/src/examples/tabs/intermediate/align-with-title.vue
  packages/docs/src/examples/tabs/intermediate/content.vue
  packages/docs/src/examples/tabs/intermediate/dynamic.vue
  packages/docs/src/examples/tabs/intermediate/icons-and-text.vue
  packages/docs/src/examples/tabs/intermediate/right.vue
  packages/docs/src/examples/tabs/playground.vue
  packages/docs/src/examples/tabs/simple/center-active.vue
  packages/docs/src/examples/tabs/simple/fixed-tabs.vue
  packages/docs/src/examples/tabs/simple/grow.vue
  packages/docs/src/examples/tabs/simple/icons.vue
  packages/docs/src/examples/tabs/simple/pagination.vue
  packages/docs/src/examples/tabs/simple/vertical.vue
Labels: C: VTabs, S: work in progress, T: documentation

#7635 docs(VToolbar): update examples
  packages/docs/src/data/pages/components/Toolbars.json
  packages/docs/src/examples/toolbars/app-bar-menu.vue
  packages/docs/src/examples/toolbars/intermediate/contextual-action-bar.vue
  packages/docs/src/examples/toolbars/intermediate/flexible-and-card.vue
  packages/docs/src/examples/toolbars/intermediate/floating-with-search.vue
  packages/docs/src/examples/toolbars/playground.vue
  packages/docs/src/examples/toolbars/simple/background.vue
  packages/docs/src/examples/toolbars/simple/collapse.vue
  packages/docs/src/examples/toolbars/simple/column-width-with-hierarchy.vue
  packages/docs/src/examples/toolbars/simple/dense.vue
  packages/docs/src/examples/toolbars/simple/extended.vue
  packages/docs/src/examples/toolbars/simple/extension-height.vue
  packages/docs/src/examples/toolbars/simple/prominent.vue
  packages/docs/src/examples/toolbars/simple/variations.vue
  packages/docs/src/lang/en/components/Toolbars.json
Labels: C: VToolbar, T: documentation

#7616 feat(VTreeview): **rounded**/**shaped** props
  packages/docs/src/lang/en/components/Treeview.json
  packages/vuetify/src/components/VTreeview/VTreeview.sass
  packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
  packages/vuetify/src/components/VTreeview/_mixins.sass
  packages/vuetify/src/components/VTreeview/_variables.scss
Labels: T: feature

#7618 feat(VTreeview): **item-disabled** prop
  packages/docs/src/lang/en/components/Treeview.json
  packages/vuetify/src/components/VTreeview/VTreeview.sass
  packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
  packages/vuetify/src/components/VTreeview/__tests__/VTreeviewNode.spec.ts
  packages/vuetify/src/components/VTreeview/__tests__/__snapshots__/VTreeviewNode.spec.ts.snap
Labels: S: has merge conflicts, T: feature

#7617 feat(VTreeview): **color** prop
  packages/vuetify/src/components/VTreeview/VTreeview.sass
  packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
Labels: T: feature

#7619 fix(Ripple): add ripple property to denote touch enabled
  packages/vuetify/src/directives/ripple/index.ts
  packages/vuetify/src/globals.d.ts
Labels: T: bug

#7519 fix: normalize component active/hover/focus states
  packages/vuetify/src/components/VBtn/VBtn.sass
  packages/vuetify/src/components/VBtn/VBtn.ts
  packages/vuetify/src/components/VBtn/_variables.scss
  packages/vuetify/src/components/VChip/VChip.sass
  packages/vuetify/src/components/VChip/VChip.ts
  packages/vuetify/src/components/VChip/_variables.scss
  packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.sass
  packages/vuetify/src/components/VExpansionPanel/VExpansionPanelHeader.ts
  packages/vuetify/src/components/VList/VListItem.sass
  packages/vuetify/src/components/VTabs/VTabs.sass
  packages/vuetify/src/components/VTreeview/VTreeview.sass
  packages/vuetify/src/styles/settings/_dark.scss
  packages/vuetify/src/styles/settings/_light.scss
  packages/vuetify/src/styles/tools/_index.sass
  packages/vuetify/src/styles/tools/_states.sass
Labels: T: enhancement

#6475 feat(VCalendar): Events improvements
  packages/docs/src/examples/calendars/complex/events.vue
  packages/docs/src/examples/calendars/playground.vue
  packages/docs/src/examples/calendars/simple/weekly.vue
  packages/docs/src/examples/calendars/usage.vue
  packages/docs/src/examples/expansion-panels/simple/disabled.vue
  packages/docs/src/lang/en/components/Calendars.json
  packages/kitchen/src/pan/Daily Calendars.vue
  packages/kitchen/src/pan/Monthly Calendars.vue
  packages/kitchen/src/pan/Weekly Calendars.vue
  packages/vuetify/src/components/VCalendar/VCalendar.ts
  packages/vuetify/src/components/VCalendar/VCalendarDaily.sass
  packages/vuetify/src/components/VCalendar/VCalendarDaily.ts
  packages/vuetify/src/components/VCalendar/VCalendarWeekly.sass
  packages/vuetify/src/components/VCalendar/VCalendarWeekly.ts
  packages/vuetify/src/components/VCalendar/__tests__/__snapshots__/VCalendar.spec.ts.snap
  packages/vuetify/src/components/VCalendar/__tests__/__snapshots__/VCalendarDailly.spec.ts.snap
  packages/vuetify/src/components/VCalendar/_variables.scss
  packages/vuetify/src/components/VCalendar/mixins/__tests__/__snapshots__/calendar-with-events.spec.ts.snap
  packages/vuetify/src/components/VCalendar/mixins/__tests__/calendar-with-events.spec.ts
  packages/vuetify/src/components/VCalendar/mixins/calendar-base.ts
  packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.sass
  packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts
  packages/vuetify/src/components/VCalendar/util/__tests__/__snapshots__/events.spec.ts.snap
  packages/vuetify/src/components/VCalendar/util/__tests__/events.spec.ts
  packages/vuetify/src/components/VCalendar/util/events.ts
  packages/vuetify/src/components/VCalendar/util/props.ts
  packages/vuetify/src/components/VCalendar/util/timestamp.ts
  packages/vuetify/src/locale/af.ts
  packages/vuetify/src/locale/ar.ts
  packages/vuetify/src/locale/ca.ts
  packages/vuetify/src/locale/de.ts
  packages/vuetify/src/locale/el.ts
  packages/vuetify/src/locale/en.ts
  packages/vuetify/src/locale/es.ts
  packages/vuetify/src/locale/et.ts
  packages/vuetify/src/locale/fa.ts
  packages/vuetify/src/locale/fr.ts
  packages/vuetify/src/locale/he.ts
  packages/vuetify/src/locale/hr.ts
  packages/vuetify/src/locale/hu.ts
  packages/vuetify/src/locale/id.ts
  packages/vuetify/src/locale/it.ts
  packages/vuetify/src/locale/ja.ts
  packages/vuetify/src/locale/ko.ts
  packages/vuetify/src/locale/lv.ts
  packages/vuetify/src/locale/nl.ts
  packages/vuetify/src/locale/pl.ts
  packages/vuetify/src/locale/pt.ts
  packages/vuetify/src/locale/ro.ts
  packages/vuetify/src/locale/ru.ts
  packages/vuetify/src/locale/sl.ts
  packages/vuetify/src/locale/sr-Cyrl.ts
  packages/vuetify/src/locale/th.ts
  packages/vuetify/src/locale/tr.ts
  packages/vuetify/src/locale/uk.ts
  packages/vuetify/src/locale/zh-Hans.ts
  packages/vuetify/src/locale/zh-Hant.ts
Labels: T: feature

#7641 docs(VTreeview): update examples
  packages/docs/src/data/pages/components/Treeview.json
  packages/docs/src/examples/treeview/complex/directory.vue
  packages/docs/src/examples/treeview/complex/hotspots.vue
  packages/docs/src/examples/treeview/complex/human-resources.vue
  packages/docs/src/examples/treeview/intermediate/file-explorer.vue
  packages/docs/src/examples/treeview/playground.vue
  packages/docs/src/examples/treeview/simple/activatable.vue
  packages/docs/src/examples/treeview/simple/color.vue
  packages/docs/src/examples/treeview/simple/dense.vue
  packages/docs/src/examples/treeview/simple/hoverable.vue
  packages/docs/src/examples/treeview/simple/item-disabled.vue
  packages/docs/src/examples/treeview/simple/open-all.vue
  packages/docs/src/examples/treeview/simple/rounded.vue
  packages/docs/src/examples/treeview/simple/selectable.vue
  packages/docs/src/examples/treeview/simple/selected-color.vue
  packages/docs/src/examples/treeview/simple/selection-type.vue
  packages/docs/src/examples/treeview/simple/shaped.vue
  packages/docs/src/lang/en/components/Treeview.json
Labels: C: VTreeview, T: documentation

#7637 docs(SelectionControls): update examples
  packages/docs/src/data/pages/components/SelectionControls.json
  packages/docs/src/examples/selection-controls/checkboxes-inline-texfield.vue
  packages/docs/src/examples/selection-controls/intermediate/checkboxes-inline-texfield.vue
  packages/docs/src/examples/selection-controls/intermediate/label-slot.vue
  packages/docs/src/examples/selection-controls/playground-checkboxes.vue
  packages/docs/src/examples/selection-controls/playground-radios.vue
  packages/docs/src/examples/selection-controls/playground-switches.vue
  packages/docs/src/examples/selection-controls/simple/checkboxes-array.vue
  packages/docs/src/examples/selection-controls/simple/checkboxes-boolean.vue
  packages/docs/src/examples/selection-controls/simple/checkboxes-colors.vue
  packages/docs/src/examples/selection-controls/simple/checkboxes-states.vue
  packages/docs/src/examples/selection-controls/simple/radios-colors.vue
  packages/docs/src/examples/selection-controls/simple/radios-default.vue
  packages/docs/src/examples/selection-controls/simple/radios-direction.vue
  packages/docs/src/examples/selection-controls/simple/switches-array.vue
  packages/docs/src/examples/selection-controls/simple/switches-boolean.vue
  packages/docs/src/examples/selection-controls/simple/switches-colors.vue
  packages/docs/src/examples/selection-controls/simple/switches-flat.vue
  packages/docs/src/examples/selection-controls/simple/switches-states.vue
Labels: C: VCheckbox, C: VRadio, C: VSwitch, T: documentation

#7646 docs(VListItemGroup): update examples
  packages/docs/src/data/pages/components/ListItemGroups.json
  packages/docs/src/examples/list-item-groups/intermediate/selection-controls.vue
  packages/docs/src/examples/list-item-groups/playground.vue
  packages/docs/src/examples/list-item-groups/simple/active-class.vue
  packages/docs/src/examples/list-item-groups/simple/flat.vue
  packages/docs/src/examples/list-item-groups/simple/mandatory.vue
  packages/docs/src/examples/list-item-groups/simple/multiple.vue
  packages/docs/src/lang/en/components/ListItemGroups.json
Labels: C: VList, T: documentation

#7633 docs(VTextarea): Update examples for 2.0
  packages/docs/src/data/pages/components/Textarea.json
  packages/docs/src/examples/textarea/intermediate/signup-box.vue
  packages/docs/src/examples/textarea/playground.vue
  packages/docs/src/examples/textarea/simple/auto-grow.vue
  packages/docs/src/examples/textarea/simple/background-color.vue
  packages/docs/src/examples/textarea/simple/browser-autocomplete.vue
  packages/docs/src/examples/textarea/simple/clearable.vue
  packages/docs/src/examples/textarea/simple/counter.vue
  packages/docs/src/examples/textarea/simple/icon.vue
  packages/docs/src/examples/textarea/simple/no-resize.vue
  packages/docs/src/examples/textarea/simple/rows.vue
  packages/docs/src/examples/textarea/usage.vue
  packages/docs/src/lang/en/components/Textarea.json
Labels: C: VTextarea, T: documentation

#7650 docs(VDataTable): update examples for 2.0
  packages/docs/src/data/pages/components/DataTables.json
  packages/docs/src/examples/data-tables/complex/crud.vue
  packages/docs/src/examples/data-tables/complex/edit-dialog.vue
  packages/docs/src/examples/data-tables/intermediate/customize-footer.vue
  packages/docs/src/examples/data-tables/intermediate/customize-header.vue
  packages/docs/src/examples/data-tables/intermediate/customize-rows.vue
  packages/docs/src/examples/data-tables/intermediate/expand.vue
  packages/docs/src/examples/data-tables/intermediate/paginate.vue
  packages/docs/src/examples/data-tables/intermediate/server.vue
  packages/docs/src/examples/data-tables/intermediate/slots.vue
  packages/docs/src/examples/data-tables/intermediate/sort.vue
  packages/docs/src/examples/data-tables/playground.vue
  packages/docs/src/examples/data-tables/simple/dense.vue
  packages/docs/src/examples/data-tables/simple/footer-props.vue
  packages/docs/src/examples/data-tables/simple/group.vue
  packages/docs/src/examples/data-tables/simple/headerless.vue
  packages/docs/src/examples/data-tables/simple/loading.vue
  packages/docs/src/examples/data-tables/simple/multi-sort.vue
  packages/docs/src/examples/data-tables/simple/search.vue
  packages/docs/src/examples/data-tables/simple/select.vue
  packages/docs/src/examples/data-tables/simple/virtualized.vue
  packages/docs/src/lang/en/components/DataTables.json
Labels: C: VDatatable, T: documentation

#7508 Fix(docs): import directives with lowercase
  packages/docs/src/snippets/js/use_vuetify_alacarte.txt
  packages/vuetify/src/components/VChip/VChip.ts
  packages/vuetify/src/components/VExpansionPanel/VExpansionPanelHeader.ts
  packages/vuetify/src/components/VList/VListGroup.ts
  packages/vuetify/src/components/VStepper/VStepperStep.ts
  packages/vuetify/src/components/VTextField/VTextField.ts
  packages/vuetify/src/mixins/rippleable/index.ts
Labels: T: documentation

#7664 fix(VSparkline): negative values, labels being cut off
  packages/docs/src/examples/sparklines/playground.vue
  packages/docs/src/lang/en/components/Sparklines.json
  packages/vuetify/src/components/VSparkline/VSparkline.ts
  packages/vuetify/src/components/VSparkline/__tests__/__snapshots__/VSparkline.spec.ts.snap
  packages/vuetify/src/components/VSparkline/helpers/core.ts
Labels: T: bug

#7678 docs(VTextFields): add outlined desc
  packages/docs/src/data/pages/components/TextFields.json
  packages/docs/src/examples/text-fields/simple/outlined.vue
  packages/docs/src/lang/en/components/TextFields.json
Labels: T: documentation

#7651 feat(VList/Item/Group): improve a11y
  packages/api-generator/src/variables.js
  packages/vuetify/src/components/VList/VList.ts
  packages/vuetify/src/components/VList/VListGroup.sass
  packages/vuetify/src/components/VList/VListGroup.ts
  packages/vuetify/src/components/VList/VListItem.ts
  packages/vuetify/src/components/VList/VListItemGroup.ts
  packages/vuetify/src/components/VList/__tests__/VList.spec.ts
  packages/vuetify/src/components/VList/__tests__/VListGroup.spec.ts
  packages/vuetify/src/components/VList/__tests__/VListItem.spec.ts
  packages/vuetify/src/components/VList/__tests__/VListItemGroup.spec.ts
  packages/vuetify/src/components/VList/__tests__/__snapshots__/VListGroup.spec.ts.snap
  packages/vuetify/src/components/VList/__tests__/__snapshots__/VListItem.spec.ts.snap
  packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts
  packages/vuetify/src/components/VNavigationDrawer/__tests__/VNavigationDrawer.spec.ts
  packages/vuetify/src/components/VSelect/VSelectList.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelectList.spec.ts.snap
Labels: T: enhancement, a11y

#7693 docs(valert): api update for 2.0
  packages/api-generator/src/maps/v-alert.js
  packages/docs/src/lang/en/components/Alerts.json
  packages/vuetify/src/components/VAlert/VAlert.ts
Labels: C: VAlert, T: documentation

#7695 docs(api): Update vdivider maps
  packages/api-generator/src/maps/v-divider.js
  packages/docs/src/lang/en/components/Dividers.json
Labels: T: documentation

#7697 docs(VAppBar): api update for 2.0
  packages/docs/src/lang/en/components/AppBars.json
  packages/vuetify/src/components/VAppBar/VAppBar.ts
Labels: C: VToolbar, T: documentation

#7706 docs(VBanner): api update for 2.0
  packages/api-generator/src/maps/v-banner.js
  packages/docs/src/lang/en/components/Banners.json
Labels: C: VBanner, T: documentation

#7702 docs(VAvatar): api update for 2.0
  packages/docs/src/lang/en/components/Avatars.json
Labels: C: VAvatar, T: documentation

#7607 fix(VTabs): remove swiping propagation for tab touch events
  packages/vuetify/src/components/VSlideGroup/VSlideGroup.ts
  packages/vuetify/src/components/VSlideGroup/__tests__/VSlideGroup.spec.ts
  packages/vuetify/src/components/VSlider/VSlider.ts
  packages/vuetify/src/components/VTimePicker/VTimePickerClock.ts
  packages/vuetify/src/components/VWindow/VWindow.ts
  packages/vuetify/src/util/helpers.ts
Labels: T: bug

#7708 feat(VDivider): Add a11y attributes
  packages/vuetify/src/components/VDivider/VDivider.ts
  packages/vuetify/src/components/VDivider/__tests__/VDivider.spec.ts
  packages/vuetify/src/components/VDivider/__tests__/__snapshots__/VDivider.spec.ts.snap
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelectList.spec.ts.snap
Labels: C: Divider, a11y
