Repository vuetifyjs/vuetify, pull requests merged in 2019-02, with the labels that each got.

#6321 feat(VTimePicker): emit click:xxx events
  packages/api-generator/src/map.js
  packages/docs/src/examples/time-pickers/timeDialogAndMenu.vue
  packages/vuetify/src/components/VTimePicker/VTimePicker.ts
  packages/vuetify/test/unit/components/VTimePicker/VTimePicker.spec.js
Labels: T: feature

#6222 fix(VExpansionPanel): fix lazy animation
  packages/vuetify/src/components/VExpansionPanel/VExpansionPanelContent.ts
Labels: T: bug

#6179 fix(VCheckbox): Add `for` attribute on checkbox's related label
  packages/vuetify/src/components/VInput/VInput.ts
  packages/vuetify/test/unit/components/VCheckbox/VCheckbox.spec.js
Labels: T: bug, T: enhancement

#6123 refactor(util): convert to TS
  packages/vuetify/src/util/easing-patterns.js
  packages/vuetify/src/util/mask.js
  packages/vuetify/src/util/mask.ts
  packages/vuetify/src/util/rebuildFunctionalSlots.js
  packages/vuetify/src/util/rebuildFunctionalSlots.ts
Labels: T: enhancement

#6332 add apostrophes to make language clearer
  packages/docs/src/lang/en/getting-started/QuickStart.json
Labels: T: documentation

#6336 refactor(VSubheader): convert to typescript
  packages/vuetify/src/components/VSubheader/VSubheader.ts
  packages/vuetify/src/components/VSubheader/index.ts
Labels: T: enhancement

#6334 refactor(VStepper): convert to typescript
  packages/vuetify/src/components/VStepper/VStepper.ts
  packages/vuetify/src/components/VStepper/VStepperContent.ts
  packages/vuetify/src/components/VStepper/VStepperStep.ts
  packages/vuetify/src/components/VStepper/index.ts
Labels: T: enhancement

#6333 fix(VAutocomplete): use toLocaleLowerCase when filtering items
  packages/vuetify/src/components/VAutocomplete/VAutocomplete.js
  packages/vuetify/src/components/VSelect/VSelectList.js
Labels: T: bug

#6330 fix(VMenu): Update position dynamically
  packages/vuetify/src/components/VTooltip/VTooltip.js
  packages/vuetify/src/mixins/menuable.js
  packages/vuetify/test/unit/components/VMenu/VMenu.spec.js
  packages/vuetify/test/unit/components/VMenu/__snapshots__/VMenu.spec.js.snap
Labels: T: bug

#6124 feat(VTreeview): add search functionality
  packages/docs/src/data/new.json
  packages/docs/src/data/pages/components/Treeview.json
  packages/docs/src/examples/treeview/humanResources.vue
  packages/docs/src/lang/en-US/components/Treeview.json
  packages/vuetify/src/components/VTreeview/VTreeview.ts
  packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
  packages/vuetify/src/stylus/components/_treeview.styl
  packages/vuetify/src/util/helpers.ts
  packages/vuetify/test/unit/components/VTreeview/VTreeview.spec.js
  packages/vuetify/test/unit/components/VTreeview/VTreeviewNode.spec.js
  packages/vuetify/test/unit/components/VTreeview/__snapshots__/VTreeview.spec.js.snap
Labels: T: feature

#6004 refactor(stackable): convert to TS
  packages/vuetify/src/mixins/stackable.ts
Labels: T: enhancement

#6160 refactor(VDatePicker): convert to typescript
  packages/vuetify/src/components/VDatePicker/VDatePicker.ts
  packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts
  packages/vuetify/src/components/VDatePicker/VDatePickerHeader.ts
  packages/vuetify/src/components/VDatePicker/VDatePickerMonthTable.ts
  packages/vuetify/src/components/VDatePicker/VDatePickerYears.ts
  packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts
  packages/vuetify/src/components/VDatePicker/util/createNativeLocaleFormatter.ts
  packages/vuetify/src/components/VDatePicker/util/isDateAllowed.ts
  packages/vuetify/src/mixins/picker.ts
Labels: T: enhancement

#6347 fix(overlayable): make hide-overlay prop reactive
  packages/vuetify/src/mixins/overlayable.js
Labels: T: bug

#6363 feat(VTreeview): updateAll public method
  packages/docs/src/lang/en-US/components/Treeview.json
  packages/vuetify/src/components/VTreeview/VTreeview.ts
  packages/vuetify/test/unit/components/VTreeview/VTreeview.spec.js
Labels: T: feature

#6374 docs(VSparkline): add gradientDirection property to playground
  packages/docs/src/examples/sparklines/playground.vue
Labels: T: documentation

#6405 refactor(theme): use color variables
  packages/vuetify/src/styles/themes/_dark.scss
  packages/vuetify/src/styles/themes/_light.scss
Labels: T: enhancement

#6408 fix(VIcon): trim leading and trailing whitespaces in icon name
  packages/vuetify/src/components/VIcon/VIcon.ts
  packages/vuetify/test/unit/components/VIcon/VIcon.spec.js
Labels: T: bug

#6446 refactor(styles): use variables instead of hard-coded colors
  packages/vuetify/src/components/VTooltip/_variables.sass
  packages/vuetify/src/styles/base/_variables.scss
  packages/vuetify/src/stylus/components/_bottom-navs.styl
  packages/vuetify/src/stylus/components/_date-picker-table.styl
  packages/vuetify/src/stylus/components/_parallax.styl
  packages/vuetify/src/stylus/components/_pickers.styl
  packages/vuetify/src/stylus/components/_sliders.styl
  packages/vuetify/src/stylus/components/_time-picker-clock.styl
  packages/vuetify/src/stylus/components/_time-picker-title.styl
  packages/vuetify/src/stylus/elements/_code.styl
  packages/vuetify/src/stylus/settings/_theme.styl
  packages/vuetify/src/stylus/settings/_variables.styl
Labels: T: enhancement

#6370 fix(VSparkline): fix bar type
  packages/docs/src/lang/en/components/Sparklines.json
  packages/vuetify/src/components/VSparkline/VSparkline.ts
  packages/vuetify/src/components/VSparkline/helpers/core.ts
  packages/vuetify/test/unit/components/VSparkline/VSparkline.spec.js
  packages/vuetify/test/unit/components/VSparkline/__snapshots__/VSparkline.spec.js.snap
Labels: T: bug

#6433 feat(VAvatar): Update to md2
  packages/vuetify/src/components/VAvatar/VAvatar.sass
  packages/vuetify/src/components/VAvatar/VAvatar.ts
  packages/vuetify/src/components/VAvatar/__tests__/VAvatar.spec.ts
  packages/vuetify/src/components/VAvatar/__tests__/__snapshots__/VAvatar.spec.ts.snap
  packages/vuetify/test/unit/components/VAvatar/VAvatar.spec.js
Labels: T: enhancement, T: feature, md2

#6439 feat(VIcon): update to md2
  packages/api-generator/src/map.js
  packages/docs/src/lang/en/components/Icons.json
  packages/kitchen/src/pan/Icons.vue
  packages/vuetify/src/components/VIcon/VIcon.sass
  packages/vuetify/src/components/VIcon/VIcon.ts
  packages/vuetify/src/components/VIcon/__tests__/VIcon.spec.ts
  packages/vuetify/src/components/VIcon/__tests__/__snapshots__/VIcon.spec.ts.snap
  packages/vuetify/src/components/VIcon/_mixins.sass
  packages/vuetify/src/components/VIcon/_variables.sass
  packages/vuetify/src/stylus/components/_icons.styl
Labels: T: enhancement, T: feature, md2

#6445 fix(v-ripple): skip mouse events if triggered by touch
  packages/vuetify/src/directives/ripple.ts
  packages/vuetify/src/globals.d.ts
Labels: T: enhancement

#6431 fix(VAutocomplete): Update dynamically when itemText is updated
  packages/vuetify/src/components/VAutocomplete/VAutocomplete.js
  packages/vuetify/test/unit/components/VAutocomplete/VAutocomplete.spec.js
Labels: T: bug

#6412 fix(menuable): positioning when overflowing viewport
  packages/vuetify/src/components/VMenu/VMenu.js
  packages/vuetify/src/components/VTooltip/VTooltip.js
  packages/vuetify/src/mixins/menuable.js
  packages/vuetify/test/unit/components/VMenu/__snapshots__/VMenu.spec.js.snap
Labels: T: bug, T: regression

#6457 test(VCalendar): add tests
  packages/vuetify/src/components/VCalendar/mixins/mouse.ts
  packages/vuetify/src/components/VCalendar/util/props.ts
  packages/vuetify/test/unit/components/VCalendar/VCalendar.spec.js
  packages/vuetify/test/unit/components/VCalendar/VCalendarDailly.spec.js
  packages/vuetify/test/unit/components/VCalendar/__snapshots__/VCalendar.spec.js.snap
  packages/vuetify/test/unit/components/VCalendar/__snapshots__/VCalendarDailly.spec.js.snap
  packages/vuetify/test/unit/components/VCalendar/mixins/__snapshots__/calendar-base.spec.js.snap
  packages/vuetify/test/unit/components/VCalendar/mixins/__snapshots__/calendar-with-intervals.spec.js.snap
  packages/vuetify/test/unit/components/VCalendar/mixins/__snapshots__/times.spec.js.snap
  packages/vuetify/test/unit/components/VCalendar/mixins/calendar-base.spec.js
  packages/vuetify/test/unit/components/VCalendar/mixins/calendar-with-intervals.spec.js
  packages/vuetify/test/unit/components/VCalendar/mixins/mouse.spec.js
  packages/vuetify/test/unit/components/VCalendar/mixins/times.spec.js
  packages/vuetify/test/unit/components/VCalendar/util/__snapshots__/timestamp.spec.js.snap
  packages/vuetify/test/unit/components/VCalendar/util/props.spec.js
  packages/vuetify/test/unit/components/VCalendar/util/timestamp.spec.js
Labels: T: enhancement, testing

#6097 fix(DataIterable): Update selection when items change.
  packages/vuetify/src/mixins/data-iterable.js
  packages/vuetify/test/unit/mixins/data-iterable.spec.js
Labels: T: bug, T: enhancement

#6463 docs(meet the team): add me to team
  packages/docs/src/components/getting-started/Team.vue
Labels: T: documentation

#6511 docs(kitchen): add pans for VCalendar
  packages/kitchen/src/pan/Daily Calendars.vue
  packages/kitchen/src/pan/Monthly Calendars.vue
  packages/kitchen/src/pan/Weekly Calendars.vue
Labels: kitchen

#6519 docs(kitchen): add sub-header component
  packages/kitchen/src/components/CoreTitle.vue
  packages/kitchen/src/components/SubHeader.vue
  packages/kitchen/src/main.js
Labels: kitchen

#6522 Create Treeview.json
  packages/docs/src/lang/ru-RU/components/Treeview.json
Labels: T: documentation

#6373 fix(VSpeedDial): fixed transition animation
  packages/vuetify/src/components/VSpeedDial/VSpeedDial.js
  packages/vuetify/src/stylus/components/_speed-dial.styl
  packages/vuetify/test/unit/components/VSpeedDial/VSpeedDial.spec.js
Labels: T: bug

#6524 test(VCalendar): fix tests
  packages/vuetify/test/unit/components/VCalendar/VCalendar.spec.js
  packages/vuetify/test/unit/components/VCalendar/__snapshots__/VCalendar.spec.js.snap
Labels: T: bug, T: regression

#6543 docs(VCard): use text defined in data() function
  packages/docs/src/examples/cards/usage.vue
Labels: T: documentation

#6554 ci(Travis): use latest Node.js
  .travis.yml
Labels: T: enhancement, testing

#6557 refactor(services): minor refactor + code style
  packages/vuetify/src/services/goto/__tests__/easing-patterns.spec.ts
  packages/vuetify/src/services/goto/easing-patterns.ts
  packages/vuetify/src/services/icons/index.ts
  packages/vuetify/src/services/icons/presets/index.ts
  packages/vuetify/src/services/theme/index.ts
Labels: T: enhancement

#6577 refactor(elements): convert to SASS
  packages/vuetify/src/styles/elements/_blockquote.sass
  packages/vuetify/src/styles/elements/_code.sass
  packages/vuetify/src/styles/elements/_global.sass
  packages/vuetify/src/styles/elements/_headings.sass
  packages/vuetify/src/styles/elements/_lists.sass
  packages/vuetify/src/styles/elements/_typography.sass
  packages/vuetify/src/styles/styles.sass
  packages/vuetify/src/stylus/app.styl
  packages/vuetify/src/stylus/elements/_blockquote.styl
  packages/vuetify/src/stylus/elements/_headings.styl
  packages/vuetify/src/stylus/elements/_lists.styl
  packages/vuetify/src/stylus/elements/_typography.styl
Labels: T: enhancement

#6582 feat(VDivider): update to md2
  packages/vuetify/src/components/VDivider/VDivider.sass
  packages/vuetify/src/components/VDivider/VDivider.ts
  packages/vuetify/src/components/VDivider/__tests__/VDivider.spec.ts
  packages/vuetify/src/components/VDivider/__tests__/__snapshots__/VDivider.spec.ts.snap
  packages/vuetify/src/components/VDivider/_mixins.sass
  packages/vuetify/test/unit/components/VDivider/VDivider.spec.js
Labels: T: feature, md2

#6578 refactor(SASS): group styles
  packages/vuetify/src/styles/base/_index.sass
  packages/vuetify/src/styles/components/_index.sass
  packages/vuetify/src/styles/helpers/_index.sass
  packages/vuetify/src/styles/styles.sass
  packages/vuetify/src/styles/themes/_index.sass
Labels: T: enhancement

#6584 feat(VLabel): update to md2
  packages/vuetify/src/components/VLabel/VLabel.sass
  packages/vuetify/src/components/VLabel/VLabel.ts
  packages/vuetify/src/components/VLabel/__tests__/VLabel.spec.ts
  packages/vuetify/src/stylus/components/_labels.styl
  packages/vuetify/test/unit/components/VLabel/VLabel.spec.js
Labels: T: enhancement, md2

#6585 feat(VMessages): update to md2
  packages/vuetify/src/components/VMessages/VMessages.sass
  packages/vuetify/src/components/VMessages/VMessages.ts
  packages/vuetify/src/components/VMessages/__tests__/VMessages.spec.ts
  packages/vuetify/src/components/VMessages/__tests__/__snapshots__/VMessages.spec.ts.snap
  packages/vuetify/test/unit/components/VMessages/VMessages.spec.js
  packages/vuetify/test/unit/components/VMessages/__snapshots__/VMessages.spec.js.snap
Labels: T: enhancement, md2

#6539 docs(kitchen): add anchors
  packages/kitchen/src/components/CoreTitle.vue
  packages/kitchen/src/plugins/vuetify.js
  packages/kitchen/src/router.js
Labels: kitchen

#6514 feat(VBadge): update to md2
  packages/vuetify/src/components/VBadge/VBadge.sass
  packages/vuetify/src/components/VBadge/VBadge.ts
  packages/vuetify/src/components/VBadge/__tests__/VBadge.spec.ts
  packages/vuetify/src/components/VBadge/__tests__/__snapshots__/VBadge.spec.ts.snap
  packages/vuetify/src/components/VBadge/_variables.sass
Labels: T: feature, md2

#6520 feat(VBanner): add new component
  packages/docs/src/data/drawerItems.json
  packages/docs/src/data/pages/components/Banners.json
  packages/docs/src/examples/banners/icon-event.vue
  packages/docs/src/examples/banners/icon-slot.vue
  packages/docs/src/examples/banners/scoped-slots.vue
  packages/docs/src/examples/banners/single-line.vue
  packages/docs/src/examples/banners/two-line.vue
  packages/docs/src/examples/banners/usage.vue
  packages/docs/src/lang/en/components/Banners.json
  packages/docs/src/lang/en/meta.json
  packages/docs/src/lang/en/vuetify/AppDrawer.json
  packages/kitchen/src/pan/Banners.vue
  packages/vuetify/src/components/VBanner/VBanner.sass
  packages/vuetify/src/components/VBanner/VBanner.ts
  packages/vuetify/src/components/VBanner/__tests__/VBanner.spec.ts
  packages/vuetify/src/components/VBanner/__tests__/__snapshots__/VBanner.spec.ts.snap
  packages/vuetify/src/components/VBanner/_mixins.sass
  packages/vuetify/src/components/VBanner/_variables.scss
  packages/vuetify/src/components/VBanner/index.ts
  packages/vuetify/src/components/index.ts
Labels: T: feature, md2

#6320 feat(VDatePicker): use $vuetify.lang.current
  packages/vuetify/src/components/VDatePicker/VDatePicker.ts
  packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts
  packages/vuetify/src/components/VDatePicker/VDatePickerHeader.ts
  packages/vuetify/src/components/VDatePicker/VDatePickerMonthTable.ts
  packages/vuetify/src/components/VDatePicker/VDatePickerYears.ts
  packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts
  packages/vuetify/src/mixins/localable.ts
Labels: T: feature, semver: major

#6587 refactor(VAlert): split out variables
  packages/vuetify/src/components/VAlert/VAlert.sass
  packages/vuetify/src/components/VAlert/_variables.scss
Labels: T: enhancement, md2

#6601 refactor(VDivider): split out variables
  packages/vuetify/src/components/VDivider/VDivider.sass
  packages/vuetify/src/components/VDivider/_variables.sass
Labels: T: enhancement

#6597 refactor(elements): split out variables
  packages/vuetify/src/styles/base/_variables.scss
  packages/vuetify/src/styles/elements/_blockquote.sass
  packages/vuetify/src/styles/elements/_code.sass
  packages/vuetify/src/styles/helpers/_bootable.sass
Labels: T: enhancement

#6596 refactor(VBtn): split out variables
  packages/vuetify/src/components/VBtn/VBtn.sass
  packages/vuetify/src/components/VBtn/_variables.scss
Labels: T: enhancement, md2

#6600 refactor(VSlideGroup): split out variables
  packages/vuetify/src/components/VSlideGroup/VSlideGroup.sass
  packages/vuetify/src/components/VSlideGroup/_variables.sass
Labels: T: enhancement

#6588 refactor(VTextField): convert to ts
  packages/vuetify/src/components/VTextField/VTextField.ts
  packages/vuetify/src/components/VTextField/index.js
  packages/vuetify/src/components/VTextField/index.ts
  packages/vuetify/src/mixins/maskable.js
  packages/vuetify/test/unit/components/VOverflowBtn/__snapshots__/VOverflowBtn.spec.js.snap
  packages/vuetify/test/unit/components/VSelect/__snapshots__/VSelect.spec.js.snap
  packages/vuetify/test/unit/components/VSelect/__snapshots__/VSelect2.spec.js.snap
  packages/vuetify/test/unit/mixins/maskable.spec.js
Labels: T: enhancement

#6525 refactor(kitchen): use new slot syntax
  packages/kitchen/src/pan/Alerts.vue
  packages/kitchen/src/pan/Avatars.vue
  packages/kitchen/src/pan/Badges.vue
  packages/kitchen/src/pan/Hover.vue
  packages/kitchen/src/pan/Images.vue
  packages/kitchen/src/pan/Item Groups.vue
  packages/kitchen/src/pan/Ratings.vue
  packages/kitchen/src/pan/Slide groups.vue
  packages/kitchen/src/pan/Text fields.vue
  packages/kitchen/src/pan/Time pickers.vue
  packages/kitchen/src/pan/Timelines.vue
  packages/kitchen/src/pan/Toolbars.vue
  packages/kitchen/src/pan/Tooltips.vue
  packages/kitchen/src/pan/Treeviews.vue
  packages/kitchen/src/pan/Windows.vue
Labels: T: enhancement, kitchen

#6614 refactor(VBtnToggle): split out variables
  packages/vuetify/src/components/VBtnToggle/VBtnToggle.sass
  packages/vuetify/src/components/VBtnToggle/_variables.sass
Labels: T: enhancement, md2

#6622 fix(VTooltip): min width is not applied
  packages/vuetify/src/components/VTooltip/VTooltip.js
  packages/vuetify/test/unit/components/VTooltip/VTooltip.spec.js
  packages/vuetify/test/unit/components/VTooltip/__snapshots__/VTooltip.spec.js.snap
Labels: T: bug

#6631 feat(VItemGroup): update to md2
  packages/vuetify/src/components/VItemGroup/VItemGroup.sass
  packages/vuetify/src/components/VItemGroup/VItemGroup.ts
  packages/vuetify/src/components/VItemGroup/__tests__/VItem.spec.ts
  packages/vuetify/src/components/VItemGroup/__tests__/VItemGroup.spec.ts
  packages/vuetify/src/components/VItemGroup/__tests__/__snapshots__/VItem.spec.ts.snap
  packages/vuetify/src/components/VItemGroup/_variables.sass
  packages/vuetify/src/stylus/components/_item-group.styl
Labels: T: feature, md2

#6618 docs: add md spec links
  packages/docs/src/components/core/Page.vue
  packages/docs/src/data/pages/components/Autocompletes.json
  packages/docs/src/data/pages/components/Banners.json
  packages/docs/src/data/pages/components/BottomNavigation.json
  packages/docs/src/data/pages/components/BottomSheets.json
  packages/docs/src/data/pages/components/ButtonGroups.json
  packages/docs/src/data/pages/components/Buttons.json
  packages/docs/src/data/pages/components/Cards.json
  packages/docs/src/data/pages/components/ChipGroups.json
  packages/docs/src/data/pages/components/Chips.json
  packages/docs/src/data/pages/components/DataTables.json
  packages/docs/src/data/pages/components/Dialogs.json
  packages/docs/src/data/pages/components/Dividers.json
  packages/docs/src/data/pages/components/ExpansionPanels.json
  packages/docs/src/data/pages/components/FloatingActionButtons.json
  packages/docs/src/data/pages/components/Icons.json
  packages/docs/src/data/pages/components/Images.json
  packages/docs/src/data/pages/components/Lists.json
  packages/docs/src/data/pages/components/Menus.json
  packages/docs/src/data/pages/components/NavigationDrawers.json
  packages/docs/src/data/pages/components/OverflowBtns.json
  packages/docs/src/data/pages/components/Progress.json
  packages/docs/src/data/pages/components/SelectionControls.json
  packages/docs/src/data/pages/components/Sliders.json
  packages/docs/src/data/pages/components/Snackbars.json
  packages/docs/src/data/pages/components/Steppers.json
  packages/docs/src/data/pages/components/Subheaders.json
  packages/docs/src/data/pages/components/Tabs.json
  packages/docs/src/data/pages/components/TextFields.json
  packages/docs/src/data/pages/components/Textarea.json
  packages/docs/src/data/pages/components/Toolbars.json
  packages/docs/src/data/pages/components/Tooltips.json
  packages/docs/src/data/pages/framework/AspectRatios.json
  packages/docs/src/data/pages/framework/Breakpoints.json
  packages/docs/src/data/pages/framework/Colors.json
  packages/docs/src/data/pages/framework/Elevation.json
  packages/docs/src/data/pages/framework/Grid.json
  packages/docs/src/data/pages/framework/GridLists.json
  packages/docs/src/data/pages/framework/Icons.json
  packages/docs/src/data/pages/framework/Internationalization.json
  packages/docs/src/data/pages/framework/Spacing.json
  packages/docs/src/data/pages/framework/Theme.json
  packages/docs/src/data/pages/framework/Transitions.json
  packages/docs/src/data/pages/framework/Typography.json
Labels: T: documentation

#6595 docs(sass): add guide for customizing variables
  packages/docs/src/data/pages/framework/Theme.json
  packages/docs/src/lang/en/framework/Theme.json
  packages/docs/src/pages/documentation/Page.vue
  packages/docs/src/snippets/bash/yarn_install_sass.txt
  packages/docs/src/snippets/js/import_vuetify_css.txt
  packages/docs/src/snippets/js/import_vuetify_sass.txt
  packages/docs/src/snippets/js/webpack_sass.txt
  packages/docs/src/snippets/js/webpack_stylus.txt
  packages/docs/src/snippets/sass/changing_variables.txt
  packages/docs/src/snippets/sass/import_vuetify_css.txt
  packages/docs/src/snippets/stylus/changing_variables.txt
Labels: T: documentation

#6612 refactor(VChipGroup): split out variables
  packages/vuetify/src/components/VChipGroup/VChipGroup.sass
  packages/vuetify/src/components/VChipGroup/_variables.sass
Labels: md2

#6603 refactor(VChip): split out variables
  packages/vuetify/src/components/VChip/VChip.sass
  packages/vuetify/src/components/VChip/_variables.scss
Labels: T: enhancement
