Repository vuetifyjs/vuetify, pull requests merged in 2019-10, with the labels that each got.

#9163 fix(VDialog/VMenu/VTooltip): hide wrapper element when not attached
  packages/vuetify/src/components/VDialog/VDialog.sass
  packages/vuetify/src/components/VDialog/VDialog.ts
  packages/vuetify/src/components/VMenu/VMenu.sass
  packages/vuetify/src/components/VMenu/VMenu.ts
  packages/vuetify/src/components/VTooltip/VTooltip.sass
  packages/vuetify/src/components/VTooltip/VTooltip.ts
Labels: C: VDialog, C: VMenu, C: VTooltip, T: bug

#9200 docs(new-usage): merge new-playground into usage
  packages/docs/src/components/doc/PlaygroundNew.vue
  packages/docs/src/components/doc/Section.vue
  packages/docs/src/components/doc/UsageExample.vue
  packages/docs/src/components/doc/UsageNew.vue
  packages/docs/src/data/pages/components/Alerts.json
  packages/docs/src/data/pages/components/Avatars.json
  packages/docs/src/data/pages/components/Buttons.json
  packages/docs/src/examples/alerts/usage.vue
  packages/docs/src/examples/avatars/usage.vue
  packages/docs/src/examples/buttons/usage.vue
  packages/docs/src/lang/en/components/Alerts.json
  packages/docs/src/lang/en/components/Avatars.json
  packages/docs/src/lang/en/components/Buttons.json
  packages/docs/src/lang/eo-UY/components/Alerts.json
  packages/docs/src/lang/eo-UY/components/Avatars.json
  packages/docs/src/lang/eo-UY/components/Buttons.json
  packages/docs/src/usages/alerts.vue
  packages/docs/src/usages/avatars.vue
  packages/docs/src/usages/buttons.vue
  packages/docs/src/util/helpers.js
Labels: T: documentation

#8421 fix(VProgressLinear): invalid background position in RTL mode
  packages/vuetify/src/components/VCard/__tests__/VCard.spec.ts
  packages/vuetify/src/components/VProgressLinear/VProgressLinear.ts
  packages/vuetify/src/components/VProgressLinear/__tests__/VProgressLinear.spec.ts
  packages/vuetify/src/components/VProgressLinear/__tests__/__snapshots__/VProgressLinear.spec.ts.snap
  packages/vuetify/src/components/VTextField/__tests__/VTextField.spec.ts
Labels: T: bug, rtl

#9273 fix(vautocomplete): make focus and blur events fire
  packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts
Labels: C: VAutocomplete, C: VCombobox, T: bug, T: regression

#8613 fix(VSparkline): add label color for light/dark theme (fix #8557)
  packages/vuetify/src/components/VSparkline/VSparkline.sass
  packages/vuetify/src/components/VSparkline/VSparkline.ts
  packages/vuetify/src/components/VSparkline/__tests__/__snapshots__/VSparkline.spec.ts.snap
Labels: T: bug

#9227 fix(vexpansionpanel): nested expansion-panels get active class of parent
  packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.sass
Labels: C: VExpansionPanel, T: bug

#9332 fix(vcarousel delimiter aria-label): a11y carousel delimiters
  packages/vuetify/src/components/VCarousel/VCarousel.ts
  packages/vuetify/src/components/VCarousel/__tests__/VCarousel.spec.ts
  packages/vuetify/src/locale/af.ts
  packages/vuetify/src/locale/ar.ts
  packages/vuetify/src/locale/ca.ts
  packages/vuetify/src/locale/cs.ts
  packages/vuetify/src/locale/de.ts
  packages/vuetify/src/locale/el.ts
  packages/vuetify/src/locale/en.ts
  packages/vuetify/src/locale/es.ts
  packages/vuetify/src/locale/et.ts
  packages/vuetify/src/locale/fa.ts
  packages/vuetify/src/locale/fr.ts
  packages/vuetify/src/locale/he.ts
  packages/vuetify/src/locale/hr.ts
  packages/vuetify/src/locale/hu.ts
  packages/vuetify/src/locale/id.ts
  packages/vuetify/src/locale/it.ts
  packages/vuetify/src/locale/ja.ts
  packages/vuetify/src/locale/ko.ts
  packages/vuetify/src/locale/lt.ts
  packages/vuetify/src/locale/lv.ts
  packages/vuetify/src/locale/nl.ts
  packages/vuetify/src/locale/no.ts
  packages/vuetify/src/locale/pl.ts
  packages/vuetify/src/locale/pt.ts
  packages/vuetify/src/locale/ro.ts
  packages/vuetify/src/locale/ru.ts
  packages/vuetify/src/locale/sl.ts
  packages/vuetify/src/locale/sr-Cyrl.ts
  packages/vuetify/src/locale/sv.ts
  packages/vuetify/src/locale/th.ts
  packages/vuetify/src/locale/tr.ts
  packages/vuetify/src/locale/uk.ts
  packages/vuetify/src/locale/zh-Hans.ts
  packages/vuetify/src/locale/zh-Hant.ts
Labels: T: bug

#9351 fix(VRating): pass in x-small icon size
  packages/vuetify/src/components/VRating/VRating.ts
Labels: C: VRating, T: bug

#9236 fix(VDataTable): Add toggle and remove functions to group header slots
  packages/api-generator/src/maps/v-data-table.js
  packages/vuetify/src/components/VDataTable/VDataTable.ts
Labels: C: VDataTable, T: bug

#9268 fix(theme): use new vue-meta api
  packages/vuetify/src/services/theme/__tests__/theme.spec.ts
  packages/vuetify/src/services/theme/index.ts
Labels: pending team review

#9427 Add Sean to meet the team page
  packages/docs/src/components/getting-started/Team.vue
Labels: T: documentation

#9440 chore: auto generate web-types.json to provide autocomplete for JetBrains IDEs
  packages/api-generator/src/index.js
  packages/vuetify/build/build-json.js
  packages/vuetify/package.json
Labels: T: enhancement

#9431 fix(VSwitch/VCheckbox): color not applied if value is 0/false
  packages/vuetify/src/components/VCheckbox/VCheckbox.ts
  packages/vuetify/src/components/VSwitch/VSwitch.ts
Labels: C: VCheckbox, C: VSwitch, T: bug

#7805 fix(VDataTable): adjust filter & sort functions to use Intl.Collator
  packages/vuetify/src/util/helpers.ts
Labels: C: VDataTable, T: bug

#9215 feature(datatable): hide sort by select on mobile if not needed
  packages/vuetify/src/components/VDataTable/VDataTableHeaderMobile.ts
Labels: C: VDataTable
