Repository vuetifyjs/vuetify, pull requests merged in 2019-09, with the labels that each got.

#7878 fix(types): avoid importing from src, update for v2
  packages/docs/src/snippets/ts/breakpoint_service_structure.txt
  packages/vuetify/src/components/VApp/VApp.ts
  packages/vuetify/src/components/VDatePicker/VDatePicker.ts
  packages/vuetify/src/directives/index.ts
  packages/vuetify/src/services/application/index.ts
  packages/vuetify/src/services/breakpoint/index.ts
  packages/vuetify/src/services/goto/index.ts
  packages/vuetify/src/services/icons/index.ts
  packages/vuetify/src/services/lang/index.ts
  packages/vuetify/src/services/theme/index.ts
  packages/vuetify/types/alacarte.d.ts
  packages/vuetify/types/index.d.ts
  packages/vuetify/types/lib.d.ts
  packages/vuetify/types/presets/index.d.ts
  packages/vuetify/types/services/application.d.ts
  packages/vuetify/types/services/breakpoint.d.ts
  packages/vuetify/types/services/goto.d.ts
  packages/vuetify/types/services/icons.d.ts
  packages/vuetify/types/services/lang.d.ts
  packages/vuetify/types/services/theme.d.ts
  packages/vuetify/types/test/global.ts
  packages/vuetify/types/test/lib.ts
  packages/vuetify/types/test/presets.ts
Labels: T: bug, typescript

#7759 feat(VAutocomplete): make items copy-pasteable
  packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts
  packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete3.spec.ts
  packages/vuetify/src/components/VCombobox/VCombobox.ts
  packages/vuetify/src/components/VCombobox/__tests__/VCombobox-multiple.spec.ts
Labels: C: VAutocomplete, T: feature, pending team review

#8835 docs(grids): make usage example responsive
  packages/docs/src/examples/grids/usage.vue
Labels: C: VGrid, T: documentation

#8922 fix(Theme): provide backward compatibility for vue-meta@1
  packages/vuetify/src/services/theme/__tests__/__snapshots__/theme.spec.ts.snap
  packages/vuetify/src/services/theme/__tests__/theme.spec.ts
  packages/vuetify/src/services/theme/index.ts
Labels: Service: Theme

#8976 docs(SelectionControls): api updates
  packages/api-generator/src/maps/v-radio.js
  packages/docs/src/data/pages/components/SelectionControls.json
  packages/docs/src/examples/selection-controls/intermediate/checkboxes-inline-textfield.vue
  packages/docs/src/lang/en/components/SelectionControls.json
  packages/vuetify/src/components/VCheckbox/VCheckbox.ts
  packages/vuetify/src/components/VRadioGroup/VRadio.ts
  packages/vuetify/src/components/VSelect/VSelect.ts
Labels: T: documentation

#8584 fix(VAppBar): fix v-model control when using elevate-on-scroll
  packages/vuetify/src/components/VAppBar/VAppBar.ts
  packages/vuetify/src/components/VAppBar/__tests__/VAppBar.spec.ts
Labels: C: VAppBar, T: bug

#9022 fix(locale): add missing Italian translations
  packages/vuetify/src/locale/it.ts
Labels: Service: Lang, T: enhancement

#9003 docs(VGrid): add docs for grow and shrink classes
  packages/docs/src/data/pages/styles/Flex.json
  packages/docs/src/examples/flex/grow-shrink.vue
  packages/docs/src/lang/en/styles/Flex.json
Labels: C: VGrid, T: documentation

#8329 docs: Add releases and migrations page
  MIGRATION.md
  packages/docs/src/components/getting-started/ReleasesAndMigrations.vue
  packages/docs/src/data/drawerItems.json
  packages/docs/src/data/pages/getting-started/ReleasesAndMigrations.json
  packages/docs/src/lang/en/getting-started/releasesAndMigrations.json
  packages/docs/src/lang/en/vuetify/AppDrawer.json
Labels: T: documentation

#8810 feat(VInput): add dense
  packages/docs/src/data/pages/components/Autocompletes.json
  packages/docs/src/data/pages/components/Combobox.json
  packages/docs/src/data/pages/components/FileInputs.json
  packages/docs/src/data/pages/components/OverflowBtns.json
  packages/docs/src/data/pages/components/Selects.json
  packages/docs/src/data/pages/components/TextFields.json
  packages/docs/src/examples/autocompletes/simple/dense.vue
  packages/docs/src/examples/combobox/simple/dense.vue
  packages/docs/src/examples/file-inputs/simple/dense.vue
  packages/docs/src/examples/overflow-btns/simple/dense.vue
  packages/docs/src/examples/selects/simple/dense.vue
  packages/docs/src/examples/text-fields/playground.vue
  packages/docs/src/examples/text-fields/simple/dense.vue
  packages/docs/src/lang/en/components/Autocompletes.json
  packages/docs/src/lang/en/components/Combobox.json
  packages/docs/src/lang/en/components/FileInputs.json
  packages/docs/src/lang/en/components/Inputs.json
  packages/docs/src/lang/en/components/OverflowBtns.json
  packages/docs/src/lang/en/components/Selects.json
  packages/docs/src/lang/en/components/TextFields.json
  packages/vuetify/src/components/VFileInput/VFileInput.sass
  packages/vuetify/src/components/VInput/VInput.ts
  packages/vuetify/src/components/VOverflowBtn/VOverflowBtn.sass
  packages/vuetify/src/components/VSelect/VSelect.sass
  packages/vuetify/src/components/VSelect/VSelect.ts
  packages/vuetify/src/components/VTextField/VTextField.sass
  packages/vuetify/src/components/VTextField/VTextField.ts
  packages/vuetify/src/components/VTextField/_mixins.sass
Labels: T: feature

#8822 fix(perf): avoid useless re-render on parent update
  packages/vuetify/src/components/VAlert/__tests__/VAlert.spec.ts
  packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete.spec.ts
  packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete2.spec.ts
  packages/vuetify/src/components/VCalendar/__tests__/VCalendar.spec.ts
  packages/vuetify/src/components/VCard/__tests__/VCard.spec.ts
  packages/vuetify/src/components/VCheckbox/VCheckbox.ts
  packages/vuetify/src/components/VChip/__tests__/VChip.spec.ts
  packages/vuetify/src/components/VColorPicker/__tests__/VColorPickerEdit.spec.ts
  packages/vuetify/src/components/VCombobox/__tests__/VCombobox-multiple.spec.ts
  packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.ts
  packages/vuetify/src/components/VDataIterator/__tests__/VDataFooter.spec.ts
  packages/vuetify/src/components/VDataTable/__tests__/VDataTableHeader.spec.ts
  packages/vuetify/src/components/VDataTable/__tests__/VEditDialog.spec.ts
  packages/vuetify/src/components/VFileInput/__tests__/VFileInput.spec.ts
  packages/vuetify/src/components/VForm/VForm.ts
  packages/vuetify/src/components/VIcon/VIcon.ts
  packages/vuetify/src/components/VIcon/__tests__/VIcon.spec.ts
  packages/vuetify/src/components/VInput/VInput.ts
  packages/vuetify/src/components/VInput/__tests__/VInput.spec.ts
  packages/vuetify/src/components/VList/VList.ts
  packages/vuetify/src/components/VList/VListGroup.ts
  packages/vuetify/src/components/VMenu/__tests__/VMenu.spec.ts
  packages/vuetify/src/components/VMenu/__tests__/__snapshots__/VMenu.spec.ts.snap
  packages/vuetify/src/components/VOverflowBtn/__tests__/VOverflowBtn.spec.ts
  packages/vuetify/src/components/VRadioGroup/VRadio.ts
  packages/vuetify/src/components/VRating/__tests__/VRating.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect2.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect3.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect4.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelectList.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect.spec.ts.snap
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect2.spec.ts.snap
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect3.spec.ts.snap
  packages/vuetify/src/components/VSheet/VSheet.ts
  packages/vuetify/src/components/VSlider/__tests__/VSlider.spec.ts
  packages/vuetify/src/components/VSwitch/VSwitch.ts
  packages/vuetify/src/components/VTextField/VTextField.ts
  packages/vuetify/src/components/VTextField/__tests__/VTextField.spec.ts
  packages/vuetify/src/components/VTextField/__tests__/__snapshots__/VTextField.spec.ts.snap
  packages/vuetify/src/components/VToolbar/__tests__/VToolbar.spec.ts
  packages/vuetify/src/components/VTreeview/__tests__/VTreeview.spec.ts
  packages/vuetify/src/components/VTreeview/__tests__/VTreeviewNode.spec.ts
  packages/vuetify/src/mixins/binds-attrs/index.ts
Labels: P: critical, T: bug, help wanted, performance

#9037 feat(VSkeletonLoader): add new component
  packages/api-generator/src/maps/v-skeleton-loader.js
  packages/docs/src/components/doc/ApiItem.vue
  packages/docs/src/data/drawerItems.json
  packages/docs/src/data/pages/components/SkeletonLoaders.json
  packages/docs/src/examples/skeleton-loaders/complex/boilerplate.vue
  packages/docs/src/examples/skeleton-loaders/intermediate/implementation.vue
  packages/docs/src/examples/skeleton-loaders/playground.vue
  packages/docs/src/examples/skeleton-loaders/usage.vue
  packages/docs/src/lang/en/components/SkeletonLoaders.json
  packages/docs/src/lang/en/meta.json
  packages/docs/src/lang/en/vuetify/AppDrawer.json
  packages/docs/src/public/sitemap.xml
  packages/vuetify/src/components/VSkeletonLoader/VSkeletonLoader.sass
  packages/vuetify/src/components/VSkeletonLoader/VSkeletonLoader.ts
  packages/vuetify/src/components/VSkeletonLoader/__tests__/VSkeletonLoader.spec.ts
  packages/vuetify/src/components/VSkeletonLoader/__tests__/__snapshots__/VSkeletonLoader.spec.ts.snap
  packages/vuetify/src/components/VSkeletonLoader/_variables.scss
  packages/vuetify/src/components/VSkeletonLoader/index.ts
  packages/vuetify/src/components/index.ts
  packages/vuetify/src/styles/settings/_dark.scss
  packages/vuetify/src/styles/settings/_light.scss
Labels: C: New Component, T: feature

#9071 feat(VIntersect): add new directive
  packages/api-generator/src/index.js
  packages/api-generator/src/maps/v-intersect.js
  packages/docs/src/components/doc/ApiItem.vue
  packages/docs/src/data/drawerItems.json
  packages/docs/src/data/pages/directives/Intersect.json
  packages/docs/src/examples/intersect/usage.vue
  packages/docs/src/lang/en/directives/Intersect.json
  packages/docs/src/lang/en/meta.json
  packages/docs/src/lang/en/vuetify/AppDrawer.json
  packages/docs/src/snippets/html/directive_intersect.txt
  packages/docs/src/snippets/html/directive_intersect_once.txt
  packages/docs/src/snippets/html/directive_intersect_quiet.txt
  packages/vuetify/src/directives/index.ts
  packages/vuetify/src/directives/intersect/__tests__/intersect.spec.ts
  packages/vuetify/src/directives/intersect/index.ts
  packages/vuetify/src/globals.d.ts
Labels: T: feature

#9046 feat(VBtn): add retainFocusOnClick property
  packages/docs/src/lang/en/components/Buttons.json
  packages/vuetify/src/components/VBtn/VBtn.ts
  packages/vuetify/src/components/VBtn/__tests__/VBtn.spec.ts
Labels: T: feature

#8443 fix(VDataTable): fixed table row classes
  packages/vuetify/src/components/VDataTable/VDataTable.sass
  packages/vuetify/src/components/VDataTable/VDataTable.ts
  packages/vuetify/src/components/VDataTable/VSimpleTable.sass
  packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
Labels: T: bug

#8284 [Bug] fix(VDataTable): show no-results when custom filter returns zero rows
  packages/vuetify/src/components/VData/VData.ts
  packages/vuetify/src/components/VDataIterator/VDataIterator.ts
  packages/vuetify/src/components/VDataTable/VDataTable.ts
Labels: T: bug

#8511 feat(VDataFooter): added page-text prop
  packages/vuetify/src/components/VDataIterator/VDataFooter.ts
  packages/vuetify/src/locale/af.ts
  packages/vuetify/src/locale/ar.ts
  packages/vuetify/src/locale/ca.ts
  packages/vuetify/src/locale/cs.ts
  packages/vuetify/src/locale/de.ts
  packages/vuetify/src/locale/el.ts
  packages/vuetify/src/locale/en.ts
  packages/vuetify/src/locale/es.ts
  packages/vuetify/src/locale/et.ts
  packages/vuetify/src/locale/fa.ts
  packages/vuetify/src/locale/fr.ts
  packages/vuetify/src/locale/he.ts
  packages/vuetify/src/locale/hr.ts
  packages/vuetify/src/locale/hu.ts
  packages/vuetify/src/locale/id.ts
  packages/vuetify/src/locale/it.ts
  packages/vuetify/src/locale/ja.ts
  packages/vuetify/src/locale/ko.ts
  packages/vuetify/src/locale/lt.ts
  packages/vuetify/src/locale/lv.ts
  packages/vuetify/src/locale/nl.ts
  packages/vuetify/src/locale/no.ts
  packages/vuetify/src/locale/pl.ts
  packages/vuetify/src/locale/pt.ts
  packages/vuetify/src/locale/ro.ts
  packages/vuetify/src/locale/ru.ts
  packages/vuetify/src/locale/sl.ts
  packages/vuetify/src/locale/sr-Cyrl.ts
  packages/vuetify/src/locale/sv.ts
  packages/vuetify/src/locale/th.ts
  packages/vuetify/src/locale/tr.ts
  packages/vuetify/src/locale/uk.ts
  packages/vuetify/src/locale/zh-Hans.ts
  packages/vuetify/src/locale/zh-Hant.ts
  packages/vuetify/src/services/lang/__tests__/lang.spec.ts
  packages/vuetify/src/services/lang/index.ts
Labels: T: feature

#8439 feat(VDataTable): added filterable property to header items
  packages/api-generator/src/maps/v-data-table.js
  packages/docs/src/data/pages/components/DataTables.json
  packages/docs/src/examples/data-tables/simple/filterable-columns.vue
  packages/docs/src/lang/en/components/DataTables.json
  packages/vuetify/src/components/VDataTable/VDataTable.ts
  packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
  packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
  packages/vuetify/src/components/VDataTable/mixins/header.ts
Labels: T: feature

#9080 Elements with [role] that require specific children [role]s, are missing.
  packages/vuetify/src/components/VList/VListItem.ts
  packages/vuetify/src/components/VList/__tests__/VListItem.spec.ts
Labels: T: bug

#8838 fix(VCarousel): Always respect original internal height of VWindow.
  packages/vuetify/src/components/VCarousel/VCarousel.ts
  packages/vuetify/src/components/VCarousel/VCarouselItem.ts
  packages/vuetify/src/components/VWindow/VWindow.ts
  packages/vuetify/src/components/VWindow/VWindowItem.ts
  packages/vuetify/src/components/VWindow/__tests__/VWindowItem.spec.ts
Labels: needs more information

#8861 feat: added color and opacity props to overlayable mixin
  packages/docs/src/lang/en/components/BottomSheets.json
  packages/docs/src/lang/en/components/Dialogs.json
  packages/docs/src/lang/en/components/NavigationDrawers.json
  packages/docs/src/lang/en/mixins/Overlayable.json
  packages/vuetify/src/mixins/overlayable/index.ts
Labels: C: VOverlay, T: feature

#8866 fix(VCalendar): fix event-more labels in month view
  packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts
Labels: C: VCalendar, T: bug

#8768 fix(VNavigationDrawer): should emit update:mini-variant
  packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts
  packages/vuetify/src/components/VNavigationDrawer/__tests__/VNavigationDrawer.spec.ts
Labels: T: bug

#8687 fix(goTo): goTo scrolls to container top
  packages/vuetify/src/services/goto/index.ts
Labels: T: bug

#8724 fix(VTextField): should respect events in correct order (#7916)
  packages/vuetify/src/components/VTextField/VTextField.ts
  packages/vuetify/src/components/VTextField/__tests__/VTextField.spec.ts
Labels: C: VTextField, T: bug

#8891 feat(VDatePicker): pick date range
  packages/docs/src/data/pages/components/DatePickers.json
  packages/docs/src/examples/date-pickers/intermediate/date-range.vue
  packages/docs/src/lang/en/components/DatePickers.json
  packages/kitchen/src/pan/Date pickers.vue
  packages/vuetify/src/components/VDatePicker/VDatePicker.ts
  packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.date.spec.ts
Labels: C: VDatepicker, T: feature

#7582 feat(VBtnToggle): add group prop
  packages/docs/src/examples/button-groups/intermediate/app-bar.vue
  packages/docs/src/examples/button-groups/intermediate/qwerty.vue
  packages/docs/src/examples/button-groups/usage.vue
  packages/docs/src/lang/en/components/ButtonGroups.json
  packages/vuetify/src/components/VBtnToggle/VBtnToggle.sass
  packages/vuetify/src/components/VBtnToggle/VBtnToggle.ts
  packages/vuetify/src/components/VBtnToggle/__tests__/VBtnToggle.spec.ts
  packages/vuetify/src/components/VBtnToggle/_variables.sass
  packages/vuetify/src/components/VBtnToggle/_variables.scss
Labels: C: VBtnToggle, T: feature

#8681 fix(VInput): add role alert to success/error messages
  packages/vuetify/src/components/VInput/VInput.ts
  packages/vuetify/src/components/VInput/__tests__/__snapshots__/VInput.spec.ts.snap
Labels: C: VInput, T: enhancement, a11y

#7672 feat(VIcon): shorter iconName prefix
  packages/docs/src/examples/expansion-panels/intermediate/custom-icons.vue
  packages/docs/src/examples/ratings/intermediate/increments.vue
  packages/docs/src/lang/en/customization/Icons.json
  packages/docs/src/lang/fr-FR/customization/Icons.json
  packages/docs/src/lang/ru-RU/customization/Icons.json
  packages/docs/src/lang/ru-RU/framework/Icons.json
  packages/docs/src/snippets/html/custom_icons_custom_component.txt
  packages/docs/src/snippets/html/using_missing_material_icons_usage.txt
  packages/docs/src/snippets/html/vuetify_reusable_custom_icons.txt
  packages/vuetify/src/components/VAlert/VAlert.ts
  packages/vuetify/src/components/VAlert/__tests__/__snapshots__/VAlert.spec.ts.snap
  packages/vuetify/src/components/VAppBar/VAppBarNavIcon.ts
  packages/vuetify/src/components/VAppBar/__tests__/__snapshots__/VAppBarNavIcon.spec.ts.snap
  packages/vuetify/src/components/VCarousel/VCarousel.ts
  packages/vuetify/src/components/VCheckbox/VCheckbox.ts
  packages/vuetify/src/components/VCheckbox/VSimpleCheckbox.ts
  packages/vuetify/src/components/VCheckbox/__tests__/__snapshots__/VCheckbox.spec.ts.snap
  packages/vuetify/src/components/VChip/VChip.ts
  packages/vuetify/src/components/VChip/__tests__/__snapshots__/VChip.spec.ts.snap
  packages/vuetify/src/components/VColorPicker/VColorPickerEdit.ts
  packages/vuetify/src/components/VColorPicker/VColorPickerSwatches.ts
  packages/vuetify/src/components/VColorPicker/__tests__/__snapshots__/VColorPicker.spec.ts.snap
  packages/vuetify/src/components/VColorPicker/__tests__/__snapshots__/VColorPickerEdit.spec.ts.snap
  packages/vuetify/src/components/VDataIterator/VDataFooter.ts
  packages/vuetify/src/components/VDataTable/VDataTable.ts
  packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
  packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTableHeader.spec.ts.snap
  packages/vuetify/src/components/VDataTable/mixins/__tests__/__snapshots__/header.spec.ts.snap
  packages/vuetify/src/components/VDataTable/mixins/header.ts
  packages/vuetify/src/components/VDatePicker/VDatePicker.ts
  packages/vuetify/src/components/VDatePicker/VDatePickerHeader.ts
  packages/vuetify/src/components/VExpansionPanel/VExpansionPanelHeader.ts
  packages/vuetify/src/components/VExpansionPanel/__tests__/__snapshots__/VExpansionPanel.spec.ts.snap
  packages/vuetify/src/components/VFileInput/VFileInput.ts
  packages/vuetify/src/components/VFileInput/__tests__/__snapshots__/VFileInput.spec.ts.snap
  packages/vuetify/src/components/VIcon/__tests__/VIcon.spec.ts
  packages/vuetify/src/components/VList/VListGroup.ts
  packages/vuetify/src/components/VList/__tests__/__snapshots__/VListGroup.spec.ts.snap
  packages/vuetify/src/components/VOverflowBtn/__tests__/__snapshots__/VOverflowBtn.spec.ts.snap
  packages/vuetify/src/components/VPagination/VPagination.ts
  packages/vuetify/src/components/VRadioGroup/VRadio.ts
  packages/vuetify/src/components/VRadioGroup/__tests__/__snapshots__/VRadio.spec.ts.snap
  packages/vuetify/src/components/VRating/VRating.ts
  packages/vuetify/src/components/VSelect/VSelect.ts
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect.spec.ts.snap
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect2.spec.ts.snap
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect3.spec.ts.snap
  packages/vuetify/src/components/VSlideGroup/VSlideGroup.ts
  packages/vuetify/src/components/VSlideGroup/__tests__/__snapshots__/VSlideGroup.spec.ts.snap
  packages/vuetify/src/components/VStepper/VStepperStep.ts
  packages/vuetify/src/components/VTabs/VTabs.ts
  packages/vuetify/src/components/VTextField/VTextField.ts
  packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
  packages/vuetify/src/components/VTreeview/__tests__/VTreeviewNode.spec.ts
  packages/vuetify/src/components/VTreeview/__tests__/__snapshots__/VTreeview.spec.ts.snap
  packages/vuetify/src/components/VWindow/VWindow.ts
  packages/vuetify/src/util/helpers.ts
Labels: C: VIcon, T: feature

#9148 feat(mutate): add a new directive
  packages/api-generator/src/index.js
  packages/api-generator/src/maps/v-mutate.js
  packages/docs/src/data/drawerItems.json
  packages/docs/src/data/pages/directives/Mutate.json
  packages/docs/src/examples/mutate/simple/once.vue
  packages/docs/src/examples/mutate/usage.vue
  packages/docs/src/lang/en/directives/Mutate.json
  packages/docs/src/lang/en/meta.json
  packages/docs/src/lang/en/vuetify/AppDrawer.json
  packages/docs/src/public/sitemap.xml
  packages/vuetify/src/directives/index.ts
  packages/vuetify/src/directives/mutate/__tests__/mutate.spec.ts
  packages/vuetify/src/directives/mutate/index.ts
  packages/vuetify/src/globals.d.ts
Labels: D: New Directive, T: feature
