Repository vuetifyjs/vuetify, pull requests merged in 2020-08, with the labels that each got.

#12025 docs(stable): convert to spa for vercel 2
  .gitignore
  .vercelignore
  now.json
  packages/docs/.eslintignore
  packages/docs/build/generate-routes.js
  packages/docs/build/prerender.js
  packages/docs/build/setup-dev-server.js
  packages/docs/build/vue-loader.config.js
  packages/docs/build/webpack.base.config.js
  packages/docs/build/webpack.client.config.js
  packages/docs/build/webpack.server.config.js
  packages/docs/package.json
  packages/docs/server.js
  packages/docs/src/components/categories/List.vue
  packages/docs/src/components/categories/ListAlt.vue
  packages/docs/src/crowdin.template.html
  packages/docs/src/index.template.html
  packages/docs/src/spa.template.html
  vercel.json
  yarn.lock
Labels: T: documentation

#12059 fix(VListitem): disable mouse click in animating menu
  packages/vuetify/src/components/VMenu/VMenu.sass
Labels: C: VList, T: bug

#12113 fix(types): number should not be allowed as a current breakpoint name
  packages/vuetify/src/mixins/mobile/index.ts
  packages/vuetify/types/services/breakpoint.d.ts
Labels: Service: Breakpoint, typescript
