Repository vuetifyjs/vuetify, pull requests merged in 2020-10, with the labels that each got.

#12340 fix: allow $material-dark-elevation-colors to be overridden
  packages/vuetify/src/styles/settings/_dark.scss
Labels: T: bug, sass

#12192 fix(VProgressCircular): dark theme background color clash
  packages/vuetify/src/components/VProgressCircular/_variables.scss
Labels: C: VProgressCircular, T: bug

#12109 fix(click-outside): allow programmatic click outside
  packages/vuetify/src/directives/click-outside/index.ts
Labels: T: bug

#11775 feat(VDataTable): add cellClass property to headers
  packages/api-generator/src/maps/v-data-table.js
  packages/vuetify/src/components/VDataTable/Row.ts
  packages/vuetify/src/components/VDataTable/__tests__/Row.spec.ts
  packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/Row.spec.ts.snap
  packages/vuetify/types/index.d.ts
Labels: C: VDataTable, T: feature

#12338 fix(locales): th-Thai i18n translation
  packages/vuetify/src/locale/th.ts
Labels: Service: Lang, T: bug

#12343 fix(VSelect): do not open menu if clicking on selection item
  packages/vuetify/src/components/VSelect/VSelect.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect2.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect3.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/VSelect4.spec.ts
  packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect3.spec.ts.snap
Labels: C: VSelect

#11865 fix(VDataTable): on mobile, expand rows to fit text
  packages/vuetify/src/components/VDataTable/VDataTable.sass
Labels: C: VDataTable, T: bug

#12319 fix(VIcon): set svg dimensions in style instead of attributes
  packages/vuetify/src/components/VIcon/VIcon.ts
  packages/vuetify/src/components/VIcon/__tests__/__snapshots__/VIcon.spec.ts.snap
Labels: C: VIcon, T: bug

#12031 fix(VAutocomplete): set isFocused to false on blur
  packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete.spec.ts
  packages/vuetify/src/components/VSelect/VSelect.ts
Labels: C: VAutocomplete, T: bug

#12163 fix(VSelect): do not highlight search text without an item match
  packages/vuetify/src/components/VSelect/VSelectList.ts
Labels: C: VAutocomplete, T: bug

#12355 docs: update contributing guide
  packages/docs/src/pages/en/getting-started/contributing.md
Labels: T: documentation

#12344 feat: add global prop defaults, update bootstrapping
  packages/vuetify/dev/index.js
  packages/vuetify/src/composables/__tests__/elevation.spec.ts
  packages/vuetify/src/composables/elevation.ts
  packages/vuetify/src/composables/index.ts
  packages/vuetify/src/entry-lib.ts
  packages/vuetify/src/framework.ts
  packages/vuetify/src/index.ts
  packages/vuetify/src/install.ts
  yarn.lock
Labels: Framework

#12429 fix(icons): use correct mdi icon for rating-half
  packages/vuetify/src/services/icons/__tests__/__snapshots__/icons.spec.ts.snap
  packages/vuetify/src/services/icons/presets/mdi.ts
Labels: C: VRating, Service: Icons, T: bug

#12440 refactor: Added styling to the table of why vuetify section
  packages/docs/src/components/vuetify/Comparison.vue
Labels: T: documentation

#12451 fix(VTextField): count characters instead of codepoints
  packages/vuetify/src/components/VTextField/VTextField.ts
Labels: C: VTextField, T: bug

#12439 docs: add utm metadata to ads
  packages/docs/src/components/ad/Bsa.vue
  packages/docs/src/components/ad/Discovery.vue
  packages/docs/src/components/ad/Entry.vue
  packages/docs/src/components/ad/Exit.vue
  packages/docs/src/components/ad/Promoted.vue
  packages/docs/src/components/ad/Random.vue
  packages/docs/src/components/doc/PremiumThemes.vue
  packages/docs/src/components/doc/links/StoreLink.vue
  packages/docs/src/mixins/ad.js
Labels: T: documentation

#12386 fix(VLinearProgress): remove unnecessary z-index
  packages/vuetify/src/components/VProgressLinear/VProgressLinear.sass
Labels: C: VProgressLinear, T: bug

#10420 refactor(ripple): update for v3
  packages/vuetify/babel.config.js
  packages/vuetify/src/directives/index.ts
  packages/vuetify/src/directives/ripple/__tests__/ripple.spec.ts
  packages/vuetify/src/directives/ripple/index.ts
  packages/vuetify/src/globals.d.ts
  packages/vuetify/tsconfig.json
Labels: C: VRipple

#10418 feat(size): create new effect
  packages/vuetify/src/composables/__tests__/size.spec.ts
  packages/vuetify/src/composables/size.ts
  packages/vuetify/src/mixins/sizeable/index.ts
Labels: Framework, T: feature

#12502 docs: fix radio button mandatory props default
  packages/docs/src/examples/v-radio-group/prop-mandatory.vue
  packages/docs/src/pages/en/components/radio-buttons.md
Labels: C: VRadioGroup, T: documentation

#12498 feat(framework): add (global) global default prop values
  packages/vuetify/src/__tests__/__mocks__/vue.ts
  packages/vuetify/src/__tests__/__snapshots__/framework.spec.ts.snap
  packages/vuetify/src/__tests__/framework.spec.ts
  packages/vuetify/src/framework.ts
  packages/vuetify/src/util/__tests__/__snapshots__/makeProps.spec.ts.snap
  packages/vuetify/src/util/__tests__/makeProps.spec.ts
  packages/vuetify/src/util/makeProps.ts
Labels: T: enhancement, testing
