Repository vuetifyjs/vuetify, pull requests merged in 2021-04, with the labels that each got.

#13373 docs(upgrade-guide): add note about `v-app-bar-nav-icon`
  packages/docs/src/pages/en/getting-started/upgrade-guide.md
Labels: T: documentation

#13365 style: sort imported members
  .eslintrc.js
  packages/vuetify/src/components/VGrid/VCol.ts
  packages/vuetify/src/components/VImg/VImg.tsx
  packages/vuetify/src/components/VLayout/VLayout.tsx
  packages/vuetify/src/components/VLayout/VLayoutItem.tsx
  packages/vuetify/src/components/VResponsive/VResponsive.tsx
  packages/vuetify/src/components/transitions/createTransition.ts
  packages/vuetify/src/composables/color.ts
  packages/vuetify/src/composables/delay.ts
  packages/vuetify/src/composables/group.ts
  packages/vuetify/src/composables/icons.tsx
  packages/vuetify/src/composables/layout.ts
  packages/vuetify/src/composables/proxiedModel.ts
  packages/vuetify/src/composables/scroll.ts
  packages/vuetify/src/composables/theme.ts
  packages/vuetify/src/directives/scroll/__tests__/scroll.spec.ts
  packages/vuetify/src/framework.ts
  packages/vuetify/src/globals.d.ts
  packages/vuetify/src/iconsets/fa.ts
  packages/vuetify/src/iconsets/fa4.ts
  packages/vuetify/src/iconsets/md.ts
  packages/vuetify/src/iconsets/mdi-svg.ts
  packages/vuetify/src/iconsets/mdi.ts
  packages/vuetify/src/util/__tests__/console.spec.ts
  packages/vuetify/src/util/__tests__/helpers.spec.ts
  packages/vuetify/src/util/color/transformCIELAB.ts
  packages/vuetify/src/util/createSimpleFunctional.ts
  packages/vuetify/src/util/helpers.ts
  packages/vuetify/src/util/useDirective.ts
Labels: task

#13005 fix(VSlideGroup): detect horizontal/vertical swipe intent
  packages/vuetify/src/components/VSlideGroup/VSlideGroup.sass
  packages/vuetify/src/components/VSlideGroup/VSlideGroup.ts
Labels: C: VSlideGroup, T: bug

#13408 Change `Connecting Settings` to `Connection Settings`
  packages/docs/src/examples/v-banner/event-icon-click.vue
Labels: T: documentation

#13418 docs(v-hover): fix broken image links
  packages/docs/src/examples/v-hover/misc-hover-list.vue
Labels: T: documentation

#13416 docs(v-sparkline): fix gradient selection in v-sparkline example
  packages/docs/src/examples/v-sparkline/prop-fill.vue
Labels: T: documentation

#13439 fix(VSelect): resolve "Expected identifier." error
  packages/vuetify/src/components/VCalendar/VCalendarCategory.sass
  packages/vuetify/src/components/VCalendar/VCalendarDaily.sass
  packages/vuetify/src/components/VSelect/VSelect.sass
  packages/vuetify/src/components/VWindow/VWindow.sass
Labels: P: critical

#13454 docs(selects): update readonly example description
  packages/docs/src/pages/en/components/selects.md
Labels: C: VSelect, T: documentation

#13413 fix(locale): update japanese translation
  packages/vuetify/src/locale/ja.ts
Labels: T: documentation

#13361 fix(VExpansionPanels): change aria-expanded to use isActive
  packages/vuetify/src/components/VExpansionPanel/VExpansionPanelHeader.ts
Labels: C: VExpansionPanel, T: bug, a11y

#13357 fix(VBreadcrumbs): remove duplicate scss var
  packages/vuetify/src/components/VBreadcrumbs/_variables.scss
Labels: C: VBreadcrumb, T: bug, sass

#13382 fix(VCombobox): reset editingIndex after clear
  packages/vuetify/src/components/VCombobox/VCombobox.ts
  packages/vuetify/src/components/VCombobox/__tests__/VCombobox-multiple.spec.ts
Labels: C: VCombobox, T: bug

#13420 fix(VCheckbox): add variable checkbox-dense-padding-top
  packages/vuetify/src/components/VCheckbox/VCheckbox.sass
  packages/vuetify/src/components/VCheckbox/_variables.scss
Labels: C: VCheckbox

#13542 docs(installation): fix typo
  packages/docs/src/pages/en/getting-started/installation.md
Labels: T: documentation

#13547 docs(sponsors-and-backers.md): update sponsors link markdown
  packages/docs/src/pages/en/about/sponsors-and-backers.md
Labels: T: documentation

#11921 feat(VDataTable): Add shift key logic for multiple selection
  packages/vuetify/src/components/VDataIterator/VDataIterator.ts
  packages/vuetify/src/util/helpers.ts
Labels: C: VDataTable, T: feature

#11975 feat(VDataTable): Add checkboxColor prop
  packages/api-generator/src/locale/en/v-data-table.json
  packages/api-generator/src/maps/v-data.js
  packages/vuetify/src/components/VDataTable/VDataTable.ts
  packages/vuetify/src/components/VDataTable/mixins/__tests__/__snapshots__/header.spec.ts.snap
  packages/vuetify/src/components/VDataTable/mixins/header.ts
Labels: C: VData, C: VDataTable, T: feature

#13318 feat(display): port to v3
  packages/api-generator/src/index.js
  packages/api-generator/src/locale/en/display.json
  packages/api-generator/src/maps/composables/display.js
  packages/docs/src/data/nav-alpha.json
  packages/docs/src/data/page-to-api.json
  packages/docs/src/pages/en/features/display-and-platform.md
  packages/vuetify/src/components/VBottomSheet/VBottomSheet.sass
  packages/vuetify/src/components/VGrid/VCol.ts
  packages/vuetify/src/components/VGrid/VRow.ts
  packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.tsx
  packages/vuetify/src/components/VNavigationDrawer/__tests__/VNavigationDrawer.spec.tsx
  packages/vuetify/src/components/VNavigationDrawer/__tests__/__snapshots__/VNavigationDrawer.spec.tsx.snap
  packages/vuetify/src/components/VStepper/VStepper.sass
  packages/vuetify/src/composables/__tests__/display.spec.ts
  packages/vuetify/src/composables/display.ts
  packages/vuetify/src/framework.ts
  packages/vuetify/src/styles/settings/_variables.scss
  packages/vuetify/test/index.ts
  packages/vuetify/test/util/to-have-been-warned.ts
Labels: Service: Breakpoint, T: feature, V3: Phase 1

#13336 feat: add locale composable
  package.json
  packages/docs/src/data/nav-alpha.json
  packages/docs/src/pages/en/features/internationalization.md
  packages/vuetify/dev/App.vue
  packages/vuetify/dev/index.js
  packages/vuetify/dev/vuetify.js
  packages/vuetify/src/components/VApp/VApp.sass
  packages/vuetify/src/components/VApp/VApp.tsx
  packages/vuetify/src/components/VApp/__tests__/VApp.spec.ts
  packages/vuetify/src/components/VApp/__tests__/__snapshots__/VApp.spec.ts.snap
  packages/vuetify/src/components/VLocaleProvider/VLocaleProvider.tsx
  packages/vuetify/src/components/VLocaleProvider/index.ts
  packages/vuetify/src/components/index.ts
  packages/vuetify/src/composables/locale.ts
  packages/vuetify/src/composables/rtl.ts
  packages/vuetify/src/entry-bundler.ts
  packages/vuetify/src/framework.ts
  packages/vuetify/src/locale/__tests__/index.spec.ts
  packages/vuetify/src/locale/index.ts
  packages/vuetify/src/styles/generic/_index.scss
  packages/vuetify/src/styles/generic/_rtl.scss
  packages/vuetify/src/styles/tools/_rtl.sass
  packages/vuetify/src/styles/tools/_utilities.sass
  packages/vuetify/src/util/helpers.ts
  yarn.lock
Labels: Service: Lang, T: feature, V3: Phase 2

#13409 fix(VAppBarTitle): export VAppBarTitle types
  packages/vuetify/types/lib.d.ts
Labels: C: VAppBar, T: bug

#13128 docs: added changes to divider and banner for v3
  packages/docs/src/pages/en/components/banners.md
  packages/docs/src/pages/en/components/dividers.md
Labels: T: documentation

#13561 refactor(VIcon): update default color, abstract variables
  packages/vuetify/src/components/VIcon/VIcon.sass
  packages/vuetify/src/components/VIcon/_variables.scss
  packages/vuetify/src/composables/__tests__/__snapshots__/theme.spec.ts.snap
  packages/vuetify/src/composables/theme.ts
Labels: C: VIcon, sass
