Repository vuetifyjs/vuetify, pull requests merged in 2024-10, with the labels that each got.

#20464 docs: fix grammatical error
  packages/docs/src/pages/en/components/data-tables/data-and-display.md
Labels: T: documentation

#20425 docs: make the service worker optional, improve precache logic
  docker-compose.yml
  packages/docs/auto-imports.d.ts
  packages/docs/components.d.ts
  packages/docs/src/components/app/bar/SettingsToggle.vue
  packages/docs/src/components/app/settings/DeveloperMode.vue
  packages/docs/src/components/app/settings/Drawer.vue
  packages/docs/src/components/app/settings/Options.vue
  packages/docs/src/components/app/settings/SettingsHeader.vue
  packages/docs/src/components/app/settings/options/AdOption.vue
  packages/docs/src/components/app/settings/options/ApiOption.vue
  packages/docs/src/components/app/settings/options/CodeOption.vue
  packages/docs/src/components/app/settings/options/OfflineOption.vue
  packages/docs/src/components/app/settings/options/PinOption.vue
  packages/docs/src/components/app/settings/options/SlashSearchOption.vue
  packages/docs/src/i18n/messages/en.json
  packages/docs/src/plugins/pwa.ts
  packages/docs/src/plugins/vuetify.ts
  packages/docs/src/service-worker.js
  packages/docs/src/shims.d.ts
  packages/docs/src/stores/pwa.ts
  packages/docs/src/utils/pwa.ts
  packages/docs/tsconfig.json
  packages/docs/vite.config.mts
Labels: T: documentation

#20541 docs(VForm): remove hide-details from usage example
  packages/docs/src/examples/v-form/usage.vue
Labels: T: documentation

#20619 docs: ensure clipboard copies the correct command from snippet
  packages/docs/src/components/home/Entry.vue
Labels: T: documentation

#20628 docs(team.json): Added shinji's profile
  packages/docs/src/data/team.json
Labels: T: documentation

#20627 docs(VForm): correct typo in validation message in example
  packages/docs/src/examples/v-form/usage.vue
Labels: T: documentation

#20526 docs(VInput): correct hint props description
  packages/docs/src/pages/en/components/inputs.md
Labels: T: documentation

#20340 docs: update nuxt 3 manual setup
  packages/docs/src/pages/en/getting-started/installation.md
Labels: T: documentation, NUXT

#20363 docs(VTreeView): fix divider in example
  packages/docs/src/examples/v-treeview/misc-selectable-icons.vue
Labels: T: documentation

#20629 docs(team.json): Fixed github name
  packages/docs/src/data/team.json
Labels: T: documentation

#20373 docs(VList): streamline examples with selectable actions
  packages/docs/src/examples/v-list/misc-action-and-item-groups.vue
  packages/docs/src/examples/v-list/misc-actions.vue
  packages/docs/src/pages/en/components/lists.md
Labels: T: documentation, C: VList

#20631 docs(VList): fix opening last example in playground
  packages/docs/src/examples/v-list/misc-actions.vue
Labels: T: documentation

#20455 docs(VDataTable): update slot-headers example to use header cells
  packages/docs/src/examples/v-data-table/slot-headers.vue
Labels: T: documentation, C: VDataTable

#20640 docs(VDataTableHeaders.json): Added missing description of VDataTableHeaders
  packages/api-generator/src/locale/en/VDataTableHeaders.json
Labels: T: documentation

#20648 docs(api): add missing table slot descriptions
  packages/api-generator/src/locale/en/VDataTableRow.json
  packages/api-generator/src/locale/en/VDataTableRows.json
Labels: T: documentation
