Repository vuetifyjs/vuetify, pull requests merged in 2024-08, with the labels that each got.

#19933 docs(elevation): use bold formatting for class names in elevation utility table
  packages/docs/src/pages/en/styles/elevation.md
Labels: T: documentation

#19940 docs(VListItem): provide more detailed descriptions for item selection
  packages/api-generator/src/locale/en/VListItem.json
  packages/docs/src/pages/en/getting-started/upgrade-guide.md
Labels: T: documentation

#20192 fix(VTreeview): don't expose open
  packages/vuetify/src/labs/VTreeview/VTreeview.tsx
Labels: T: bug, C: VTreeview, labs

#20260 docs: optimize build
  .github/actions/pnpm-install/action.yml
  .nvmrc
  package.json
  packages/api-generator/package.json
  packages/docs/auto-imports.d.ts
  packages/docs/build/api-plugin.ts
  packages/docs/build/frontmatterMeta.ts
  packages/docs/build/markdown-it.ts
  packages/docs/build/mdi-js.ts
  packages/docs/components.d.ts
  packages/docs/jest.config.js
  packages/docs/package.json
  packages/docs/src/App.vue
  packages/docs/src/components/PageFeatures.vue
  packages/docs/src/components/api/Backlinks.vue
  packages/docs/src/components/api/Inline.vue
  packages/docs/src/components/api/Section.vue
  packages/docs/src/components/api/View.vue
  packages/docs/src/components/app/Markdown.vue
  packages/docs/src/components/app/Toc.vue
  packages/docs/src/components/app/list/List.vue
  packages/docs/src/components/app/search/Search.vue
  packages/docs/src/components/app/search/SearchDialog.vue
  packages/docs/src/components/doc/Explorer.vue
  packages/docs/src/components/doc/IconList.vue
  packages/docs/src/components/doc/MadeWithVuetifyGallery.vue
  packages/docs/src/components/doc/RelatedPages.vue
  packages/docs/src/composables/frontmatter.ts
  packages/docs/src/examples/v-overlay/misc-advanced.vue
  packages/docs/src/examples/v-progress-linear/misc-buffer-color.vue
  packages/docs/src/pages/en/api/[name].md
  packages/docs/src/plugins/global-components.ts
  packages/docs/src/plugins/icons.ts
  packages/docs/src/plugins/vuetify.ts
  packages/docs/src/shims.d.ts
  packages/docs/src/stores/made-with-vuetify.ts
  packages/docs/src/utils/helpers.ts
  packages/docs/tsconfig.json
  packages/docs/vite.config.mts
  packages/vuetify/package.json
  packages/vuetify/src/composables/location.ts
  packages/vuetify/src/util/propsFactory.ts
  patches/@mdi__js@7.4.47.patch
  pnpm-lock.yaml
  tsconfig.json
Labels: T: documentation

#20315 docs(useDisplay): replace deprecated properties
  packages/docs/src/pages/en/features/display-and-platform.md
  packages/docs/src/pages/en/getting-started/upgrade-guide.md
Labels: T: documentation

#20207 fix(VFileInput): emit null after VForm reset()
  packages/vuetify/src/components/VFileInput/VFileInput.tsx
Labels: T: bug, C: VFileInput

#20269 docs(installation): Correct Vitepress installation steps
  packages/docs/src/pages/en/getting-started/installation.md
Labels: T: documentation

#20326 docs: add vuetify-nuxt-module to nuxt install section
  packages/docs/src/pages/en/getting-started/installation.md
Labels: T: documentation

#20364 fix(VTreeview): Load children when expanded
  packages/vuetify/src/labs/VTreeview/VTreeviewChildren.tsx
Labels: T: bug, C: VTreeview
